scoreboard objectives add AAEK dummy AAEK
scoreboard objectives add AAEKЗ dummy AAEKЗ
scoreboard objectives add AAEKЖ dummy AAEKЖ
scoreboard objectives add AAEKЗЖ dummy AAEKЗЖ
scoreboard objectives add AAEKЖЗ dummy AAEKЖЗ
scoreboard objectives add AAEKГ dummy AAEKГ
scoreboard objectives add AAEKГЗ dummy AAEKГЗ
scoreboard objectives add AAEKГГГ dummy AAEKГГГ
scoreboard objectives add AAEKД dummy AAEKД
scoreboard objectives add AAEKДГ dummy AAEKДГ
scoreboard objectives add AAEKSГГГ dummy AAEKSГГГ
scoreboard objectives add AAEL dummy AAEL
scoreboard objectives add AAELГ dummy AAELГ
scoreboard objectives add AAEWM dummy AAEWM
scoreboard objectives add AAEWMГ dummy AAEWMГ
scoreboard objectives add AAEWMГГГ dummy AAEWMГГГ
scoreboard objectives add AAEW dummy AAEW
scoreboard objectives add AAEWГ dummy AAEWГ
scoreboard objectives add AAEWЗ dummy AAEWЗ
scoreboard objectives add AAFW dummy AAFW
scoreboard objectives add AAFWГ dummy AAFWГ
scoreboard objectives add AAGЗ dummy AAGЗ
scoreboard objectives add AAG dummy AAG
scoreboard objectives add AAJ dummy AAJ
scoreboard objectives add AAE1 dummy AAE1
scoreboard objectives add AAE1Г dummy AAE1Г
scoreboard objectives add AAE2 dummy AAE2
scoreboard objectives add AAE2Г dummy AAE2Г
scoreboard objectives add ABFV dummy ABFV
scoreboard objectives add ABFVГ dummy ABFVГ
scoreboard objectives add ABEV dummy ABEV
scoreboard objectives add ABEVГ dummy ABEVГ
scoreboard objectives add ABGЗ dummy ABGЗ
scoreboard objectives add ABG dummy ABG
scoreboard objectives add ABFQ dummy ABFQ
scoreboard objectives add ABFQЗ dummy ABFQЗ
scoreboard objectives add ABFQЖ dummy ABFQЖ
scoreboard objectives add ABFQГ dummy ABFQГ
scoreboard objectives add ABFQГЗ dummy ABFQГЗ
scoreboard objectives add ABFQГЖ dummy ABFQГЖ
scoreboard objectives add ABFQГГ dummy ABFQГГ
scoreboard objectives add ABFQГГГ dummy ABFQГГГ
scoreboard objectives add ABFБ dummy ABFБ
scoreboard objectives add ABFБГ dummy ABFБГ
scoreboard objectives add ABFБГГГ dummy ABFБГГГ
scoreboard objectives add ABFБZ dummy ABFБZ
scoreboard objectives add ABFБZГ dummy ABFБZГ
scoreboard objectives add ABFБZГГГ dummy ABFБZГГГ
scoreboard objectives add ABJ dummy ABJ
scoreboard objectives add ACFP dummy ACFP
scoreboard objectives add ACFPГ dummy ACFPГ
scoreboard objectives add ACFPГГ dummy ACFPГГ
scoreboard objectives add ACFPГГГ dummy ACFPГГГ
scoreboard objectives add ACFPM dummy ACFPM
scoreboard objectives add ACFPMГ dummy ACFPMГ
scoreboard objectives add ACFPMГГГ dummy ACFPMГГГ
scoreboard objectives add ACFPMЗ dummy ACFPMЗ
scoreboard objectives add ACFPMГЗ dummy ACFPMГЗ
scoreboard objectives add ACFPMГГГЗ dummy ACFPMГГГЗ
scoreboard objectives add ACFPW dummy ACFPW
scoreboard objectives add ACFPWЗ dummy ACFPWЗ
scoreboard objectives add ACFT dummy ACFT
scoreboard objectives add ACFTЖ dummy ACFTЖ
scoreboard objectives add ACFTЗ dummy ACFTЗ
scoreboard objectives add ACFQ dummy ACFQ
scoreboard objectives add ACFQЖ dummy ACFQЖ
scoreboard objectives add ACFQЗ dummy ACFQЗ
scoreboard objectives add ACFQГ dummy ACFQГ
scoreboard objectives add ACFQГЗ dummy ACFQГЗ
scoreboard objectives add ACFZ dummy ACFZ
scoreboard objectives add ACFZЖ dummy ACFZЖ
scoreboard objectives add ACFZЗ dummy ACFZЗ
scoreboard objectives add ACFO dummy ACFO
scoreboard objectives add ACFOЗ dummy ACFOЗ
scoreboard objectives add ACFOЖ dummy ACFOЖ
scoreboard objectives add ACFOГ dummy ACFOГ
scoreboard objectives add ACFOГЗ dummy ACFOГЗ
scoreboard objectives add ACFOГЖ dummy ACFOГЖ
scoreboard objectives add ACFOГГГ dummy ACFOГГГ
scoreboard objectives add ACFOГГГЗ dummy ACFOГГГЗ
scoreboard objectives add ACFOГГГЖ dummy ACFOГГГЖ
scoreboard objectives add ACFOQГГГ dummy ACFOQГГГ
scoreboard objectives add ACFOQГГГЗ dummy ACFOQГГГЗ
scoreboard objectives add ACFS dummy ACFS
scoreboard objectives add ACJ dummy ACJ
scoreboard objectives add ACG dummy ACG
scoreboard objectives add ACGЗ dummy ACGЗ
scoreboard objectives add ACF2 dummy ACF2
scoreboard objectives add ACIU dummy ACIU
scoreboard objectives add ACIUГ dummy ACIUГ
scoreboard objectives add ACFPU dummy ACFPU
scoreboard objectives add ACFPUЖ dummy ACFPUЖ
scoreboard objectives add ACFPUГГГЖ dummy ACFPUГГГЖ
scoreboard objectives add ADITX dummy ADITX
scoreboard objectives add ADGZЗ dummy ADGZЗ
scoreboard objectives add ADFM dummy ADFM
scoreboard objectives add ADFMP dummy ADFMP
scoreboard objectives add ADFPZЖ dummy ADFPZЖ
scoreboard objectives add ADFY dummy ADFY
scoreboard objectives add ADFYГ dummy ADFYГ
scoreboard objectives add ADFYГГГ dummy ADFYГГГ
scoreboard objectives add ADEY dummy ADEY
scoreboard objectives add ADEYГ dummy ADEYГ
scoreboard objectives add ADEYГГГ dummy ADEYГГГ
scoreboard objectives add ADFБX dummy ADFБX
scoreboard objectives add ADFБXK dummy ADFБXK
scoreboard objectives add ADFXY dummy ADFXY
scoreboard objectives add ADFXYГ dummy ADFXYГ
scoreboard objectives add ADFXYГГГ dummy ADFXYГГГ
scoreboard objectives add ADFБ dummy ADFБ
scoreboard objectives add ADFБS dummy ADFБS
scoreboard objectives add ADFБM dummy ADFБM
scoreboard objectives add ADFT dummy ADFT
scoreboard objectives add ADET dummy ADET
scoreboard objectives add ADETГ dummy ADETГ
scoreboard objectives add ADETЗ dummy ADETЗ
scoreboard objectives add ADETГЗ dummy ADETГЗ
scoreboard objectives add ADEZ dummy ADEZ
scoreboard objectives add ADEZГ dummy ADEZГ
scoreboard objectives add ADEZГГГ dummy ADEZГГГ
scoreboard objectives add ADEZЗ dummy ADEZЗ
scoreboard objectives add ADEZГЗ dummy ADEZГЗ
scoreboard objectives add ADEZM dummy ADEZM
scoreboard objectives add ADEZMГ dummy ADEZMГ
scoreboard objectives add ADEZMГГГ dummy ADEZMГГГ
scoreboard objectives add ADEZMЗ dummy ADEZMЗ
scoreboard objectives add ADEZMГЗ dummy ADEZMГЗ
scoreboard objectives add ADFZ dummy ADFZ
scoreboard objectives add ADFZГ dummy ADFZГ
scoreboard objectives add ADFZГГГ dummy ADFZГГГ
scoreboard objectives add ADFZMГ dummy ADFZMГ
scoreboard objectives add ADFZЗ dummy ADFZЗ
scoreboard objectives add ADFZГЗ dummy ADFZГЗ
scoreboard objectives add ADFZГГГЗ dummy ADFZГГГЗ
scoreboard objectives add ADFZЖ dummy ADFZЖ
scoreboard objectives add ADEN dummy ADEN
scoreboard objectives add ADENГ dummy ADENГ
scoreboard objectives add ADENГГГ dummy ADENГГГ
scoreboard objectives add ADFNГ dummy ADFNГ
scoreboard objectives add ADFNГГГ dummy ADFNГГГ
scoreboard objectives add ADHXZTUГЖЗ dummy ADHXZTUГЖЗ
scoreboard objectives add ADFXMД dummy ADFXMД
scoreboard objectives add ADFXMГ dummy ADFXMГ
scoreboard objectives add ADFXMГГ dummy ADFXMГГ
scoreboard objectives add ADFXMГГГ dummy ADFXMГГГ
scoreboard objectives add ADIR dummy ADIR
scoreboard objectives add ADJM dummy ADJM
scoreboard objectives add ADJMГ dummy ADJMГ
scoreboard objectives add ADJ dummy ADJ
scoreboard objectives add ADJZ dummy ADJZ
scoreboard objectives add ADGЗ dummy ADGЗ
scoreboard objectives add ADG dummy ADG
scoreboard objectives add ADGД dummy ADGД
scoreboard objectives add ADGДЗ dummy ADGДЗ
scoreboard objectives add ADFXP dummy ADFXP
scoreboard objectives add ADFXPГ dummy ADFXPГ
scoreboard objectives add ADFXPГГГ dummy ADFXPГГГ
scoreboard objectives add ADI2 dummy ADI2
scoreboard objectives add ADI2K dummy ADI2K
scoreboard objectives add ADI2M dummy ADI2M
scoreboard objectives add ADI2MK dummy ADI2MK
scoreboard objectives add ADIU dummy ADIU
scoreboard objectives add ADIUЖ dummy ADIUЖ
scoreboard objectives add ADIUГГГ dummy ADIUГГГ
scoreboard objectives add ADIUГГГЖ dummy ADIUГГГЖ

scoreboard objectives add BAEK dummy BAEK
scoreboard objectives add BAEKЗ dummy BAEKЗ
scoreboard objectives add BAEKЖ dummy BAEKЖ
scoreboard objectives add BAEKЗЖ dummy BAEKЗЖ
scoreboard objectives add BAEKЖЗ dummy BAEKЖЗ
scoreboard objectives add BAEKГ dummy BAEKГ
scoreboard objectives add BAEKГЗ dummy BAEKГЗ
scoreboard objectives add BAEKГГГ dummy BAEKГГГ
scoreboard objectives add BAEKД dummy BAEKД
scoreboard objectives add BAEKДГ dummy BAEKДГ
scoreboard objectives add BAEKSГГГ dummy BAEKSГГГ
scoreboard objectives add BAEL dummy BAEL
scoreboard objectives add BAELГ dummy BAELГ
scoreboard objectives add BAEWM dummy BAEWM
scoreboard objectives add BAEWMГ dummy BAEWMГ
scoreboard objectives add BAEWMГГГ dummy BAEWMГГГ
scoreboard objectives add BAEW dummy BAEW
scoreboard objectives add BAEWГ dummy BAEWГ
scoreboard objectives add BAEWЗ dummy BAEWЗ
scoreboard objectives add BAFW dummy BAFW
scoreboard objectives add BAFWГ dummy BAFWГ
scoreboard objectives add BAGЗ dummy BAGЗ
scoreboard objectives add BAG dummy BAG
scoreboard objectives add BAJ dummy BAJ
scoreboard objectives add BAE1 dummy BAE1
scoreboard objectives add BAE1Г dummy BAE1Г
scoreboard objectives add BAE2 dummy BAE2
scoreboard objectives add BAE2Г dummy BAE2Г
scoreboard objectives add BBFV dummy BBFV
scoreboard objectives add BBFVГ dummy BBFVГ
scoreboard objectives add BBEV dummy BBEV
scoreboard objectives add BBEVГ dummy BBEVГ
scoreboard objectives add BBGЗ dummy BBGЗ
scoreboard objectives add BBG dummy BBG
scoreboard objectives add BBFQ dummy BBFQ
scoreboard objectives add BBFQЗ dummy BBFQЗ
scoreboard objectives add BBFQЖ dummy BBFQЖ
scoreboard objectives add BBFQГ dummy BBFQГ
scoreboard objectives add BBFQГЗ dummy BBFQГЗ
scoreboard objectives add BBFQГЖ dummy BBFQГЖ
scoreboard objectives add BBFQГГ dummy BBFQГГ
scoreboard objectives add BBFQГГГ dummy BBFQГГГ
scoreboard objectives add BBFБ dummy BBFБ
scoreboard objectives add BBFБГ dummy BBFБГ
scoreboard objectives add BBFБГГГ dummy BBFБГГГ
scoreboard objectives add BBFБZ dummy BBFБZ
scoreboard objectives add BBFБZГ dummy BBFБZГ
scoreboard objectives add BBFБZГГГ dummy BBFБZГГГ
scoreboard objectives add BBJ dummy BBJ
scoreboard objectives add BCFP dummy BCFP
scoreboard objectives add BCFPГ dummy BCFPГ
scoreboard objectives add BCFPГГ dummy BCFPГГ
scoreboard objectives add BCFPГГГ dummy BCFPГГГ
scoreboard objectives add BCFPM dummy BCFPM
scoreboard objectives add BCFPMГ dummy BCFPMГ
scoreboard objectives add BCFPMГГГ dummy BCFPMГГГ
scoreboard objectives add BCFPMЗ dummy BCFPMЗ
scoreboard objectives add BCFPMГЗ dummy BCFPMГЗ
scoreboard objectives add BCFPMГГГЗ dummy BCFPMГГГЗ
scoreboard objectives add BCFPW dummy BCFPW
scoreboard objectives add BCFPWЗ dummy BCFPWЗ
scoreboard objectives add BCFT dummy BCFT
scoreboard objectives add BCFTЖ dummy BCFTЖ
scoreboard objectives add BCFTЗ dummy BCFTЗ
scoreboard objectives add BCFQ dummy BCFQ
scoreboard objectives add BCFQЖ dummy BCFQЖ
scoreboard objectives add BCFQЗ dummy BCFQЗ
scoreboard objectives add BCFQГ dummy BCFQГ
scoreboard objectives add BCFQГЗ dummy BCFQГЗ
scoreboard objectives add BCFZ dummy BCFZ
scoreboard objectives add BCFZЖ dummy BCFZЖ
scoreboard objectives add BCFZЗ dummy BCFZЗ
scoreboard objectives add BCFO dummy BCFO
scoreboard objectives add BCFOЗ dummy BCFOЗ
scoreboard objectives add BCFOЖ dummy BCFOЖ
scoreboard objectives add BCFOГ dummy BCFOГ
scoreboard objectives add BCFOГЗ dummy BCFOГЗ
scoreboard objectives add BCFOГЖ dummy BCFOГЖ
scoreboard objectives add BCFOГГГ dummy BCFOГГГ
scoreboard objectives add BCFOГГГЗ dummy BCFOГГГЗ
scoreboard objectives add BCFOГГГЖ dummy BCFOГГГЖ
scoreboard objectives add BCFOQГГГ dummy BCFOQГГГ
scoreboard objectives add BCFOQГГГЗ dummy BCFOQГГГЗ
scoreboard objectives add BCFS dummy BCFS
scoreboard objectives add BCJ dummy BCJ
scoreboard objectives add BCG dummy BCG
scoreboard objectives add BCGЗ dummy BCGЗ
scoreboard objectives add BCF2 dummy BCF2
scoreboard objectives add BCIU dummy BCIU
scoreboard objectives add BCIUГ dummy BCIUГ
scoreboard objectives add BCFPU dummy BCFPU
scoreboard objectives add BCFPUЖ dummy BCFPUЖ
scoreboard objectives add BCFPUГГГЖ dummy BCFPUГГГЖ
scoreboard objectives add BDITX dummy BDITX
scoreboard objectives add BDGZЗ dummy BDGZЗ
scoreboard objectives add BDFM dummy BDFM
scoreboard objectives add BDFMP dummy BDFMP
scoreboard objectives add BDFPZЖ dummy BDFPZЖ
scoreboard objectives add BDFY dummy BDFY
scoreboard objectives add BDFYГ dummy BDFYГ
scoreboard objectives add BDFYГГГ dummy BDFYГГГ
scoreboard objectives add BDEY dummy BDEY
scoreboard objectives add BDEYГ dummy BDEYГ
scoreboard objectives add BDEYГГГ dummy BDEYГГГ
scoreboard objectives add BDFБX dummy BDFБX
scoreboard objectives add BDFБXK dummy BDFБXK
scoreboard objectives add BDFXY dummy BDFXY
scoreboard objectives add BDFXYГ dummy BDFXYГ
scoreboard objectives add BDFXYГГГ dummy BDFXYГГГ
scoreboard objectives add BDFБ dummy BDFБ
scoreboard objectives add BDFБS dummy BDFБS
scoreboard objectives add BDFБM dummy BDFБM
scoreboard objectives add BDFT dummy BDFT
scoreboard objectives add BDET dummy BDET
scoreboard objectives add BDETГ dummy BDETГ
scoreboard objectives add BDETЗ dummy BDETЗ
scoreboard objectives add BDETГЗ dummy BDETГЗ
scoreboard objectives add BDEZ dummy BDEZ
scoreboard objectives add BDEZГ dummy BDEZГ
scoreboard objectives add BDEZГГГ dummy BDEZГГГ
scoreboard objectives add BDEZЗ dummy BDEZЗ
scoreboard objectives add BDEZГЗ dummy BDEZГЗ
scoreboard objectives add BDEZM dummy BDEZM
scoreboard objectives add BDEZMГ dummy BDEZMГ
scoreboard objectives add BDEZMГГГ dummy BDEZMГГГ
scoreboard objectives add BDEZMЗ dummy BDEZMЗ
scoreboard objectives add BDEZMГЗ dummy BDEZMГЗ
scoreboard objectives add BDFZ dummy BDFZ
scoreboard objectives add BDFZГ dummy BDFZГ
scoreboard objectives add BDFZГГГ dummy BDFZГГГ
scoreboard objectives add BDFZMГ dummy BDFZMГ
scoreboard objectives add BDFZЗ dummy BDFZЗ
scoreboard objectives add BDFZГЗ dummy BDFZГЗ
scoreboard objectives add BDFZГГГЗ dummy BDFZГГГЗ
scoreboard objectives add BDFZЖ dummy BDFZЖ
scoreboard objectives add BDEN dummy BDEN
scoreboard objectives add BDENГ dummy BDENГ
scoreboard objectives add BDENГГГ dummy BDENГГГ
scoreboard objectives add BDFNГ dummy BDFNГ
scoreboard objectives add BDFNГГГ dummy BDFNГГГ
scoreboard objectives add BDHXZTUГЖЗ dummy BDHXZTUГЖЗ
scoreboard objectives add BDFXMД dummy BDFXMД
scoreboard objectives add BDFXMГ dummy BDFXMГ
scoreboard objectives add BDFXMГГ dummy BDFXMГГ
scoreboard objectives add BDFXMГГГ dummy BDFXMГГГ
scoreboard objectives add BDIR dummy BDIR
scoreboard objectives add BDJM dummy BDJM
scoreboard objectives add BDJMГ dummy BDJMГ
scoreboard objectives add BDJ dummy BDJ
scoreboard objectives add BDJZ dummy BDJZ
scoreboard objectives add BDGЗ dummy BDGЗ
scoreboard objectives add BDG dummy BDG
scoreboard objectives add BDGД dummy BDGД
scoreboard objectives add BDGДЗ dummy BDGДЗ
scoreboard objectives add BDFXP dummy BDFXP
scoreboard objectives add BDFXPГ dummy BDFXPГ
scoreboard objectives add BDFXPГГГ dummy BDFXPГГГ
scoreboard objectives add BDI2 dummy BDI2
scoreboard objectives add BDI2K dummy BDI2K
scoreboard objectives add BDI2M dummy BDI2M
scoreboard objectives add BDI2MK dummy BDI2MK
scoreboard objectives add BDIU dummy BDIU
scoreboard objectives add BDIUЖ dummy BDIUЖ
scoreboard objectives add BDIUГГГ dummy BDIUГГГ
scoreboard objectives add BDIUГГГЖ dummy BDIUГГГЖ

scoreboard objectives add CAEK dummy CAEK
scoreboard objectives add CAEKЗ dummy CAEKЗ
scoreboard objectives add CAEKЖ dummy CAEKЖ
scoreboard objectives add CAEKЗЖ dummy CAEKЗЖ
scoreboard objectives add CAEKЖЗ dummy CAEKЖЗ
scoreboard objectives add CAEKГ dummy CAEKГ
scoreboard objectives add CAEKГЗ dummy CAEKГЗ
scoreboard objectives add CAEKГГГ dummy CAEKГГГ
scoreboard objectives add CAEKД dummy CAEKД
scoreboard objectives add CAEKДГ dummy CAEKДГ
scoreboard objectives add CAEKSГГГ dummy CAEKSГГГ
scoreboard objectives add CAEL dummy CAEL
scoreboard objectives add CAELГ dummy CAELГ
scoreboard objectives add CAEWM dummy CAEWM
scoreboard objectives add CAEWMГ dummy CAEWMГ
scoreboard objectives add CAEWMГГГ dummy CAEWMГГГ
scoreboard objectives add CAEW dummy CAEW
scoreboard objectives add CAEWГ dummy CAEWГ
scoreboard objectives add CAEWЗ dummy CAEWЗ
scoreboard objectives add CAFW dummy CAFW
scoreboard objectives add CAFWГ dummy CAFWГ
scoreboard objectives add CAGЗ dummy CAGЗ
scoreboard objectives add CAG dummy CAG
scoreboard objectives add CAJ dummy CAJ
scoreboard objectives add CAE1 dummy CAE1
scoreboard objectives add CAE1Г dummy CAE1Г
scoreboard objectives add CAE2 dummy CAE2
scoreboard objectives add CAE2Г dummy CAE2Г
scoreboard objectives add CBFV dummy CBFV
scoreboard objectives add CBFVГ dummy CBFVГ
scoreboard objectives add CBEV dummy CBEV
scoreboard objectives add CBEVГ dummy CBEVГ
scoreboard objectives add CBGЗ dummy CBGЗ
scoreboard objectives add CBG dummy CBG
scoreboard objectives add CBFQ dummy CBFQ
scoreboard objectives add CBFQЗ dummy CBFQЗ
scoreboard objectives add CBFQЖ dummy CBFQЖ
scoreboard objectives add CBFQГ dummy CBFQГ
scoreboard objectives add CBFQГЗ dummy CBFQГЗ
scoreboard objectives add CBFQГЖ dummy CBFQГЖ
scoreboard objectives add CBFQГГ dummy CBFQГГ
scoreboard objectives add CBFQГГГ dummy CBFQГГГ
scoreboard objectives add CBFБ dummy CBFБ
scoreboard objectives add CBFБГ dummy CBFБГ
scoreboard objectives add CBFБГГГ dummy CBFБГГГ
scoreboard objectives add CBFБZ dummy CBFБZ
scoreboard objectives add CBFБZГ dummy CBFБZГ
scoreboard objectives add CBFБZГГГ dummy CBFБZГГГ
scoreboard objectives add CBJ dummy CBJ
scoreboard objectives add CCFP dummy CCFP
scoreboard objectives add CCFPГ dummy CCFPГ
scoreboard objectives add CCFPГГ dummy CCFPГГ
scoreboard objectives add CCFPГГГ dummy CCFPГГГ
scoreboard objectives add CCFPM dummy CCFPM
scoreboard objectives add CCFPMГ dummy CCFPMГ
scoreboard objectives add CCFPMГГГ dummy CCFPMГГГ
scoreboard objectives add CCFPMЗ dummy CCFPMЗ
scoreboard objectives add CCFPMГЗ dummy CCFPMГЗ
scoreboard objectives add CCFPMГГГЗ dummy CCFPMГГГЗ
scoreboard objectives add CCFPW dummy CCFPW
scoreboard objectives add CCFPWЗ dummy CCFPWЗ
scoreboard objectives add CCFT dummy CCFT
scoreboard objectives add CCFTЖ dummy CCFTЖ
scoreboard objectives add CCFTЗ dummy CCFTЗ
scoreboard objectives add CCFQ dummy CCFQ
scoreboard objectives add CCFQЖ dummy CCFQЖ
scoreboard objectives add CCFQЗ dummy CCFQЗ
scoreboard objectives add CCFQГ dummy CCFQГ
scoreboard objectives add CCFQГЗ dummy CCFQГЗ
scoreboard objectives add CCFZ dummy CCFZ
scoreboard objectives add CCFZЖ dummy CCFZЖ
scoreboard objectives add CCFZЗ dummy CCFZЗ
scoreboard objectives add CCFO dummy CCFO
scoreboard objectives add CCFOЗ dummy CCFOЗ
scoreboard objectives add CCFOЖ dummy CCFOЖ
scoreboard objectives add CCFOГ dummy CCFOГ
scoreboard objectives add CCFOГЗ dummy CCFOГЗ
scoreboard objectives add CCFOГЖ dummy CCFOГЖ
scoreboard objectives add CCFOГГГ dummy CCFOГГГ
scoreboard objectives add CCFOГГГЗ dummy CCFOГГГЗ
scoreboard objectives add CCFOГГГЖ dummy CCFOГГГЖ
scoreboard objectives add CCFOQГГГ dummy CCFOQГГГ
scoreboard objectives add CCFOQГГГЗ dummy CCFOQГГГЗ
scoreboard objectives add CCFS dummy CCFS
scoreboard objectives add CCJ dummy CCJ
scoreboard objectives add CCG dummy CCG
scoreboard objectives add CCGЗ dummy CCGЗ
scoreboard objectives add CCF2 dummy CCF2
scoreboard objectives add CCIU dummy CCIU
scoreboard objectives add CCIUГ dummy CCIUГ
scoreboard objectives add CCFPU dummy CCFPU
scoreboard objectives add CCFPUЖ dummy CCFPUЖ
scoreboard objectives add CCFPUГГГЖ dummy CCFPUГГГЖ
scoreboard objectives add CDITX dummy CDITX
scoreboard objectives add CDGZЗ dummy CDGZЗ
scoreboard objectives add CDFM dummy CDFM
scoreboard objectives add CDFMP dummy CDFMP
scoreboard objectives add CDFPZЖ dummy CDFPZЖ
scoreboard objectives add CDFY dummy CDFY
scoreboard objectives add CDFYГ dummy CDFYГ
scoreboard objectives add CDFYГГГ dummy CDFYГГГ
scoreboard objectives add CDEY dummy CDEY
scoreboard objectives add CDEYГ dummy CDEYГ
scoreboard objectives add CDEYГГГ dummy CDEYГГГ
scoreboard objectives add CDFБX dummy CDFБX
scoreboard objectives add CDFБXK dummy CDFБXK
scoreboard objectives add CDFXY dummy CDFXY
scoreboard objectives add CDFXYГ dummy CDFXYГ
scoreboard objectives add CDFXYГГГ dummy CDFXYГГГ
scoreboard objectives add CDFБ dummy CDFБ
scoreboard objectives add CDFБS dummy CDFБS
scoreboard objectives add CDFБM dummy CDFБM
scoreboard objectives add CDFT dummy CDFT
scoreboard objectives add CDET dummy CDET
scoreboard objectives add CDETГ dummy CDETГ
scoreboard objectives add CDETЗ dummy CDETЗ
scoreboard objectives add CDETГЗ dummy CDETГЗ
scoreboard objectives add CDEZ dummy CDEZ
scoreboard objectives add CDEZГ dummy CDEZГ
scoreboard objectives add CDEZГГГ dummy CDEZГГГ
scoreboard objectives add CDEZЗ dummy CDEZЗ
scoreboard objectives add CDEZГЗ dummy CDEZГЗ
scoreboard objectives add CDEZM dummy CDEZM
scoreboard objectives add CDEZMГ dummy CDEZMГ
scoreboard objectives add CDEZMГГГ dummy CDEZMГГГ
scoreboard objectives add CDEZMЗ dummy CDEZMЗ
scoreboard objectives add CDEZMГЗ dummy CDEZMГЗ
scoreboard objectives add CDFZ dummy CDFZ
scoreboard objectives add CDFZГ dummy CDFZГ
scoreboard objectives add CDFZГГГ dummy CDFZГГГ
scoreboard objectives add CDFZMГ dummy CDFZMГ
scoreboard objectives add CDFZЗ dummy CDFZЗ
scoreboard objectives add CDFZГЗ dummy CDFZГЗ
scoreboard objectives add CDFZГГГЗ dummy CDFZГГГЗ
scoreboard objectives add CDFZЖ dummy CDFZЖ
scoreboard objectives add CDEN dummy CDEN
scoreboard objectives add CDENГ dummy CDENГ
scoreboard objectives add CDENГГГ dummy CDENГГГ
scoreboard objectives add CDFNГ dummy CDFNГ
scoreboard objectives add CDFNГГГ dummy CDFNГГГ
scoreboard objectives add CDHXZTUГЖЗ dummy CDHXZTUГЖЗ
scoreboard objectives add CDFXMД dummy CDFXMД
scoreboard objectives add CDFXMГ dummy CDFXMГ
scoreboard objectives add CDFXMГГ dummy CDFXMГГ
scoreboard objectives add CDFXMГГГ dummy CDFXMГГГ
scoreboard objectives add CDIR dummy CDIR
scoreboard objectives add CDJM dummy CDJM
scoreboard objectives add CDJMГ dummy CDJMГ
scoreboard objectives add CDJ dummy CDJ
scoreboard objectives add CDJZ dummy CDJZ
scoreboard objectives add CDGЗ dummy CDGЗ
scoreboard objectives add CDG dummy CDG
scoreboard objectives add CDGД dummy CDGД
scoreboard objectives add CDGДЗ dummy CDGДЗ
scoreboard objectives add CDFXP dummy CDFXP
scoreboard objectives add CDFXPГ dummy CDFXPГ
scoreboard objectives add CDFXPГГГ dummy CDFXPГГГ
scoreboard objectives add CDI2 dummy CDI2
scoreboard objectives add CDI2K dummy CDI2K
scoreboard objectives add CDI2M dummy CDI2M
scoreboard objectives add CDI2MK dummy CDI2MK
scoreboard objectives add CDIU dummy CDIU
scoreboard objectives add CDIUЖ dummy CDIUЖ
scoreboard objectives add CDIUГГГ dummy CDIUГГГ
scoreboard objectives add CDIUГГГЖ dummy CDIUГГГЖ

scoreboard objectives add DAEK dummy DAEK
scoreboard objectives add DAEKЗ dummy DAEKЗ
scoreboard objectives add DAEKЖ dummy DAEKЖ
scoreboard objectives add DAEKЗЖ dummy DAEKЗЖ
scoreboard objectives add DAEKЖЗ dummy DAEKЖЗ
scoreboard objectives add DAEKГ dummy DAEKГ
scoreboard objectives add DAEKГЗ dummy DAEKГЗ
scoreboard objectives add DAEKГГГ dummy DAEKГГГ
scoreboard objectives add DAEKД dummy DAEKД
scoreboard objectives add DAEKДГ dummy DAEKДГ
scoreboard objectives add DAEKSГГГ dummy DAEKSГГГ
scoreboard objectives add DAEL dummy DAEL
scoreboard objectives add DAELГ dummy DAELГ
scoreboard objectives add DAEWM dummy DAEWM
scoreboard objectives add DAEWMГ dummy DAEWMГ
scoreboard objectives add DAEWMГГГ dummy DAEWMГГГ
scoreboard objectives add DAEW dummy DAEW
scoreboard objectives add DAEWГ dummy DAEWГ
scoreboard objectives add DAEWЗ dummy DAEWЗ
scoreboard objectives add DAFW dummy DAFW
scoreboard objectives add DAFWГ dummy DAFWГ
scoreboard objectives add DAGЗ dummy DAGЗ
scoreboard objectives add DAG dummy DAG
scoreboard objectives add DAJ dummy DAJ
scoreboard objectives add DAE1 dummy DAE1
scoreboard objectives add DAE1Г dummy DAE1Г
scoreboard objectives add DAE2 dummy DAE2
scoreboard objectives add DAE2Г dummy DAE2Г
scoreboard objectives add DBFV dummy DBFV
scoreboard objectives add DBFVГ dummy DBFVГ
scoreboard objectives add DBEV dummy DBEV
scoreboard objectives add DBEVГ dummy DBEVГ
scoreboard objectives add DBGЗ dummy DBGЗ
scoreboard objectives add DBG dummy DBG
scoreboard objectives add DBFQ dummy DBFQ
scoreboard objectives add DBFQЗ dummy DBFQЗ
scoreboard objectives add DBFQЖ dummy DBFQЖ
scoreboard objectives add DBFQГ dummy DBFQГ
scoreboard objectives add DBFQГЗ dummy DBFQГЗ
scoreboard objectives add DBFQГЖ dummy DBFQГЖ
scoreboard objectives add DBFQГГ dummy DBFQГГ
scoreboard objectives add DBFQГГГ dummy DBFQГГГ
scoreboard objectives add DBFБ dummy DBFБ
scoreboard objectives add DBFБГ dummy DBFБГ
scoreboard objectives add DBFБГГГ dummy DBFБГГГ
scoreboard objectives add DBFБZ dummy DBFБZ
scoreboard objectives add DBFБZГ dummy DBFБZГ
scoreboard objectives add DBFБZГГГ dummy DBFБZГГГ
scoreboard objectives add DBJ dummy DBJ
scoreboard objectives add DCFP dummy DCFP
scoreboard objectives add DCFPГ dummy DCFPГ
scoreboard objectives add DCFPГГ dummy DCFPГГ
scoreboard objectives add DCFPГГГ dummy DCFPГГГ
scoreboard objectives add DCFPM dummy DCFPM
scoreboard objectives add DCFPMГ dummy DCFPMГ
scoreboard objectives add DCFPMГГГ dummy DCFPMГГГ
scoreboard objectives add DCFPMЗ dummy DCFPMЗ
scoreboard objectives add DCFPMГЗ dummy DCFPMГЗ
scoreboard objectives add DCFPMГГГЗ dummy DCFPMГГГЗ
scoreboard objectives add DCFPW dummy DCFPW
scoreboard objectives add DCFPWЗ dummy DCFPWЗ
scoreboard objectives add DCFT dummy DCFT
scoreboard objectives add DCFTЖ dummy DCFTЖ
scoreboard objectives add DCFTЗ dummy DCFTЗ
scoreboard objectives add DCFQ dummy DCFQ
scoreboard objectives add DCFQЖ dummy DCFQЖ
scoreboard objectives add DCFQЗ dummy DCFQЗ
scoreboard objectives add DCFQГ dummy DCFQГ
scoreboard objectives add DCFQГЗ dummy DCFQГЗ
scoreboard objectives add DCFZ dummy DCFZ
scoreboard objectives add DCFZЖ dummy DCFZЖ
scoreboard objectives add DCFZЗ dummy DCFZЗ
scoreboard objectives add DCFO dummy DCFO
scoreboard objectives add DCFOЗ dummy DCFOЗ
scoreboard objectives add DCFOЖ dummy DCFOЖ
scoreboard objectives add DCFOГ dummy DCFOГ
scoreboard objectives add DCFOГЗ dummy DCFOГЗ
scoreboard objectives add DCFOГЖ dummy DCFOГЖ
scoreboard objectives add DCFOГГГ dummy DCFOГГГ
scoreboard objectives add DCFOГГГЗ dummy DCFOГГГЗ
scoreboard objectives add DCFOГГГЖ dummy DCFOГГГЖ
scoreboard objectives add DCFOQГГГ dummy DCFOQГГГ
scoreboard objectives add DCFOQГГГЗ dummy DCFOQГГГЗ
scoreboard objectives add DCFS dummy DCFS
scoreboard objectives add DCJ dummy DCJ
scoreboard objectives add DCG dummy DCG
scoreboard objectives add DCGЗ dummy DCGЗ
scoreboard objectives add DCF2 dummy DCF2
scoreboard objectives add DCIU dummy DCIU
scoreboard objectives add DCIUГ dummy DCIUГ
scoreboard objectives add DCFPU dummy DCFPU
scoreboard objectives add DCFPUЖ dummy DCFPUЖ
scoreboard objectives add DCFPUГГГЖ dummy DCFPUГГГЖ
scoreboard objectives add DDITX dummy DDITX
scoreboard objectives add DDGZЗ dummy DDGZЗ
scoreboard objectives add DDFM dummy DDFM
scoreboard objectives add DDFMP dummy DDFMP
scoreboard objectives add DDFPZЖ dummy DDFPZЖ
scoreboard objectives add DDFY dummy DDFY
scoreboard objectives add DDFYГ dummy DDFYГ
scoreboard objectives add DDFYГГГ dummy DDFYГГГ
scoreboard objectives add DDEY dummy DDEY
scoreboard objectives add DDEYГ dummy DDEYГ
scoreboard objectives add DDEYГГГ dummy DDEYГГГ
scoreboard objectives add DDFБX dummy DDFБX
scoreboard objectives add DDFБXK dummy DDFБXK
scoreboard objectives add DDFXY dummy DDFXY
scoreboard objectives add DDFXYГ dummy DDFXYГ
scoreboard objectives add DDFXYГГГ dummy DDFXYГГГ
scoreboard objectives add DDFБ dummy DDFБ
scoreboard objectives add DDFБS dummy DDFБS
scoreboard objectives add DDFБM dummy DDFБM
scoreboard objectives add DDFT dummy DDFT
scoreboard objectives add DDET dummy DDET
scoreboard objectives add DDETГ dummy DDETГ
scoreboard objectives add DDETЗ dummy DDETЗ
scoreboard objectives add DDETГЗ dummy DDETГЗ
scoreboard objectives add DDEZ dummy DDEZ
scoreboard objectives add DDEZГ dummy DDEZГ
scoreboard objectives add DDEZГГГ dummy DDEZГГГ
scoreboard objectives add DDEZЗ dummy DDEZЗ
scoreboard objectives add DDEZГЗ dummy DDEZГЗ
scoreboard objectives add DDEZM dummy DDEZM
scoreboard objectives add DDEZMГ dummy DDEZMГ
scoreboard objectives add DDEZMГГГ dummy DDEZMГГГ
scoreboard objectives add DDEZMЗ dummy DDEZMЗ
scoreboard objectives add DDEZMГЗ dummy DDEZMГЗ
scoreboard objectives add DDFZ dummy DDFZ
scoreboard objectives add DDFZГ dummy DDFZГ
scoreboard objectives add DDFZГГГ dummy DDFZГГГ
scoreboard objectives add DDFZMГ dummy DDFZMГ
scoreboard objectives add DDFZЗ dummy DDFZЗ
scoreboard objectives add DDFZГЗ dummy DDFZГЗ
scoreboard objectives add DDFZГГГЗ dummy DDFZГГГЗ
scoreboard objectives add DDFZЖ dummy DDFZЖ
scoreboard objectives add DDEN dummy DDEN
scoreboard objectives add DDENГ dummy DDENГ
scoreboard objectives add DDENГГГ dummy DDENГГГ
scoreboard objectives add DDFNГ dummy DDFNГ
scoreboard objectives add DDFNГГГ dummy DDFNГГГ
scoreboard objectives add DDHXZTUГЖЗ dummy DDHXZTUГЖЗ
scoreboard objectives add DDFXMД dummy DDFXMД
scoreboard objectives add DDFXMГ dummy DDFXMГ
scoreboard objectives add DDFXMГГ dummy DDFXMГГ
scoreboard objectives add DDFXMГГГ dummy DDFXMГГГ
scoreboard objectives add DDIR dummy DDIR
scoreboard objectives add DDJM dummy DDJM
scoreboard objectives add DDJMГ dummy DDJMГ
scoreboard objectives add DDJ dummy DDJ
scoreboard objectives add DDJZ dummy DDJZ
scoreboard objectives add DDGЗ dummy DDGЗ
scoreboard objectives add DDG dummy DDG
scoreboard objectives add DDGД dummy DDGД
scoreboard objectives add DDGДЗ dummy DDGДЗ
scoreboard objectives add DDFXP dummy DDFXP
scoreboard objectives add DDFXPГ dummy DDFXPГ
scoreboard objectives add DDFXPГГГ dummy DDFXPГГГ
scoreboard objectives add DDI2 dummy DDI2
scoreboard objectives add DDI2K dummy DDI2K
scoreboard objectives add DDI2M dummy DDI2M
scoreboard objectives add DDI2MK dummy DDI2MK
scoreboard objectives add DDIU dummy DDIU
scoreboard objectives add DDIUЖ dummy DDIUЖ
scoreboard objectives add DDIUГГГ dummy DDIUГГГ
scoreboard objectives add DDIUГГГЖ dummy DDIUГГГЖ

scoreboard objectives add EAEK dummy EAEK
scoreboard objectives add EAEKЗ dummy EAEKЗ
scoreboard objectives add EAEKЖ dummy EAEKЖ
scoreboard objectives add EAEKЗЖ dummy EAEKЗЖ
scoreboard objectives add EAEKЖЗ dummy EAEKЖЗ
scoreboard objectives add EAEKГ dummy EAEKГ
scoreboard objectives add EAEKГЗ dummy EAEKГЗ
scoreboard objectives add EAEKГГГ dummy EAEKГГГ
scoreboard objectives add EAEKД dummy EAEKД
scoreboard objectives add EAEKДГ dummy EAEKДГ
scoreboard objectives add EAEKSГГГ dummy EAEKSГГГ
scoreboard objectives add EAEL dummy EAEL
scoreboard objectives add EAELГ dummy EAELГ
scoreboard objectives add EAEWM dummy EAEWM
scoreboard objectives add EAEWMГ dummy EAEWMГ
scoreboard objectives add EAEWMГГГ dummy EAEWMГГГ
scoreboard objectives add EAEW dummy EAEW
scoreboard objectives add EAEWГ dummy EAEWГ
scoreboard objectives add EAEWЗ dummy EAEWЗ
scoreboard objectives add EAFW dummy EAFW
scoreboard objectives add EAFWГ dummy EAFWГ
scoreboard objectives add EAGЗ dummy EAGЗ
scoreboard objectives add EAG dummy EAG
scoreboard objectives add EAJ dummy EAJ
scoreboard objectives add EAE1 dummy EAE1
scoreboard objectives add EAE1Г dummy EAE1Г
scoreboard objectives add EAE2 dummy EAE2
scoreboard objectives add EAE2Г dummy EAE2Г
scoreboard objectives add EBFV dummy EBFV
scoreboard objectives add EBFVГ dummy EBFVГ
scoreboard objectives add EBEV dummy EBEV
scoreboard objectives add EBEVГ dummy EBEVГ
scoreboard objectives add EBGЗ dummy EBGЗ
scoreboard objectives add EBG dummy EBG
scoreboard objectives add EBFQ dummy EBFQ
scoreboard objectives add EBFQЗ dummy EBFQЗ
scoreboard objectives add EBFQЖ dummy EBFQЖ
scoreboard objectives add EBFQГ dummy EBFQГ
scoreboard objectives add EBFQГЗ dummy EBFQГЗ
scoreboard objectives add EBFQГЖ dummy EBFQГЖ
scoreboard objectives add EBFQГГ dummy EBFQГГ
scoreboard objectives add EBFQГГГ dummy EBFQГГГ
scoreboard objectives add EBFБ dummy EBFБ
scoreboard objectives add EBFБГ dummy EBFБГ
scoreboard objectives add EBFБГГГ dummy EBFБГГГ
scoreboard objectives add EBFБZ dummy EBFБZ
scoreboard objectives add EBFБZГ dummy EBFБZГ
scoreboard objectives add EBFБZГГГ dummy EBFБZГГГ
scoreboard objectives add EBJ dummy EBJ
scoreboard objectives add ECFP dummy ECFP
scoreboard objectives add ECFPГ dummy ECFPГ
scoreboard objectives add ECFPГГ dummy ECFPГГ
scoreboard objectives add ECFPГГГ dummy ECFPГГГ
scoreboard objectives add ECFPM dummy ECFPM
scoreboard objectives add ECFPMГ dummy ECFPMГ
scoreboard objectives add ECFPMГГГ dummy ECFPMГГГ
scoreboard objectives add ECFPMЗ dummy ECFPMЗ
scoreboard objectives add ECFPMГЗ dummy ECFPMГЗ
scoreboard objectives add ECFPMГГГЗ dummy ECFPMГГГЗ
scoreboard objectives add ECFPW dummy ECFPW
scoreboard objectives add ECFPWЗ dummy ECFPWЗ
scoreboard objectives add ECFT dummy ECFT
scoreboard objectives add ECFTЖ dummy ECFTЖ
scoreboard objectives add ECFTЗ dummy ECFTЗ
scoreboard objectives add ECFQ dummy ECFQ
scoreboard objectives add ECFQЖ dummy ECFQЖ
scoreboard objectives add ECFQЗ dummy ECFQЗ
scoreboard objectives add ECFQГ dummy ECFQГ
scoreboard objectives add ECFQГЗ dummy ECFQГЗ
scoreboard objectives add ECFZ dummy ECFZ
scoreboard objectives add ECFZЖ dummy ECFZЖ
scoreboard objectives add ECFZЗ dummy ECFZЗ
scoreboard objectives add ECFO dummy ECFO
scoreboard objectives add ECFOЗ dummy ECFOЗ
scoreboard objectives add ECFOЖ dummy ECFOЖ
scoreboard objectives add ECFOГ dummy ECFOГ
scoreboard objectives add ECFOГЗ dummy ECFOГЗ
scoreboard objectives add ECFOГЖ dummy ECFOГЖ
scoreboard objectives add ECFOГГГ dummy ECFOГГГ
scoreboard objectives add ECFOГГГЗ dummy ECFOГГГЗ
scoreboard objectives add ECFOГГГЖ dummy ECFOГГГЖ
scoreboard objectives add ECFOQГГГ dummy ECFOQГГГ
scoreboard objectives add ECFOQГГГЗ dummy ECFOQГГГЗ
scoreboard objectives add ECFS dummy ECFS
scoreboard objectives add ECJ dummy ECJ
scoreboard objectives add ECG dummy ECG
scoreboard objectives add ECGЗ dummy ECGЗ
scoreboard objectives add ECF2 dummy ECF2
scoreboard objectives add ECIU dummy ECIU
scoreboard objectives add ECIUГ dummy ECIUГ
scoreboard objectives add ECFPU dummy ECFPU
scoreboard objectives add ECFPUЖ dummy ECFPUЖ
scoreboard objectives add ECFPUГГГЖ dummy ECFPUГГГЖ
scoreboard objectives add EDITX dummy EDITX
scoreboard objectives add EDGZЗ dummy EDGZЗ
scoreboard objectives add EDFM dummy EDFM
scoreboard objectives add EDFMP dummy EDFMP
scoreboard objectives add EDFPZЖ dummy EDFPZЖ
scoreboard objectives add EDFY dummy EDFY
scoreboard objectives add EDFYГ dummy EDFYГ
scoreboard objectives add EDFYГГГ dummy EDFYГГГ
scoreboard objectives add EDEY dummy EDEY
scoreboard objectives add EDEYГ dummy EDEYГ
scoreboard objectives add EDEYГГГ dummy EDEYГГГ
scoreboard objectives add EDFБX dummy EDFБX
scoreboard objectives add EDFБXK dummy EDFБXK
scoreboard objectives add EDFXY dummy EDFXY
scoreboard objectives add EDFXYГ dummy EDFXYГ
scoreboard objectives add EDFXYГГГ dummy EDFXYГГГ
scoreboard objectives add EDFБ dummy EDFБ
scoreboard objectives add EDFБS dummy EDFБS
scoreboard objectives add EDFБM dummy EDFБM
scoreboard objectives add EDFT dummy EDFT
scoreboard objectives add EDET dummy EDET
scoreboard objectives add EDETГ dummy EDETГ
scoreboard objectives add EDETЗ dummy EDETЗ
scoreboard objectives add EDETГЗ dummy EDETГЗ
scoreboard objectives add EDEZ dummy EDEZ
scoreboard objectives add EDEZГ dummy EDEZГ
scoreboard objectives add EDEZГГГ dummy EDEZГГГ
scoreboard objectives add EDEZЗ dummy EDEZЗ
scoreboard objectives add EDEZГЗ dummy EDEZГЗ
scoreboard objectives add EDEZM dummy EDEZM
scoreboard objectives add EDEZMГ dummy EDEZMГ
scoreboard objectives add EDEZMГГГ dummy EDEZMГГГ
scoreboard objectives add EDEZMЗ dummy EDEZMЗ
scoreboard objectives add EDEZMГЗ dummy EDEZMГЗ
scoreboard objectives add EDFZ dummy EDFZ
scoreboard objectives add EDFZГ dummy EDFZГ
scoreboard objectives add EDFZГГГ dummy EDFZГГГ
scoreboard objectives add EDFZMГ dummy EDFZMГ
scoreboard objectives add EDFZЗ dummy EDFZЗ
scoreboard objectives add EDFZГЗ dummy EDFZГЗ
scoreboard objectives add EDFZГГГЗ dummy EDFZГГГЗ
scoreboard objectives add EDFZЖ dummy EDFZЖ
scoreboard objectives add EDEN dummy EDEN
scoreboard objectives add EDENГ dummy EDENГ
scoreboard objectives add EDENГГГ dummy EDENГГГ
scoreboard objectives add EDFNГ dummy EDFNГ
scoreboard objectives add EDFNГГГ dummy EDFNГГГ
scoreboard objectives add EDHXZTUГЖЗ dummy EDHXZTUГЖЗ
scoreboard objectives add EDFXMД dummy EDFXMД
scoreboard objectives add EDFXMГ dummy EDFXMГ
scoreboard objectives add EDFXMГГ dummy EDFXMГГ
scoreboard objectives add EDFXMГГГ dummy EDFXMГГГ
scoreboard objectives add EDIR dummy EDIR
scoreboard objectives add EDJM dummy EDJM
scoreboard objectives add EDJMГ dummy EDJMГ
scoreboard objectives add EDJ dummy EDJ
scoreboard objectives add EDJZ dummy EDJZ
scoreboard objectives add EDGЗ dummy EDGЗ
scoreboard objectives add EDG dummy EDG
scoreboard objectives add EDGД dummy EDGД
scoreboard objectives add EDGДЗ dummy EDGДЗ
scoreboard objectives add EDFXP dummy EDFXP
scoreboard objectives add EDFXPГ dummy EDFXPГ
scoreboard objectives add EDFXPГГГ dummy EDFXPГГГ
scoreboard objectives add EDI2 dummy EDI2
scoreboard objectives add EDI2K dummy EDI2K
scoreboard objectives add EDI2M dummy EDI2M
scoreboard objectives add EDI2MK dummy EDI2MK
scoreboard objectives add EDIU dummy EDIU
scoreboard objectives add EDIUЖ dummy EDIUЖ
scoreboard objectives add EDIUГГГ dummy EDIUГГГ
scoreboard objectives add EDIUГГГЖ dummy EDIUГГГЖ

scoreboard objectives add FAEK dummy FAEK
scoreboard objectives add FAEKЗ dummy FAEKЗ
scoreboard objectives add FAEKЖ dummy FAEKЖ
scoreboard objectives add FAEKЗЖ dummy FAEKЗЖ
scoreboard objectives add FAEKЖЗ dummy FAEKЖЗ
scoreboard objectives add FAEKГ dummy FAEKГ
scoreboard objectives add FAEKГЗ dummy FAEKГЗ
scoreboard objectives add FAEKГГГ dummy FAEKГГГ
scoreboard objectives add FAEKД dummy FAEKД
scoreboard objectives add FAEKДГ dummy FAEKДГ
scoreboard objectives add FAEKSГГГ dummy FAEKSГГГ
scoreboard objectives add FAEL dummy FAEL
scoreboard objectives add FAELГ dummy FAELГ
scoreboard objectives add FAEWM dummy FAEWM
scoreboard objectives add FAEWMГ dummy FAEWMГ
scoreboard objectives add FAEWMГГГ dummy FAEWMГГГ
scoreboard objectives add FAEW dummy FAEW
scoreboard objectives add FAEWГ dummy FAEWГ
scoreboard objectives add FAEWЗ dummy FAEWЗ
scoreboard objectives add FAFW dummy FAFW
scoreboard objectives add FAFWГ dummy FAFWГ
scoreboard objectives add FAGЗ dummy FAGЗ
scoreboard objectives add FAG dummy FAG
scoreboard objectives add FAJ dummy FAJ
scoreboard objectives add FAE1 dummy FAE1
scoreboard objectives add FAE1Г dummy FAE1Г
scoreboard objectives add FAE2 dummy FAE2
scoreboard objectives add FAE2Г dummy FAE2Г
scoreboard objectives add FBFV dummy FBFV
scoreboard objectives add FBFVГ dummy FBFVГ
scoreboard objectives add FBEV dummy FBEV
scoreboard objectives add FBEVГ dummy FBEVГ
scoreboard objectives add FBGЗ dummy FBGЗ
scoreboard objectives add FBG dummy FBG
scoreboard objectives add FBFQ dummy FBFQ
scoreboard objectives add FBFQЗ dummy FBFQЗ
scoreboard objectives add FBFQЖ dummy FBFQЖ
scoreboard objectives add FBFQГ dummy FBFQГ
scoreboard objectives add FBFQГЗ dummy FBFQГЗ
scoreboard objectives add FBFQГЖ dummy FBFQГЖ
scoreboard objectives add FBFQГГ dummy FBFQГГ
scoreboard objectives add FBFQГГГ dummy FBFQГГГ
scoreboard objectives add FBFБ dummy FBFБ
scoreboard objectives add FBFБГ dummy FBFБГ
scoreboard objectives add FBFБГГГ dummy FBFБГГГ
scoreboard objectives add FBFБZ dummy FBFБZ
scoreboard objectives add FBFБZГ dummy FBFБZГ
scoreboard objectives add FBFБZГГГ dummy FBFБZГГГ
scoreboard objectives add FBJ dummy FBJ
scoreboard objectives add FCFP dummy FCFP
scoreboard objectives add FCFPГ dummy FCFPГ
scoreboard objectives add FCFPГГ dummy FCFPГГ
scoreboard objectives add FCFPГГГ dummy FCFPГГГ
scoreboard objectives add FCFPM dummy FCFPM
scoreboard objectives add FCFPMГ dummy FCFPMГ
scoreboard objectives add FCFPMГГГ dummy FCFPMГГГ
scoreboard objectives add FCFPMЗ dummy FCFPMЗ
scoreboard objectives add FCFPMГЗ dummy FCFPMГЗ
scoreboard objectives add FCFPMГГГЗ dummy FCFPMГГГЗ
scoreboard objectives add FCFPW dummy FCFPW
scoreboard objectives add FCFPWЗ dummy FCFPWЗ
scoreboard objectives add FCFT dummy FCFT
scoreboard objectives add FCFTЖ dummy FCFTЖ
scoreboard objectives add FCFTЗ dummy FCFTЗ
scoreboard objectives add FCFQ dummy FCFQ
scoreboard objectives add FCFQЖ dummy FCFQЖ
scoreboard objectives add FCFQЗ dummy FCFQЗ
scoreboard objectives add FCFQГ dummy FCFQГ
scoreboard objectives add FCFQГЗ dummy FCFQГЗ
scoreboard objectives add FCFZ dummy FCFZ
scoreboard objectives add FCFZЖ dummy FCFZЖ
scoreboard objectives add FCFZЗ dummy FCFZЗ
scoreboard objectives add FCFO dummy FCFO
scoreboard objectives add FCFOЗ dummy FCFOЗ
scoreboard objectives add FCFOЖ dummy FCFOЖ
scoreboard objectives add FCFOГ dummy FCFOГ
scoreboard objectives add FCFOГЗ dummy FCFOГЗ
scoreboard objectives add FCFOГЖ dummy FCFOГЖ
scoreboard objectives add FCFOГГГ dummy FCFOГГГ
scoreboard objectives add FCFOГГГЗ dummy FCFOГГГЗ
scoreboard objectives add FCFOГГГЖ dummy FCFOГГГЖ
scoreboard objectives add FCFOQГГГ dummy FCFOQГГГ
scoreboard objectives add FCFOQГГГЗ dummy FCFOQГГГЗ
scoreboard objectives add FCFS dummy FCFS
scoreboard objectives add FCJ dummy FCJ
scoreboard objectives add FCG dummy FCG
scoreboard objectives add FCGЗ dummy FCGЗ
scoreboard objectives add FCF2 dummy FCF2
scoreboard objectives add FCIU dummy FCIU
scoreboard objectives add FCIUГ dummy FCIUГ
scoreboard objectives add FCFPU dummy FCFPU
scoreboard objectives add FCFPUЖ dummy FCFPUЖ
scoreboard objectives add FCFPUГГГЖ dummy FCFPUГГГЖ
scoreboard objectives add FDITX dummy FDITX
scoreboard objectives add FDGZЗ dummy FDGZЗ
scoreboard objectives add FDFM dummy FDFM
scoreboard objectives add FDFMP dummy FDFMP
scoreboard objectives add FDFPZЖ dummy FDFPZЖ
scoreboard objectives add FDFY dummy FDFY
scoreboard objectives add FDFYГ dummy FDFYГ
scoreboard objectives add FDFYГГГ dummy FDFYГГГ
scoreboard objectives add FDEY dummy FDEY
scoreboard objectives add FDEYГ dummy FDEYГ
scoreboard objectives add FDEYГГГ dummy FDEYГГГ
scoreboard objectives add FDFБX dummy FDFБX
scoreboard objectives add FDFБXK dummy FDFБXK
scoreboard objectives add FDFXY dummy FDFXY
scoreboard objectives add FDFXYГ dummy FDFXYГ
scoreboard objectives add FDFXYГГГ dummy FDFXYГГГ
scoreboard objectives add FDFБ dummy FDFБ
scoreboard objectives add FDFБS dummy FDFБS
scoreboard objectives add FDFБM dummy FDFБM
scoreboard objectives add FDFT dummy FDFT
scoreboard objectives add FDET dummy FDET
scoreboard objectives add FDETГ dummy FDETГ
scoreboard objectives add FDETЗ dummy FDETЗ
scoreboard objectives add FDETГЗ dummy FDETГЗ
scoreboard objectives add FDEZ dummy FDEZ
scoreboard objectives add FDEZГ dummy FDEZГ
scoreboard objectives add FDEZГГГ dummy FDEZГГГ
scoreboard objectives add FDEZЗ dummy FDEZЗ
scoreboard objectives add FDEZГЗ dummy FDEZГЗ
scoreboard objectives add FDEZM dummy FDEZM
scoreboard objectives add FDEZMГ dummy FDEZMГ
scoreboard objectives add FDEZMГГГ dummy FDEZMГГГ
scoreboard objectives add FDEZMЗ dummy FDEZMЗ
scoreboard objectives add FDEZMГЗ dummy FDEZMГЗ
scoreboard objectives add FDFZ dummy FDFZ
scoreboard objectives add FDFZГ dummy FDFZГ
scoreboard objectives add FDFZГГГ dummy FDFZГГГ
scoreboard objectives add FDFZMГ dummy FDFZMГ
scoreboard objectives add FDFZЗ dummy FDFZЗ
scoreboard objectives add FDFZГЗ dummy FDFZГЗ
scoreboard objectives add FDFZГГГЗ dummy FDFZГГГЗ
scoreboard objectives add FDFZЖ dummy FDFZЖ
scoreboard objectives add FDEN dummy FDEN
scoreboard objectives add FDENГ dummy FDENГ
scoreboard objectives add FDENГГГ dummy FDENГГГ
scoreboard objectives add FDFNГ dummy FDFNГ
scoreboard objectives add FDFNГГГ dummy FDFNГГГ
scoreboard objectives add FDHXZTUГЖЗ dummy FDHXZTUГЖЗ
scoreboard objectives add FDFXMД dummy FDFXMД
scoreboard objectives add FDFXMГ dummy FDFXMГ
scoreboard objectives add FDFXMГГ dummy FDFXMГГ
scoreboard objectives add FDFXMГГГ dummy FDFXMГГГ
scoreboard objectives add FDIR dummy FDIR
scoreboard objectives add FDJM dummy FDJM
scoreboard objectives add FDJMГ dummy FDJMГ
scoreboard objectives add FDJ dummy FDJ
scoreboard objectives add FDJZ dummy FDJZ
scoreboard objectives add FDGЗ dummy FDGЗ
scoreboard objectives add FDG dummy FDG
scoreboard objectives add FDGД dummy FDGД
scoreboard objectives add FDGДЗ dummy FDGДЗ
scoreboard objectives add FDFXP dummy FDFXP
scoreboard objectives add FDFXPГ dummy FDFXPГ
scoreboard objectives add FDFXPГГГ dummy FDFXPГГГ
scoreboard objectives add FDI2 dummy FDI2
scoreboard objectives add FDI2K dummy FDI2K
scoreboard objectives add FDI2M dummy FDI2M
scoreboard objectives add FDI2MK dummy FDI2MK
scoreboard objectives add FDIU dummy FDIU
scoreboard objectives add FDIUЖ dummy FDIUЖ
scoreboard objectives add FDIUГГГ dummy FDIUГГГ
scoreboard objectives add FDIUГГГЖ dummy FDIUГГГЖ

