scoreboard players set @p sk_a_1 1
scoreboard players set @p sk_a_2 1
scoreboard players set @p sk_a_3 1
scoreboard players set @p sk_a_4 1
scoreboard players set @p sk_a_5 1
scoreboard players set @p sk_a_6 1
scoreboard players set @p sk_a_7 1
scoreboard players set @p sk_a_8 1
scoreboard players set @p sk_a_9 1
scoreboard players set @p sk_a_10 1
scoreboard players set @p sk_a_11 1
scoreboard players set @p sk_a_12 1
scoreboard players set @p sk_a_13 1
scoreboard players set @p sk_a_14 1
scoreboard players set @p sk_a_15 1
scoreboard players set @p sk_a_16 1
scoreboard players set @p sk_a_17 1
scoreboard players set @p sk_a_18 1
scoreboard players set @p sk_a_19 1
scoreboard players set @p sk_a_20 1
scoreboard players set @p sk_a_21 1
scoreboard players set @p sk_a_22 1
scoreboard players set @p sk_a_23 1
scoreboard players set @p sk_a_24 1
scoreboard players set @p sk_a_25 1
scoreboard players set @p sk_a_26 1
scoreboard players set @p sk_a_27 1
scoreboard players set @p sk_a_28 1
scoreboard players set @p sk_a_29 1

scoreboard players set @p sk_b_1 1
scoreboard players set @p sk_b_2 1
scoreboard players set @p sk_b_3 1
scoreboard players set @p sk_b_4 1
scoreboard players set @p sk_b_5 1
scoreboard players set @p sk_b_6 1
scoreboard players set @p sk_b_7 1
scoreboard players set @p sk_b_8 1
scoreboard players set @p sk_b_9 1
scoreboard players set @p sk_b_10 1
scoreboard players set @p sk_b_11 1
scoreboard players set @p sk_b_12 1
scoreboard players set @p sk_b_13 1
scoreboard players set @p sk_b_14 1

scoreboard players set @p sk_c_1 1
scoreboard players set @p sk_c_2 1
scoreboard players set @p sk_c_3 1
scoreboard players set @p sk_c_4 1
scoreboard players set @p sk_c_5 1
scoreboard players set @p sk_c_6 1
scoreboard players set @p sk_c_7 1
scoreboard players set @p sk_c_8 1
scoreboard players set @p sk_c_9 1
scoreboard players set @p sk_c_10 1
scoreboard players set @p sk_c_11 1
scoreboard players set @p sk_c_12 1
scoreboard players set @p sk_c_13 1
scoreboard players set @p sk_c_14 1
scoreboard players set @p sk_c_15 1

scoreboard players set @p sk_d_1 1
scoreboard players set @p sk_d_2 1
scoreboard players set @p sk_d_3 1
scoreboard players set @p sk_d_4 1