# Функция анимирования бездействия. Запускается от лицы и позиции каждого отдельного игрока

# Анализ недопустимых предметов. Если no_animate_killing_time то анимацию не допускаем.
    tag @s[hasitem={item=arx:costorub, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:moder_gun, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:costorub, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:delimiter, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:golden_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_dismantler, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_light_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:adona_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:blood_waiting, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:tearing_flesh, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bone_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:spear_with_gold_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_wide_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_wide_shortsword_with_special_guard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:golden_ossified_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:powered_steel_wide_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:golden_dagger_fang, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:hunting_cast_iron_knife, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_sharp_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:simple_iron_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dagger_fang, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:longed_cast_iron_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:notched_durasteel_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:simple_stone_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:fish_knife, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:podlik, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:chloronite_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_advanced_guard_dagger, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dagger_of_the_gap, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dagger_with_golden_blade, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:even, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_hammer_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:flesh_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:heavy_axe_with_chloronite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:petrified_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:rose_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_fang, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:altaite_small_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:copper_heavy_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_powered_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_wide_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:red_crystal_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_small_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_chorper, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_sword_with_bronze_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:altaite_battlehammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:ideal_altaite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_secyra_with_sapphiers, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_heavy_secyra, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:leave_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:stone_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:riolik_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_board, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:full_golden_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_ripper, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_small_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_great_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_small_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:stone_tomahawk, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:iron_default_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_very_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:naginitis_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:elder_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_and_toliriite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:naginits_and_forfacorite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_secyra, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:riolik_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_short_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_bonecrusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_netherite_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_ripper, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:toliriite_ripper, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:red_crystal_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:toliriite_cutter, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_crusher_with_cornelian, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:lamenite_megahammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_blade, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_and_caryite_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:clear_dorionite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_sword_with_draphorite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_megahammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_and_toliriite_wide_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_extreme_long_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:draphorite_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_dismantler_with_draphorite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_battleaxe_with_chloronite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_wide_greatsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wide_cross_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:harbinger_of_dawn, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_delimiter, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_sword_with_sapphire, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_and_gold_alloy_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_big_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:ravensword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_longsword_with_altaite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:clear_caryite_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:flesh_hell_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_long_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_greatsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:elder_battleboard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:tin_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:elder_white_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_extreme_heavy_crusher, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:chloronite_big_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_delimiter, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_alebard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_spear, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_spear, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_naginata, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_lance_with_draphorite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_and_aluminium_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:naginitis_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:simple_iron_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:sacrificial_iron_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_full_small_hammer, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:netherite_ripper, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_battleaxe_with_draphorite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_simple_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:copper_sword_hook, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:simple_iron_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_simple_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_simple_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_battleaxe_with_caryite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:dorionite_double_edged_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:aluminium_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:simple_iron_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:iron_wide_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_weighted_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:aluminium_curved_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:iron_wide_heavy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_longed_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_sword_with_copper_guard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_heighted_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_mace, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_longsword_with_copper_guard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:tin_curved_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_crossword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:bronze_trident, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_streight_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:tin_small_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_small_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_one_sided_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_sword_with_golden_guard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_heighted_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:naginitis_weighted_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:altaite_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_long_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_small_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:golden_trident, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:forfacorite_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:stone_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_lighted_small_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:duraluminium_great_battleaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_altaite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_netherite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_caryite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_tin, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_chloronite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_toliriite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_steel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_forfacorite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:scythe_naginitis, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:jagged_lance, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_alebard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:durasteel_sword_with_dorionite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_heavy_longsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_tooth, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_dark_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_simple_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_classic_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_sword_with_red_guard, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:powered_steel_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_dark_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:chloronite_shortsword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:caryite_heavysword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:cast_iron_tooth, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_sword_with_gold_inlay, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:holy_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:aluminium_simple_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_simple_blade, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:steel_cleaver, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:plumbum_saber, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:wooden_carved_sword, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:long_steel_sword_with_draphorite_inlays, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_san, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_caryite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_wooden, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_dragon, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_gold, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_netherite_with_ruby, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_dark_netherite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_golden_with_sapphire, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_chrysolite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_naginitis, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_cast_iron_with_chrysolite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_phoenix, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_with_ruby, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_with_skull, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_forest, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_twilight, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_golden_with_chrysolite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_simple_with_ruby, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_chloronite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_wooden_with_chrysolite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_dorionite_with_caryite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_with_diamond, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_wooden_with_riolik, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_tin_with_gold, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_dorionite, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_steel_with_topaz, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_kon, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_golden_with_violet_handle, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_battle, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_battle_custom_magik, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_hell, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_snowlands, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_din, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_sin, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_shaman, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_precious, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_angel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_golden_cross, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_fulminant, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:staff_of_heaven, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=arx:umbrella_golden_silk, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:umbrella_silk, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:umbrella_skin, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=arx:umbrella_small_silk, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=minecraft:torch, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:fishing_rod, location=slot.weapon.mainhand}] add no_animate_killing_time


    tag @s[hasitem={item=minecraft:wooden_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:stone_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:golden_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:iron_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:diamond_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:netherite_pickaxe, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=minecraft:wooden_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:stone_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:golden_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:iron_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:diamond_axe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:netherite_axe, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=minecraft:wooden_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:stone_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:golden_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:iron_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:diamond_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:netherite_hoe, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=minecraft:wooden_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:stone_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:golden_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:iron_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:diamond_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time
    tag @s[hasitem={item=minecraft:netherite_shovel, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[hasitem={item=arx:pose_tuning, location=slot.weapon.mainhand}] add no_animate_killing_time

    tag @s[has_property={arx:is_knocked=1..}] add no_animate_killing_time

# Нельзя анимировать если мы лежим/сидим
    tag @s[tag=is_riding] add no_animate_killing_time


# Запуск анимации
    playanimation @s[tag=!no_animate_killing_time, scores={custom_random=0..333}] animation.killing_time.a a 0.1 "query.is_moving || q.property('arx:is_knocked') > 0"
    playanimation @s[tag=!no_animate_killing_time, scores={custom_random=333..666}] animation.killing_time.b a 0.1 "query.is_moving || q.property('arx:is_knocked') > 0"
    playanimation @s[tag=!no_animate_killing_time, scores={custom_random=666..1000}] animation.killing_time.c a 0.1 "query.is_moving || q.property('arx:is_knocked') > 0"

# Чистка тегов
    tag @s remove no_animate_killing_time