execute as @a[scores={max_light_range=5, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=5, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=5, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=5, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=5, lamp_oil=1..6249}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=6, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=6, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=6, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=6, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=6, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=6, lamp_oil=1..3124}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=7, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=7, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=7, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=7, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=7, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=7, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=7, lamp_oil=1..1561}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=8, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=8, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=8, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=8, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=8, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=8, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=8, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=8, lamp_oil=1..780}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=9, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=9, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=9, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=9, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=9, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=9, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=9, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=9, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=9, lamp_oil=1..389}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=10, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=10, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=10, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=10, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=10, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=10, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=10, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=10, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=10, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=10, lamp_oil=1..194}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=11, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 11
execute as @a[scores={max_light_range=11, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=11, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=11, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=11, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=11, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=11, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=11, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=11, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=11, lamp_oil=97..194}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=11, lamp_oil=1..96}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=12, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 12
execute as @a[scores={max_light_range=12, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 11
execute as @a[scores={max_light_range=12, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=12, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=12, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=12, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=12, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=12, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=12, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=12, lamp_oil=97..194}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=12, lamp_oil=48..96}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=12, lamp_oil=1..47}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=13, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 13
execute as @a[scores={max_light_range=13, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 12
execute as @a[scores={max_light_range=13, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 11
execute as @a[scores={max_light_range=13, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=13, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=13, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=13, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=13, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=13, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=13, lamp_oil=97..194}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=13, lamp_oil=48..96}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=13, lamp_oil=24..47}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=13, lamp_oil=1..23}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=14, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 14
execute as @a[scores={max_light_range=14, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 13
execute as @a[scores={max_light_range=14, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 12
execute as @a[scores={max_light_range=14, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 11
execute as @a[scores={max_light_range=14, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=14, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=14, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=14, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=14, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=14, lamp_oil=97..194}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=14, lamp_oil=48..96}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=14, lamp_oil=24..47}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=14, lamp_oil=12..23}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=14, lamp_oil=1..11}] run scoreboard players set @s dynamic_light_power 1

execute as @a[scores={max_light_range=15, lamp_oil=50000..100000}] run scoreboard players set @s dynamic_light_power 15
execute as @a[scores={max_light_range=15, lamp_oil=25000..49999}] run scoreboard players set @s dynamic_light_power 14
execute as @a[scores={max_light_range=15, lamp_oil=12500..24999}] run scoreboard players set @s dynamic_light_power 13
execute as @a[scores={max_light_range=15, lamp_oil=6250..12499}] run scoreboard players set @s dynamic_light_power 12
execute as @a[scores={max_light_range=15, lamp_oil=3125..6249}] run scoreboard players set @s dynamic_light_power 11
execute as @a[scores={max_light_range=15, lamp_oil=1562..3124}] run scoreboard players set @s dynamic_light_power 10
execute as @a[scores={max_light_range=15, lamp_oil=781..1561}] run scoreboard players set @s dynamic_light_power 9
execute as @a[scores={max_light_range=15, lamp_oil=390..780}] run scoreboard players set @s dynamic_light_power 8
execute as @a[scores={max_light_range=15, lamp_oil=195..389}] run scoreboard players set @s dynamic_light_power 7
execute as @a[scores={max_light_range=15, lamp_oil=97..194}] run scoreboard players set @s dynamic_light_power 6
execute as @a[scores={max_light_range=15, lamp_oil=48..96}] run scoreboard players set @s dynamic_light_power 5
execute as @a[scores={max_light_range=15, lamp_oil=24..47}] run scoreboard players set @s dynamic_light_power 4
execute as @a[scores={max_light_range=15, lamp_oil=12..23}] run scoreboard players set @s dynamic_light_power 3
execute as @a[scores={max_light_range=15, lamp_oil=6..11}] run scoreboard players set @s dynamic_light_power 2
execute as @a[scores={max_light_range=15, lamp_oil=1..5}] run scoreboard players set @s dynamic_light_power 1