# Это функция отображения маны
# Запрещаем показывать ману при определенных условиях (deny_to_show_mp_on_actionbar)
    tag @a remove deny_to_show_mp_on_actionbar
    # Запрещаем в комнате респавна
        tag @a[tag=at_respawn_room] add deny_to_show_mp_on_actionbar
    # Запрещаем, если на прошлой проходке мана была максимальной
        tag @a[tag=mp_was_equal_to_max_mp_last_pass] add deny_to_show_mp_on_actionbar
    # Запрещаем, если держим посох
        tag @a[tag=holds_staff_sexto] add deny_to_show_mp_on_actionbar
        tag @a[tag=holds_staff_quintu] add deny_to_show_mp_on_actionbar
        tag @a[tag=holds_staff_quadro] add deny_to_show_mp_on_actionbar
        tag @a[tag=holds_staff_trio] add deny_to_show_mp_on_actionbar
        tag @a[tag=holds_staff_duo] add deny_to_show_mp_on_actionbar
        tag @a[tag=holds_staff_mono] add deny_to_show_mp_on_actionbar
    # Запрещаем, если нет навыка
        tag @a[scores={sk_a_22=0}] add deny_to_show_mp_on_actionbar

title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=0}] actionbar 0 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=1}] actionbar 1 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=2}] actionbar 2 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=3}] actionbar 3 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=4}] actionbar 4 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=5}] actionbar 5 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=6}] actionbar 6 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=7}] actionbar 7 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=8}] actionbar 8 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=9}] actionbar 9 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=10}] actionbar 10 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=11}] actionbar 11 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=12}] actionbar 12 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=13}] actionbar 13 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=14}] actionbar 14 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=15}] actionbar 15 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=16}] actionbar 16 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=17}] actionbar 17 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=18}] actionbar 18 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=19}] actionbar 19 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=20}] actionbar 20 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=21}] actionbar 21 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=22}] actionbar 22 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=23}] actionbar 23 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=24}] actionbar 24 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=25}] actionbar 25 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=26}] actionbar 26 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=27}] actionbar 27 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=28}] actionbar 28 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=29}] actionbar 29 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=30}] actionbar 30 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=31}] actionbar 31 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=32}] actionbar 32 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=33}] actionbar 33 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=34}] actionbar 34 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=35}] actionbar 35 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=36}] actionbar 36 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=37}] actionbar 37 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=38}] actionbar 38 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=39}] actionbar 39 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=40}] actionbar 40 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=41}] actionbar 41 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=42}] actionbar 42 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=43}] actionbar 43 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=44}] actionbar 44 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=45}] actionbar 45 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=46}] actionbar 46 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=47}] actionbar 47 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=48}] actionbar 48 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=49}] actionbar 49 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=50}] actionbar 50 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=51}] actionbar 51 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=52}] actionbar 52 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=53}] actionbar 53 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=54}] actionbar 54 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=55}] actionbar 55 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=56}] actionbar 56 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=57}] actionbar 57 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=58}] actionbar 58 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=59}] actionbar 59 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=60}] actionbar 60 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=61}] actionbar 61 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=62}] actionbar 62 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=63}] actionbar 63 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=64}] actionbar 64 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=65}] actionbar 65 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=66}] actionbar 66 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=67}] actionbar 67 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=68}] actionbar 68 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=69}] actionbar 69 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=70}] actionbar 70 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=71}] actionbar 71 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=72}] actionbar 72 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=73}] actionbar 73 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=74}] actionbar 74 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=75}] actionbar 75 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=76}] actionbar 76 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=77}] actionbar 77 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=78}] actionbar 78 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=79}] actionbar 79 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=80}] actionbar 80 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=81}] actionbar 81 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=82}] actionbar 82 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=83}] actionbar 83 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=84}] actionbar 84 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=85}] actionbar 85 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=86}] actionbar 86 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=87}] actionbar 87 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=88}] actionbar 88 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=89}] actionbar 89 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=90}] actionbar 90 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=91}] actionbar 91 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=92}] actionbar 92 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=93}] actionbar 93 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=94}] actionbar 94 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=95}] actionbar 95 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=96}] actionbar 96 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=97}] actionbar 97 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=98}] actionbar 98 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=99}] actionbar 99 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=100}] actionbar 100 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=101}] actionbar 101 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=102}] actionbar 102 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=103}] actionbar 103 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=104}] actionbar 104 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=105}] actionbar 105 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=106}] actionbar 106 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=107}] actionbar 107 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=108}] actionbar 108 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=109}] actionbar 109 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=110}] actionbar 110 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=111}] actionbar 111 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=112}] actionbar 112 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=113}] actionbar 113 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=114}] actionbar 114 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=115}] actionbar 115 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=116}] actionbar 116 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=117}] actionbar 117 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=118}] actionbar 118 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=119}] actionbar 119 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=120}] actionbar 120 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=121}] actionbar 121 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=122}] actionbar 122 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=123}] actionbar 123 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=124}] actionbar 124 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=125}] actionbar 125 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=126}] actionbar 126 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=127}] actionbar 127 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=128}] actionbar 128 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=129}] actionbar 129 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=130}] actionbar 130 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=131}] actionbar 131 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=132}] actionbar 132 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=133}] actionbar 133 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=134}] actionbar 134 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=135}] actionbar 135 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=136}] actionbar 136 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=137}] actionbar 137 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=138}] actionbar 138 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=139}] actionbar 139 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=140}] actionbar 140 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=141}] actionbar 141 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=142}] actionbar 142 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=143}] actionbar 143 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=144}] actionbar 144 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=145}] actionbar 145 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=146}] actionbar 146 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=147}] actionbar 147 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=148}] actionbar 148 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=149}] actionbar 149 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=150}] actionbar 150 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=151}] actionbar 151 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=152}] actionbar 152 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=153}] actionbar 153 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=154}] actionbar 154 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=155}] actionbar 155 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=156}] actionbar 156 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=157}] actionbar 157 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=158}] actionbar 158 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=159}] actionbar 159 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=160}] actionbar 160 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=161}] actionbar 161 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=162}] actionbar 162 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=163}] actionbar 163 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=164}] actionbar 164 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=165}] actionbar 165 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=166}] actionbar 166 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=167}] actionbar 167 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=168}] actionbar 168 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=169}] actionbar 169 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=170}] actionbar 170 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=171}] actionbar 171 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=172}] actionbar 172 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=173}] actionbar 173 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=174}] actionbar 174 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=175}] actionbar 175 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=176}] actionbar 176 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=177}] actionbar 177 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=178}] actionbar 178 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=179}] actionbar 179 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=180}] actionbar 180 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=181}] actionbar 181 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=182}] actionbar 182 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=183}] actionbar 183 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=184}] actionbar 184 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=185}] actionbar 185 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=186}] actionbar 186 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=187}] actionbar 187 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=188}] actionbar 188 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=189}] actionbar 189 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=190}] actionbar 190 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=191}] actionbar 191 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=192}] actionbar 192 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=193}] actionbar 193 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=194}] actionbar 194 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=195}] actionbar 195 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=196}] actionbar 196 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=197}] actionbar 197 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=198}] actionbar 198 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=199}] actionbar 199 §1MP
title @a[tag=!deny_to_show_mp_on_actionbar, scores={mp=200..}] actionbar 200+ §1MP