# Это функция титла при держании рун. Запускается лично для каждого игрока, т.е. должна иметь синтаксис @a

tag @a remove holds_rune

tag @a[hasitem={item=arx:rune_affuono_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_affuono_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_affuono_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_arrako_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_arrako_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_arrako_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_din_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_din_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_din_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_disortari_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_disortari_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_disortari_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_elletera_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_elletera_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_elletera_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_floruum_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_floruum_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_floruum_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_flurri_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_flurri_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_flurri_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_hijo_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_hijo_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_hijo_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_horo_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_horo_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_horo_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_inoffo_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_inoffo_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_inoffo_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kon_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kon_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kon_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kotoka_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kotoka_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_kotoka_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_laffaeti_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_laffaeti_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_laffaeti_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_low_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_low_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_low_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_marra_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_marra_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_marra_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_mega_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_mega_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_mega_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_orduino_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_orduino_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_orduino_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_recuro_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_recuro_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_recuro_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sakiifori_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sakiifori_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sakiifori_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_san_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_san_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_san_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sartagana_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sartagana_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sartagana_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sempra_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sempra_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sempra_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_shumi_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_shumi_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_shumi_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sin_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sin_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sin_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sofiso_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sofiso_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sofiso_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_subversa_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_subversa_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_subversa_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sukimo_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sukimo_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_sukimo_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_trafantana_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_trafantana_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_trafantana_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_transkursio_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_transkursio_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_transkursio_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_watashi_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_watashi_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_watashi_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_yanamo_a, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_yanamo_b, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_yanamo_s, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_nakamata, location=slot.weapon.mainhand}] add holds_rune
tag @a[hasitem={item=arx:rune_ratatao, location=slot.weapon.mainhand}] add holds_rune
