# heavy - вес, который прямо сейчас несет игрок

# Устанавливаем значение в 0
    scoreboard players set @a heavy 0

# Рассчитываем, что мы несем
    #Оружие
        scoreboard players add @a[hasitem={item=arx:costorub}] heavy 4
        scoreboard players add @a[hasitem={item=arx:delimiter}] heavy 10
        scoreboard players add @a[hasitem={item=arx:golden_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:dorionite_dismantler}] heavy 7
        scoreboard players add @a[hasitem={item=arx:steel_heavy_crusher}] heavy 7
        scoreboard players add @a[hasitem={item=arx:steel_light_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:adona_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:blood_waiting}] heavy 3
        scoreboard players add @a[hasitem={item=arx:tearing_flesh}] heavy 2
        scoreboard players add @a[hasitem={item=arx:bone_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:spear_with_gold_inlays}] heavy 4
        scoreboard players add @a[hasitem={item=arx:steel_wide_shortsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_wide_shortsword_with_special_guard}] heavy 2
        scoreboard players add @a[hasitem={item=arx:golden_ossified_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:powered_steel_wide_shortsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:golden_dagger_fang}] heavy 1
        scoreboard players add @a[hasitem={item=arx:hunting_cast_iron_knife}] heavy 1
        scoreboard players add @a[hasitem={item=arx:steel_sharp_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:simple_iron_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dagger_fang}] heavy 1
        scoreboard players add @a[hasitem={item=arx:longed_cast_iron_dagger}] heavy 2
        scoreboard players add @a[hasitem={item=arx:notched_durasteel_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:simple_stone_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:fish_knife}] heavy 1
        scoreboard players add @a[hasitem={item=arx:podlik}] heavy 1
        scoreboard players add @a[hasitem={item=arx:chloronite_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:steel_advanced_guard_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dagger_of_the_gap}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dagger_with_golden_blade}] heavy 1
        scoreboard players add @a[hasitem={item=arx:vicious_dagger}] heavy 1
        scoreboard players add @a[hasitem={item=arx:vicious_dagger_refined}] heavy 1
        scoreboard players add @a[hasitem={item=arx:even}] heavy 3
        scoreboard players add @a[hasitem={item=arx:cast_iron_hammer_crusher}] heavy 5
        scoreboard players add @a[hasitem={item=arx:flesh_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:dorionite_hammer}] heavy 4
        scoreboard players add @a[hasitem={item=arx:heavy_axe_with_chloronite_inlays}] heavy 7
        scoreboard players add @a[hasitem={item=arx:petrified_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:rose_crusher}] heavy 1
        scoreboard players add @a[hasitem={item=arx:bronze_fang}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_heavy_crusher}] heavy 3
        scoreboard players add @a[hasitem={item=arx:altaite_small_hammer}] heavy 4
        scoreboard players add @a[hasitem={item=arx:bronze_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:copper_heavy_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:dorionite_battleaxe}] heavy 7
        scoreboard players add @a[hasitem={item=arx:dorionite_powered_battleaxe}] heavy 8
        scoreboard players add @a[hasitem={item=arx:wooden_wide_sword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:red_crystal_crusher}] heavy 7
        scoreboard players add @a[hasitem={item=arx:plumbum_small_hammer}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_chorper}] heavy 6
        scoreboard players add @a[hasitem={item=arx:durasteel_sword_with_bronze_inlays}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_heavy_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:altaite_battlehammer}] heavy 5
        scoreboard players add @a[hasitem={item=arx:ideal_altaite_sword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:durasteel_longsword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:dorionite_secyra_with_sapphiers}] heavy 3
        scoreboard players add @a[hasitem={item=arx:netherite_crusher}] heavy 4
        scoreboard players add @a[hasitem={item=arx:netherite_heavy_secyra}] heavy 5
        scoreboard players add @a[hasitem={item=arx:leave_axe}] heavy 5
        scoreboard players add @a[hasitem={item=arx:stone_heavy_crusher}] heavy 5
        scoreboard players add @a[hasitem={item=arx:riolik_hammer}] heavy 4
        scoreboard players add @a[hasitem={item=arx:cast_iron_board}] heavy 4
        scoreboard players add @a[hasitem={item=arx:duraluminium_crusher}] heavy 5
        scoreboard players add @a[hasitem={item=arx:caryite_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:bronze_crusher}] heavy 6
        scoreboard players add @a[hasitem={item=arx:full_golden_longsword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:durasteel_ripper}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dorionite_small_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:bronze_great_battleaxe}] heavy 5
        scoreboard players add @a[hasitem={item=arx:caryite_small_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:stone_tomahawk}] heavy 3
        scoreboard players add @a[hasitem={item=arx:iron_default_axe}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_very_heavy_crusher}] heavy 3
        scoreboard players add @a[hasitem={item=arx:naginitis_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:elder_crusher}] heavy 3
        scoreboard players add @a[hasitem={item=arx:caryite_and_toliriite_sword}] heavy 6
        scoreboard players add @a[hasitem={item=arx:naginits_and_forfacorite_sword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:netherite_secyra}] heavy 3
        scoreboard players add @a[hasitem={item=arx:riolik_heavy_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:duraluminium_short_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:cast_iron_hammer}] heavy 5
        scoreboard players add @a[hasitem={item=arx:netherite_bonecrusher}] heavy 9
        scoreboard players add @a[hasitem={item=arx:cast_netherite_crusher}] heavy 7
        scoreboard players add @a[hasitem={item=arx:steel_heavy_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dorionite_ripper}] heavy 7
        scoreboard players add @a[hasitem={item=arx:toliriite_ripper}] heavy 6
        scoreboard players add @a[hasitem={item=arx:red_crystal_heavy_sword}] heavy 8
        scoreboard players add @a[hasitem={item=arx:toliriite_cutter}] heavy 5
        scoreboard players add @a[hasitem={item=arx:bronze_crusher_with_cornelian}] heavy 7
        scoreboard players add @a[hasitem={item=arx:lamenite_megahammer}] heavy 5
        scoreboard players add @a[hasitem={item=arx:netherite_blade}] heavy 6
        scoreboard players add @a[hasitem={item=arx:bronze_and_caryite_axe}] heavy 7
        scoreboard players add @a[hasitem={item=arx:clear_dorionite_sword}] heavy 8
        scoreboard players add @a[hasitem={item=arx:duraluminium_sword_with_draphorite_inlays}] heavy 6
        scoreboard players add @a[hasitem={item=arx:dorionite_megahammer}] heavy 10
        scoreboard players add @a[hasitem={item=arx:caryite_and_toliriite_wide_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:durasteel_extreme_long_sword}] heavy 13
        scoreboard players add @a[hasitem={item=arx:bronze_hammer}] heavy 9
        scoreboard players add @a[hasitem={item=arx:draphorite_sword}] heavy 7
        scoreboard players add @a[hasitem={item=arx:duraluminium_dismantler_with_draphorite_inlays}] heavy 7
        scoreboard players add @a[hasitem={item=arx:cast_iron_heavy_crusher}] heavy 9
        scoreboard players add @a[hasitem={item=arx:cast_iron_battleaxe_with_chloronite_inlays}] heavy 7
        scoreboard players add @a[hasitem={item=arx:durasteel_wide_greatsword}] heavy 15
        scoreboard players add @a[hasitem={item=arx:wide_cross_sword}] heavy 7
        scoreboard players add @a[hasitem={item=arx:harbinger_of_dawn}] heavy 8
        scoreboard players add @a[hasitem={item=arx:caryite_delimiter}] heavy 7
        scoreboard players add @a[hasitem={item=arx:caryite_sword_with_sapphire}] heavy 5
        scoreboard players add @a[hasitem={item=arx:bronze_and_gold_alloy_battleaxe}] heavy 7
        scoreboard players add @a[hasitem={item=arx:steel_big_longsword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:ravensword}] heavy 8
        scoreboard players add @a[hasitem={item=arx:steel_longsword_with_altaite_inlays}] heavy 7
        scoreboard players add @a[hasitem={item=arx:clear_caryite_crusher}] heavy 8
        scoreboard players add @a[hasitem={item=arx:flesh_hell_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dorionite_long_sword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:cast_iron_greatsword}] heavy 13
        scoreboard players add @a[hasitem={item=arx:elder_battleboard}] heavy 5
        scoreboard players add @a[hasitem={item=arx:tin_heavy_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:elder_white_crusher}] heavy 7
        scoreboard players add @a[hasitem={item=arx:chloronite_big_sword}] heavy 6
        scoreboard players add @a[hasitem={item=arx:duraluminium_delimiter}] heavy 5
        scoreboard players add @a[hasitem={item=arx:cast_iron_alebard}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_lance}] heavy 2
        scoreboard players add @a[hasitem={item=arx:cast_iron_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:duraluminium_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:durasteel_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:durasteel_spear}] heavy 3
        scoreboard players add @a[hasitem={item=arx:netherite_lance}] heavy 4
        scoreboard players add @a[hasitem={item=arx:steel_spear}] heavy 3
        scoreboard players add @a[hasitem={item=arx:netherite_naginata}] heavy 3
        scoreboard players add @a[hasitem={item=arx:durasteel_lance_with_draphorite_inlays}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dorionite_lance}] heavy 4
        scoreboard players add @a[hasitem={item=arx:durasteel_and_aluminium_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:bronze_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:cast_iron_longsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:naginitis_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:simple_iron_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:sacrificial_iron_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:plumbum_full_small_hammer}] heavy 3
        scoreboard players add @a[hasitem={item=arx:wooden_longsword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:plumbum_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:netherite_ripper}] heavy 4
        scoreboard players add @a[hasitem={item=arx:caryite_saber}] heavy 4
        scoreboard players add @a[hasitem={item=arx:duraluminium_battleaxe_with_draphorite_inlays}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_simple_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:copper_sword_hook}] heavy 2
        scoreboard players add @a[hasitem={item=arx:simple_iron_axe}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_simple_sword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:steel_saber}] heavy 3
        scoreboard players add @a[hasitem={item=arx:durasteel_simple_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:dorionite_battleaxe_with_caryite_inlays}] heavy 3
        scoreboard players add @a[hasitem={item=arx:dorionite_double_edged_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:plumbum_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:aluminium_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:simple_iron_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:iron_wide_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_weighted_sword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:aluminium_curved_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:iron_wide_heavy_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:bronze_longed_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_sword_with_copper_guard}] heavy 2
        scoreboard players add @a[hasitem={item=arx:bronze_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:bronze_heighted_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:steel_mace}] heavy 4
        scoreboard players add @a[hasitem={item=arx:plumbum_axe}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_longsword_with_copper_guard}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:tin_curved_saber}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_crossword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:bronze_trident}] heavy 4
        scoreboard players add @a[hasitem={item=arx:durasteel_streight_longsword}] heavy 5
        scoreboard players add @a[hasitem={item=arx:tin_small_battleaxe}] heavy 3
        scoreboard players add @a[hasitem={item=arx:plumbum_small_longsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_one_sided_sword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:steel_sword_with_golden_guard}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wooden_battleaxe}] heavy 1
        scoreboard players add @a[hasitem={item=arx:plumbum_heighted_longsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:naginitis_weighted_battleaxe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:altaite_saber}] heavy 3
        scoreboard players add @a[hasitem={item=arx:cast_iron_long_saber}] heavy 2
        scoreboard players add @a[hasitem={item=arx:durasteel_small_longsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:golden_trident}] heavy 3
        scoreboard players add @a[hasitem={item=arx:forfacorite_longsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:stone_longsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_battleaxe}] heavy 5
        scoreboard players add @a[hasitem={item=arx:plumbum_lighted_small_longsword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:duraluminium_great_battleaxe}] heavy 5
        scoreboard players add @a[hasitem={item=arx:scythe_altaite}] heavy 3
        scoreboard players add @a[hasitem={item=arx:scythe_netherite}] heavy 4
        scoreboard players add @a[hasitem={item=arx:scythe_caryite}] heavy 4
        scoreboard players add @a[hasitem={item=arx:scythe_tin}] heavy 2
        scoreboard players add @a[hasitem={item=arx:scythe_chloronite}] heavy 3
        scoreboard players add @a[hasitem={item=arx:scythe_toliriite}] heavy 3
        scoreboard players add @a[hasitem={item=arx:scythe_steel}] heavy 3
        scoreboard players add @a[hasitem={item=arx:scythe_forfacorite}] heavy 3
        scoreboard players add @a[hasitem={item=arx:scythe_naginitis}] heavy 3
        scoreboard players add @a[hasitem={item=arx:jagged_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_alebard}] heavy 3
        scoreboard players add @a[hasitem={item=arx:vicious_lance}] heavy 3
        scoreboard players add @a[hasitem={item=arx:vicious_lance_refined}] heavy 4
        scoreboard players add @a[hasitem={item=arx:durasteel_sword_with_dorionite}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_heavy_longsword}] heavy 4
        scoreboard players add @a[hasitem={item=arx:steel_tooth}] heavy 3
        scoreboard players add @a[hasitem={item=arx:plumbum_dark_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:plumbum_simple_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_classic_sword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_sword_with_red_guard}] heavy 2
        scoreboard players add @a[hasitem={item=arx:powered_steel_shortsword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_shortsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_dark_shortsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:chloronite_shortsword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:chloronite_shortsword_magik}] heavy 2
        scoreboard players add @a[hasitem={item=arx:caryite_heavysword}] heavy 3
        scoreboard players add @a[hasitem={item=arx:cast_iron_tooth}] heavy 3
        scoreboard players add @a[hasitem={item=arx:steel_sword_with_gold_inlay}] heavy 3
        scoreboard players add @a[hasitem={item=arx:holy_sword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:aluminium_simple_sword}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_simple_blade}] heavy 2
        scoreboard players add @a[hasitem={item=arx:steel_cleaver}] heavy 2
        scoreboard players add @a[hasitem={item=arx:plumbum_saber}] heavy 3
        scoreboard players add @a[hasitem={item=arx:wooden_carved_sword}] heavy 1
        scoreboard players add @a[hasitem={item=arx:long_steel_sword_with_draphorite_inlays}] heavy 4

        scoreboard players add @a[hasitem={item=arx:staff_san}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_caryite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_wooden}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_dragon}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_gold}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_netherite_with_ruby}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_dark_netherite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_golden_with_sapphire}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_chrysolite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_naginitis}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_cast_iron_with_chrysolite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_phoenix}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_with_ruby}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_with_skull}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_forest}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_twilight}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_golden_with_chrysolite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_simple_with_ruby}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_chloronite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_wooden_with_chrysolite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_dorionite_with_caryite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_with_diamond}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_wooden_with_riolik}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_tin_with_gold}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_dorionite}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_steel_with_topaz}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_kon}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_golden_with_violet_handle}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_scarlet_moon}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_battle}] heavy 3
        scoreboard players add @a[hasitem={item=arx:staff_battle_custom_magik}] heavy 3
        scoreboard players add @a[hasitem={item=arx:staff_of_hell}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_snowlands}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_din}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_sin}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_shaman}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_precious}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_angel}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_golden_cross}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_fulminant}] heavy 1
        scoreboard players add @a[hasitem={item=arx:staff_of_heaven}] heavy 1
        scoreboard players add @a[hasitem={item=arx:vicious_staff}] heavy 1
        scoreboard players add @a[hasitem={item=arx:vicious_staff_refined}] heavy 1
        scoreboard players add @a[hasitem={item=arx:hacksaw}] heavy 1
        scoreboard players add @a[hasitem={item=arx:composite_toothed_sawsword}] heavy 5

    #Особые предметы
        scoreboard players add @a[hasitem={item=arx:shackles}] heavy 3
        scoreboard players add @a[hasitem={item=arx:blacksmith_tongs}] heavy 1
        scoreboard players add @a[hasitem={item=arx:blacksmith_tongs_super}] heavy 2
        scoreboard players add @a[hasitem={item=arx:heater}] heavy 3

    #Одежда
        scoreboard players add @a[hasitem={item=arx:adona_jacket}] heavy 2
        scoreboard players add @a[hasitem={item=arx:apprentice_robe}] heavy 2
        scoreboard players add @a[hasitem={item=arx:archmage_robe}] heavy 2
        scoreboard players add @a[hasitem={item=arx:big_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:big_hat_dyed_blue}] heavy 1
        scoreboard players add @a[hasitem={item=arx:big_hat_dyed_red}] heavy 1
        scoreboard players add @a[hasitem={item=arx:big_hat_dyed_white}] heavy 1
        scoreboard players add @a[hasitem={item=arx:big_hat_dyed_black}] heavy 1
        scoreboard players add @a[hasitem={item=arx:black_jacket}] heavy 2
        scoreboard players add @a[hasitem={item=arx:bloody_robe}] heavy 2
        scoreboard players add @a[hasitem={item=arx:blue_pirate_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:bone_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:cape_of_purple_dust}] heavy 1
        scoreboard players add @a[hasitem={item=arx:cheap_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:citizen_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:clothes_of_roaring_winds}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dealer_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:demon_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:derek_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:diadem_of_desert_wanderer}] heavy 1
        scoreboard players add @a[hasitem={item=arx:diadem_of_the_forgotten_queen}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dress_of_green_rose}] heavy 1
        scoreboard players add @a[hasitem={item=arx:elven_tunic}] heavy 1
        scoreboard players add @a[hasitem={item=arx:exquisite_town_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:farmers_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:fox_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:fox_sakura_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:gown_of_desert_wanderer}] heavy 1
        scoreboard players add @a[hasitem={item=arx:gray_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:night_hunter_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:gray_dress_of_the_forgotten_queen}] heavy 1
        scoreboard players add @a[hasitem={item=arx:horn_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:hu_tao_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:kofata_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:morning_forest_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:night_vision_device}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pallada_sweater}] heavy 2
        scoreboard players add @a[hasitem={item=arx:pirate_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:pirate_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pireta_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:plague_doctor_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:purple_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:ranger_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:red_brassiere}] heavy 1
        scoreboard players add @a[hasitem={item=arx:red_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:red_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:rich_jacket}] heavy 2
        scoreboard players add @a[hasitem={item=arx:robe_of_clouds}] heavy 2
        scoreboard players add @a[hasitem={item=arx:robe_of_desert}] heavy 1
        scoreboard players add @a[hasitem={item=arx:sailors_clothing}] heavy 1
        scoreboard players add @a[hasitem={item=arx:scarlet_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:scientists_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:shepherd_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:simple_open_clothing}] heavy 1
        scoreboard players add @a[hasitem={item=arx:simple_skin_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:simple_worker_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:slave_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:steampunk_pants}] heavy 2
        scoreboard players add @a[hasitem={item=arx:stroller_clothes}] heavy 3
        scoreboard players add @a[hasitem={item=arx:travelers_cape}] heavy 2
        scoreboard players add @a[hasitem={item=arx:wanderer_jacket}] heavy 3
        scoreboard players add @a[hasitem={item=arx:watermelon_hat}] heavy 2
        scoreboard players add @a[hasitem={item=arx:white_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:wide_hat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:women_face}] heavy 1
        scoreboard players add @a[hasitem={item=arx:youkai_mask}] heavy 1
        scoreboard players add @a[hasitem={item=arx:descriptor}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pink_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:home_gown}] heavy 1
        scoreboard players add @a[hasitem={item=arx:blue_dawn_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:archer_coat}] heavy 2
        scoreboard players add @a[hasitem={item=arx:astronomer_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:dark_captain_jacket}] heavy 2
        scoreboard players add @a[hasitem={item=arx:dark_shepherd_clothes}] heavy 1
        scoreboard players add @a[hasitem={item=arx:desert_traders_hood}] heavy 1
        scoreboard players add @a[hasitem={item=arx:desert_traders_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:eclipse_tunic}] heavy 1
        scoreboard players add @a[hasitem={item=arx:elite_gown}] heavy 1
        scoreboard players add @a[hasitem={item=arx:forest_fairy_bandages}] heavy 1
        scoreboard players add @a[hasitem={item=arx:mantle_of_swamp_alchemist}] heavy 1
        scoreboard players add @a[hasitem={item=arx:mayor_coat}] heavy 1
        scoreboard players add @a[hasitem={item=arx:moon_fierce}] heavy 1
        scoreboard players add @a[hasitem={item=arx:red_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:red_sunset_dress}] heavy 1
        scoreboard players add @a[hasitem={item=arx:robe_of_dark_priest}] heavy 2
        scoreboard players add @a[hasitem={item=arx:royal_gown}] heavy 1
        scoreboard players add @a[hasitem={item=arx:scarlet_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:swordsman_clothes}] heavy 2
        scoreboard players add @a[hasitem={item=arx:twilight_cape}] heavy 1
        scoreboard players add @a[hasitem={item=arx:twilight_dress}] heavy 1

    # Религиозная одежда
        scoreboard players add @a[hasitem={item=arx:pallas_apprentice_robe}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pires_apprentice_robe}] heavy 1
        scoreboard players add @a[hasitem={item=arx:necro_mantle}] heavy 1
        scoreboard players add @a[hasitem={item=arx:necro_mantle_zel}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pallas_mage_mantle}] heavy 1
        scoreboard players add @a[hasitem={item=arx:pires_mage_mantle}] heavy 1

    #Лёгкая броня
        scoreboard players add @a[hasitem={item=arx:armored_blue_clothes}] heavy 3
        scoreboard players add @a[hasitem={item=arx:armored_chain_mail_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:armored_robe}] heavy 4
        scoreboard players add @a[hasitem={item=arx:beryl_armor}] heavy 2
        scoreboard players add @a[hasitem={item=arx:crown_with_ruby}] heavy 2
        scoreboard players add @a[hasitem={item=arx:dwarf_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:dwarf_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:golden_crown}] heavy 3
        scoreboard players add @a[hasitem={item=arx:golden_silk_coat}] heavy 3
        scoreboard players add @a[hasitem={item=arx:knight_chain_mail}] heavy 4
        scoreboard players add @a[hasitem={item=arx:knight_chain_mail_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:knight_light_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:knight_light_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:light_chestplate}] heavy 2
        scoreboard players add @a[hasitem={item=arx:lightweight_combat_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:militiaman_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:militiaman_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:moon_mask}] heavy 2
        scoreboard players add @a[hasitem={item=arx:night_knight}] heavy 3
        scoreboard players add @a[hasitem={item=arx:night_knight_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:pallas_crown}] heavy 2
        scoreboard players add @a[hasitem={item=arx:pires_crown}] heavy 2
        scoreboard players add @a[hasitem={item=arx:precious_coat}] heavy 3
        scoreboard players add @a[hasitem={item=arx:protector_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:raven_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:silk_reinforced_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:skull_mask}] heavy 2
        scoreboard players add @a[hasitem={item=arx:warrior_chain_mail}] heavy 3
        scoreboard players add @a[hasitem={item=arx:warrior_helmet}] heavy 3

        scoreboard players add @a[hasitem={item=arx:pallas_assasin_clothing}] heavy 4
        scoreboard players add @a[hasitem={item=arx:pires_ranger_coat}] heavy 4

        scoreboard players add @a[hasitem={item=arx:baron_gambeson}] heavy 4
        scoreboard players add @a[hasitem={item=arx:desert_protector_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:hell_fighter_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:swordsman_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:light_leather_armor}] heavy 3
        scoreboard players add @a[hasitem={item=arx:snow_lord_armor}] heavy 5

    #Тяжёлая броня
        scoreboard players add @a[hasitem={item=arx:crimson_armor}] heavy 7
        scoreboard players add @a[hasitem={item=arx:dark_knight_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dark_knight_helmet}] heavy 4
        scoreboard players add @a[hasitem={item=arx:dragon_slayer_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:dragon_slayer_helmet}] heavy 4
        scoreboard players add @a[hasitem={item=arx:duke_armor}] heavy 4
        scoreboard players add @a[hasitem={item=arx:duke_helmet}] heavy 3
        scoreboard players add @a[hasitem={item=arx:durasteel_armor}] heavy 6
        scoreboard players add @a[hasitem={item=arx:durasteel_helmet}] heavy 5
        scoreboard players add @a[hasitem={item=arx:heavy_plate_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:heavy_plate_helmet}] heavy 5
        scoreboard players add @a[hasitem={item=arx:knight_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:knight_helmet}] heavy 4
        scoreboard players add @a[hasitem={item=arx:knight_steel_armor}] heavy 5
        scoreboard players add @a[hasitem={item=arx:northerner_armor}] heavy 7
        scoreboard players add @a[hasitem={item=arx:northerner_helmet}] heavy 6
        scoreboard players add @a[hasitem={item=arx:old_camp_armor}] heavy 6
        scoreboard players add @a[hasitem={item=arx:precursor_armor}] heavy 6
        scoreboard players add @a[hasitem={item=arx:precursor_helmet}] heavy 6
        scoreboard players add @a[hasitem={item=arx:purple_plate_helmet}] heavy 5
        scoreboard players add @a[hasitem={item=arx:purple_plates}] heavy 6
        scoreboard players add @a[hasitem={item=arx:steeletherite_armor}] heavy 8
        scoreboard players add @a[hasitem={item=arx:lamenite_plate_armor}] heavy 8

        scoreboard players add @a[hasitem={item=arx:silver_samurai_helmet}] heavy 6
        scoreboard players add @a[hasitem={item=arx:silver_samurai_armor}] heavy 8
        scoreboard players add @a[hasitem={item=arx:plate_chainmail_armor}] heavy 6
        scoreboard players add @a[hasitem={item=arx:snow_warrior_armor}] heavy 5

        scoreboard players add @a[hasitem={item=arx:pires_paladin_armor}] heavy 7
        scoreboard players add @a[hasitem={item=arx:pallas_conqueror_armor}] heavy 7

    # Вес от носимого игрока
        # Базовый 
            execute at @a[tag=is_riding, has_property={arx:is_knocked=1..}] run scoreboard players add @p[r=0.8, tag=has_riders] heavy 3
        # Экипировка
            execute at @a[tag=is_riding, has_property={arx:is_knocked=1..}] run scoreboard players operation @p[r=0.8, tag=has_riders] heavy += @s heavy

    # Сумки backpack_volume
        scoreboard players set @a backpack_volume 0
        scoreboard players add @a[hasitem={item=arx:leg_bag_dual, location=slot.armor.feet}] backpack_volume 2
        scoreboard players add @a[hasitem={item=arx:leg_bag, location=slot.armor.feet}] backpack_volume 1
        scoreboard players add @a[hasitem={item=arx:mini_bag, location=slot.armor.legs}] backpack_volume 2
        scoreboard players add @a[hasitem={item=arx:default_bag, location=slot.armor.legs}] backpack_volume 4
        scoreboard players add @a[hasitem={item=arx:big_bag, location=slot.armor.legs}] backpack_volume 8
        scoreboard players add @a[hasitem={item=arx:belt_bag, location=slot.armor.legs}] backpack_volume 1