scoreboard players set @s book_asar_i 0 
scoreboard players set @s book_asar_ii 0 
scoreboard players set @s book_asar_iii 0 
scoreboard players set @s book_asar_iv 0 
scoreboard players set @s book_th_ab_gods 0 
scoreboard players set @s book_golfari 0 
scoreboard players set @s book_namel_pal 0 
scoreboard players set @s book_holy_sakura 0 
scoreboard players set @s book_wand_puppet 0 
scoreboard players set @s book_dragon_arti 0 
scoreboard players set @s book_dext 0 
scoreboard players set @s book_philosophy 0 