scoreboard players set @s AAEK 0
scoreboard players set @s AAEKЗ 0
scoreboard players set @s AAEKЖ 0
scoreboard players set @s AAEKЗЖ 0
scoreboard players set @s AAEKЖЗ 0
scoreboard players set @s AAEKГ 0
scoreboard players set @s AAEKГЗ 0
scoreboard players set @s AAEKГГГ 0
scoreboard players set @s AAEKД 0
scoreboard players set @s AAEKДГ 0
scoreboard players set @s AAEKSГГГ 0
scoreboard players set @s AAEL 0
scoreboard players set @s AAELГ 0
scoreboard players set @s AAEWM 0
scoreboard players set @s AAEWMГ 0
scoreboard players set @s AAEWMГГГ 0
scoreboard players set @s AAEW 0
scoreboard players set @s AAEWГ 0
scoreboard players set @s AAEWЗ 0
scoreboard players set @s AAFW 0
scoreboard players set @s AAFWГ 0
scoreboard players set @s AAGЗ 0
scoreboard players set @s AAG 0
scoreboard players set @s AAJ 0
scoreboard players set @s AAE1 0
scoreboard players set @s AAE1Г 0
scoreboard players set @s AAE2 0
scoreboard players set @s AAE2Г 0
scoreboard players set @s ABFV 0
scoreboard players set @s ABFVГ 0
scoreboard players set @s ABEV 0
scoreboard players set @s ABEVГ 0
scoreboard players set @s ABGЗ 0
scoreboard players set @s ABG 0
scoreboard players set @s ABFQ 0
scoreboard players set @s ABFQЗ 0
scoreboard players set @s ABFQЖ 0
scoreboard players set @s ABFQГ 0
scoreboard players set @s ABFQГЗ 0
scoreboard players set @s ABFQГЖ 0
scoreboard players set @s ABFQГГ 0
scoreboard players set @s ABFQГГГ 0
scoreboard players set @s ABFБ 0
scoreboard players set @s ABFБГ 0
scoreboard players set @s ABFБГГГ 0
scoreboard players set @s ABFБZ 0
scoreboard players set @s ABFБZГ 0
scoreboard players set @s ABFБZГГГ 0
scoreboard players set @s ABJ 0
scoreboard players set @s ACFP 0
scoreboard players set @s ACFPГ 0
scoreboard players set @s ACFPГГ 0
scoreboard players set @s ACFPГГГ 0
scoreboard players set @s ACFPM 0
scoreboard players set @s ACFPMГ 0
scoreboard players set @s ACFPMГГГ 0
scoreboard players set @s ACFPMЗ 0
scoreboard players set @s ACFPMГЗ 0
scoreboard players set @s ACFPMГГГЗ 0
scoreboard players set @s ACFPW 0
scoreboard players set @s ACFPWЗ 0
scoreboard players set @s ACFT 0
scoreboard players set @s ACFTЖ 0
scoreboard players set @s ACFTЗ 0
scoreboard players set @s ACFQ 0
scoreboard players set @s ACFQЖ 0
scoreboard players set @s ACFQЗ 0
scoreboard players set @s ACFQГ 0
scoreboard players set @s ACFQГЗ 0
scoreboard players set @s ACFZ 0
scoreboard players set @s ACFZЖ 0
scoreboard players set @s ACFZЗ 0
scoreboard players set @s ACFO 0
scoreboard players set @s ACFOЗ 0
scoreboard players set @s ACFOЖ 0
scoreboard players set @s ACFOГ 0
scoreboard players set @s ACFOГЗ 0
scoreboard players set @s ACFOГЖ 0
scoreboard players set @s ACFOГГГ 0
scoreboard players set @s ACFOГГГЗ 0
scoreboard players set @s ACFOГГГЖ 0
scoreboard players set @s ACFOQГГГ 0
scoreboard players set @s ACFOQГГГЗ 0
scoreboard players set @s ACFS 0
scoreboard players set @s ACJ 0
scoreboard players set @s ACG 0
scoreboard players set @s ACGЗ 0
scoreboard players set @s ACF2 0
scoreboard players set @s ACIU 0
scoreboard players set @s ACIUГ 0
scoreboard players set @s ACFPU 0
scoreboard players set @s ACFPUЖ 0
scoreboard players set @s ACFPUГГГЖ 0
scoreboard players set @s ADITX 0
scoreboard players set @s ADGZЗ 0
scoreboard players set @s ADFM 0
scoreboard players set @s ADFMP 0
scoreboard players set @s ADFPZЖ 0
scoreboard players set @s ADFY 0
scoreboard players set @s ADFYГ 0
scoreboard players set @s ADFYГГГ 0
scoreboard players set @s ADEY 0
scoreboard players set @s ADEYГ 0
scoreboard players set @s ADEYГГГ 0
scoreboard players set @s ADFБX 0
scoreboard players set @s ADFБXK 0
scoreboard players set @s ADFXY 0
scoreboard players set @s ADFXYГ 0
scoreboard players set @s ADFXYГГГ 0
scoreboard players set @s ADFБ 0
scoreboard players set @s ADFБS 0
scoreboard players set @s ADFБM 0
scoreboard players set @s ADFT 0
scoreboard players set @s ADET 0
scoreboard players set @s ADETГ 0
scoreboard players set @s ADETЗ 0
scoreboard players set @s ADETГЗ 0
scoreboard players set @s ADEZ 0
scoreboard players set @s ADEZГ 0
scoreboard players set @s ADEZГГГ 0
scoreboard players set @s ADEZЗ 0
scoreboard players set @s ADEZГЗ 0
scoreboard players set @s ADEZM 0
scoreboard players set @s ADEZMГ 0
scoreboard players set @s ADEZMГГГ 0
scoreboard players set @s ADEZMЗ 0
scoreboard players set @s ADEZMГЗ 0
scoreboard players set @s ADFZ 0
scoreboard players set @s ADFZГ 0
scoreboard players set @s ADFZГГГ 0
scoreboard players set @s ADFZMГ 0
scoreboard players set @s ADFZЗ 0
scoreboard players set @s ADFZГЗ 0
scoreboard players set @s ADFZГГГЗ 0
scoreboard players set @s ADFZЖ 0
scoreboard players set @s ADEN 0
scoreboard players set @s ADENГ 0
scoreboard players set @s ADENГГГ 0
scoreboard players set @s ADFNГ 0
scoreboard players set @s ADFNГГГ 0
scoreboard players set @s ADHXZTUГЖЗ 0
scoreboard players set @s ADFXMД 0
scoreboard players set @s ADFXMГ 0
scoreboard players set @s ADFXMГГ 0
scoreboard players set @s ADFXMГГГ 0
scoreboard players set @s ADIR 0
scoreboard players set @s ADJM 0
scoreboard players set @s ADJMГ 0
scoreboard players set @s ADJ 0
scoreboard players set @s ADJZ 0
scoreboard players set @s ADGЗ 0
scoreboard players set @s ADG 0
scoreboard players set @s ADGД 0
scoreboard players set @s ADGДЗ 0
scoreboard players set @s ADFXP 0
scoreboard players set @s ADFXPГ 0
scoreboard players set @s ADFXPГГГ 0
scoreboard players set @s ADI2 0
scoreboard players set @s ADI2K 0
scoreboard players set @s ADI2M 0
scoreboard players set @s ADI2MK 0
scoreboard players set @s ADIU 0
scoreboard players set @s ADIUЖ 0
scoreboard players set @s ADIUГГГ 0
scoreboard players set @s ADIUГГГЖ 0
scoreboard players set @s ADHZД 0

scoreboard players set @s BAEK 0
scoreboard players set @s BAEKЗ 0
scoreboard players set @s BAEKЖ 0
scoreboard players set @s BAEKЗЖ 0
scoreboard players set @s BAEKЖЗ 0
scoreboard players set @s BAEKГ 0
scoreboard players set @s BAEKГЗ 0
scoreboard players set @s BAEKГГГ 0
scoreboard players set @s BAEKД 0
scoreboard players set @s BAEKДГ 0
scoreboard players set @s BAEKSГГГ 0
scoreboard players set @s BAEL 0
scoreboard players set @s BAELГ 0
scoreboard players set @s BAEWM 0
scoreboard players set @s BAEWMГ 0
scoreboard players set @s BAEWMГГГ 0
scoreboard players set @s BAEW 0
scoreboard players set @s BAEWГ 0
scoreboard players set @s BAEWЗ 0
scoreboard players set @s BAFW 0
scoreboard players set @s BAFWГ 0
scoreboard players set @s BAGЗ 0
scoreboard players set @s BAG 0
scoreboard players set @s BAJ 0
scoreboard players set @s BAE1 0
scoreboard players set @s BAE1Г 0
scoreboard players set @s BAE2 0
scoreboard players set @s BAE2Г 0
scoreboard players set @s BBFV 0
scoreboard players set @s BBFVГ 0
scoreboard players set @s BBEV 0
scoreboard players set @s BBEVГ 0
scoreboard players set @s BBGЗ 0
scoreboard players set @s BBG 0
scoreboard players set @s BBFQ 0
scoreboard players set @s BBFQЗ 0
scoreboard players set @s BBFQЖ 0
scoreboard players set @s BBFQГ 0
scoreboard players set @s BBFQГЗ 0
scoreboard players set @s BBFQГЖ 0
scoreboard players set @s BBFQГГ 0
scoreboard players set @s BBFQГГГ 0
scoreboard players set @s BBFБ 0
scoreboard players set @s BBFБГ 0
scoreboard players set @s BBFБГГГ 0
scoreboard players set @s BBFБZ 0
scoreboard players set @s BBFБZГ 0
scoreboard players set @s BBFБZГГГ 0
scoreboard players set @s BBJ 0
scoreboard players set @s BCFP 0
scoreboard players set @s BCFPГ 0
scoreboard players set @s BCFPГГ 0
scoreboard players set @s BCFPГГГ 0
scoreboard players set @s BCFPM 0
scoreboard players set @s BCFPMГ 0
scoreboard players set @s BCFPMГГГ 0
scoreboard players set @s BCFPMЗ 0
scoreboard players set @s BCFPMГЗ 0
scoreboard players set @s BCFPMГГГЗ 0
scoreboard players set @s BCFPW 0
scoreboard players set @s BCFPWЗ 0
scoreboard players set @s BCFT 0
scoreboard players set @s BCFTЖ 0
scoreboard players set @s BCFTЗ 0
scoreboard players set @s BCFQ 0
scoreboard players set @s BCFQЖ 0
scoreboard players set @s BCFQЗ 0
scoreboard players set @s BCFQГ 0
scoreboard players set @s BCFQГЗ 0
scoreboard players set @s BCFZ 0
scoreboard players set @s BCFZЖ 0
scoreboard players set @s BCFZЗ 0
scoreboard players set @s BCFO 0
scoreboard players set @s BCFOЗ 0
scoreboard players set @s BCFOЖ 0
scoreboard players set @s BCFOГ 0
scoreboard players set @s BCFOГЗ 0
scoreboard players set @s BCFOГЖ 0
scoreboard players set @s BCFOГГГ 0
scoreboard players set @s BCFOГГГЗ 0
scoreboard players set @s BCFOГГГЖ 0
scoreboard players set @s BCFOQГГГ 0
scoreboard players set @s BCFOQГГГЗ 0
scoreboard players set @s BCFS 0
scoreboard players set @s BCJ 0
scoreboard players set @s BCG 0
scoreboard players set @s BCGЗ 0
scoreboard players set @s BCF2 0
scoreboard players set @s BCIU 0
scoreboard players set @s BCIUГ 0
scoreboard players set @s BCFPU 0
scoreboard players set @s BCFPUЖ 0
scoreboard players set @s BCFPUГГГЖ 0
scoreboard players set @s BDITX 0
scoreboard players set @s BDGZЗ 0
scoreboard players set @s BDFM 0
scoreboard players set @s BDFMP 0
scoreboard players set @s BDFPZЖ 0
scoreboard players set @s BDFY 0
scoreboard players set @s BDFYГ 0
scoreboard players set @s BDFYГГГ 0
scoreboard players set @s BDEY 0
scoreboard players set @s BDEYГ 0
scoreboard players set @s BDEYГГГ 0
scoreboard players set @s BDFБX 0
scoreboard players set @s BDFБXK 0
scoreboard players set @s BDFXY 0
scoreboard players set @s BDFXYГ 0
scoreboard players set @s BDFXYГГГ 0
scoreboard players set @s BDFБ 0
scoreboard players set @s BDFБS 0
scoreboard players set @s BDFБM 0
scoreboard players set @s BDFT 0
scoreboard players set @s BDET 0
scoreboard players set @s BDETГ 0
scoreboard players set @s BDETЗ 0
scoreboard players set @s BDETГЗ 0
scoreboard players set @s BDEZ 0
scoreboard players set @s BDEZГ 0
scoreboard players set @s BDEZГГГ 0
scoreboard players set @s BDEZЗ 0
scoreboard players set @s BDEZГЗ 0
scoreboard players set @s BDEZM 0
scoreboard players set @s BDEZMГ 0
scoreboard players set @s BDEZMГГГ 0
scoreboard players set @s BDEZMЗ 0
scoreboard players set @s BDEZMГЗ 0
scoreboard players set @s BDFZ 0
scoreboard players set @s BDFZГ 0
scoreboard players set @s BDFZГГГ 0
scoreboard players set @s BDFZMГ 0
scoreboard players set @s BDFZЗ 0
scoreboard players set @s BDFZГЗ 0
scoreboard players set @s BDFZГГГЗ 0
scoreboard players set @s BDFZЖ 0
scoreboard players set @s BDEN 0
scoreboard players set @s BDENГ 0
scoreboard players set @s BDENГГГ 0
scoreboard players set @s BDFNГ 0
scoreboard players set @s BDFNГГГ 0
scoreboard players set @s BDHXZTUГЖЗ 0
scoreboard players set @s BDFXMД 0
scoreboard players set @s BDFXMГ 0
scoreboard players set @s BDFXMГГ 0
scoreboard players set @s BDFXMГГГ 0
scoreboard players set @s BDIR 0
scoreboard players set @s BDJM 0
scoreboard players set @s BDJMГ 0
scoreboard players set @s BDJ 0
scoreboard players set @s BDJZ 0
scoreboard players set @s BDGЗ 0
scoreboard players set @s BDG 0
scoreboard players set @s BDGД 0
scoreboard players set @s BDGДЗ 0
scoreboard players set @s BDFXP 0
scoreboard players set @s BDFXPГ 0
scoreboard players set @s BDFXPГГГ 0
scoreboard players set @s BDI2 0
scoreboard players set @s BDI2K 0
scoreboard players set @s BDI2M 0
scoreboard players set @s BDI2MK 0
scoreboard players set @s BDIU 0
scoreboard players set @s BDIUЖ 0
scoreboard players set @s BDIUГГГ 0
scoreboard players set @s BDIUГГГЖ 0
scoreboard players set @s BDHZД 0

scoreboard players set @s CAEK 0
scoreboard players set @s CAEKЗ 0
scoreboard players set @s CAEKЖ 0
scoreboard players set @s CAEKЗЖ 0
scoreboard players set @s CAEKЖЗ 0
scoreboard players set @s CAEKГ 0
scoreboard players set @s CAEKГЗ 0
scoreboard players set @s CAEKГГГ 0
scoreboard players set @s CAEKД 0
scoreboard players set @s CAEKДГ 0
scoreboard players set @s CAEKSГГГ 0
scoreboard players set @s CAEL 0
scoreboard players set @s CAELГ 0
scoreboard players set @s CAEWM 0
scoreboard players set @s CAEWMГ 0
scoreboard players set @s CAEWMГГГ 0
scoreboard players set @s CAEW 0
scoreboard players set @s CAEWГ 0
scoreboard players set @s CAEWЗ 0
scoreboard players set @s CAFW 0
scoreboard players set @s CAFWГ 0
scoreboard players set @s CAGЗ 0
scoreboard players set @s CAG 0
scoreboard players set @s CAJ 0
scoreboard players set @s CAE1 0
scoreboard players set @s CAE1Г 0
scoreboard players set @s CAE2 0
scoreboard players set @s CAE2Г 0
scoreboard players set @s CBFV 0
scoreboard players set @s CBFVГ 0
scoreboard players set @s CBEV 0
scoreboard players set @s CBEVГ 0
scoreboard players set @s CBGЗ 0
scoreboard players set @s CBG 0
scoreboard players set @s CBFQ 0
scoreboard players set @s CBFQЗ 0
scoreboard players set @s CBFQЖ 0
scoreboard players set @s CBFQГ 0
scoreboard players set @s CBFQГЗ 0
scoreboard players set @s CBFQГЖ 0
scoreboard players set @s CBFQГГ 0
scoreboard players set @s CBFQГГГ 0
scoreboard players set @s CBFБ 0
scoreboard players set @s CBFБГ 0
scoreboard players set @s CBFБГГГ 0
scoreboard players set @s CBFБZ 0
scoreboard players set @s CBFБZГ 0
scoreboard players set @s CBFБZГГГ 0
scoreboard players set @s CBJ 0
scoreboard players set @s CCFP 0
scoreboard players set @s CCFPГ 0
scoreboard players set @s CCFPГГ 0
scoreboard players set @s CCFPГГГ 0
scoreboard players set @s CCFPM 0
scoreboard players set @s CCFPMГ 0
scoreboard players set @s CCFPMГГГ 0
scoreboard players set @s CCFPMЗ 0
scoreboard players set @s CCFPMГЗ 0
scoreboard players set @s CCFPMГГГЗ 0
scoreboard players set @s CCFPW 0
scoreboard players set @s CCFPWЗ 0
scoreboard players set @s CCFT 0
scoreboard players set @s CCFTЖ 0
scoreboard players set @s CCFTЗ 0
scoreboard players set @s CCFQ 0
scoreboard players set @s CCFQЖ 0
scoreboard players set @s CCFQЗ 0
scoreboard players set @s CCFQГ 0
scoreboard players set @s CCFQГЗ 0
scoreboard players set @s CCFZ 0
scoreboard players set @s CCFZЖ 0
scoreboard players set @s CCFZЗ 0
scoreboard players set @s CCFO 0
scoreboard players set @s CCFOЗ 0
scoreboard players set @s CCFOЖ 0
scoreboard players set @s CCFOГ 0
scoreboard players set @s CCFOГЗ 0
scoreboard players set @s CCFOГЖ 0
scoreboard players set @s CCFOГГГ 0
scoreboard players set @s CCFOГГГЗ 0
scoreboard players set @s CCFOГГГЖ 0
scoreboard players set @s CCFOQГГГ 0
scoreboard players set @s CCFOQГГГЗ 0
scoreboard players set @s CCFS 0
scoreboard players set @s CCJ 0
scoreboard players set @s CCG 0
scoreboard players set @s CCGЗ 0
scoreboard players set @s CCF2 0
scoreboard players set @s CCIU 0
scoreboard players set @s CCIUГ 0
scoreboard players set @s CCFPU 0
scoreboard players set @s CCFPUЖ 0
scoreboard players set @s CCFPUГГГЖ 0
scoreboard players set @s CDITX 0
scoreboard players set @s CDGZЗ 0
scoreboard players set @s CDFM 0
scoreboard players set @s CDFMP 0
scoreboard players set @s CDFPZЖ 0
scoreboard players set @s CDFY 0
scoreboard players set @s CDFYГ 0
scoreboard players set @s CDFYГГГ 0
scoreboard players set @s CDEY 0
scoreboard players set @s CDEYГ 0
scoreboard players set @s CDEYГГГ 0
scoreboard players set @s CDFБX 0
scoreboard players set @s CDFБXK 0
scoreboard players set @s CDFXY 0
scoreboard players set @s CDFXYГ 0
scoreboard players set @s CDFXYГГГ 0
scoreboard players set @s CDFБ 0
scoreboard players set @s CDFБS 0
scoreboard players set @s CDFБM 0
scoreboard players set @s CDFT 0
scoreboard players set @s CDET 0
scoreboard players set @s CDETГ 0
scoreboard players set @s CDETЗ 0
scoreboard players set @s CDETГЗ 0
scoreboard players set @s CDEZ 0
scoreboard players set @s CDEZГ 0
scoreboard players set @s CDEZГГГ 0
scoreboard players set @s CDEZЗ 0
scoreboard players set @s CDEZГЗ 0
scoreboard players set @s CDEZM 0
scoreboard players set @s CDEZMГ 0
scoreboard players set @s CDEZMГГГ 0
scoreboard players set @s CDEZMЗ 0
scoreboard players set @s CDEZMГЗ 0
scoreboard players set @s CDFZ 0
scoreboard players set @s CDFZГ 0
scoreboard players set @s CDFZГГГ 0
scoreboard players set @s CDFZMГ 0
scoreboard players set @s CDFZЗ 0
scoreboard players set @s CDFZГЗ 0
scoreboard players set @s CDFZГГГЗ 0
scoreboard players set @s CDFZЖ 0
scoreboard players set @s CDEN 0
scoreboard players set @s CDENГ 0
scoreboard players set @s CDENГГГ 0
scoreboard players set @s CDFNГ 0
scoreboard players set @s CDFNГГГ 0
scoreboard players set @s CDHXZTUГЖЗ 0
scoreboard players set @s CDFXMД 0
scoreboard players set @s CDFXMГ 0
scoreboard players set @s CDFXMГГ 0
scoreboard players set @s CDFXMГГГ 0
scoreboard players set @s CDIR 0
scoreboard players set @s CDJM 0
scoreboard players set @s CDJMГ 0
scoreboard players set @s CDJ 0
scoreboard players set @s CDJZ 0
scoreboard players set @s CDGЗ 0
scoreboard players set @s CDG 0
scoreboard players set @s CDGД 0
scoreboard players set @s CDGДЗ 0
scoreboard players set @s CDFXP 0
scoreboard players set @s CDFXPГ 0
scoreboard players set @s CDFXPГГГ 0
scoreboard players set @s CDI2 0
scoreboard players set @s CDI2K 0
scoreboard players set @s CDI2M 0
scoreboard players set @s CDI2MK 0
scoreboard players set @s CDIU 0
scoreboard players set @s CDIUЖ 0
scoreboard players set @s CDIUГГГ 0
scoreboard players set @s CDIUГГГЖ 0
scoreboard players set @s CDHZД 0

scoreboard players set @s DAEK 0
scoreboard players set @s DAEKЗ 0
scoreboard players set @s DAEKЖ 0
scoreboard players set @s DAEKЗЖ 0
scoreboard players set @s DAEKЖЗ 0
scoreboard players set @s DAEKГ 0
scoreboard players set @s DAEKГЗ 0
scoreboard players set @s DAEKГГГ 0
scoreboard players set @s DAEKД 0
scoreboard players set @s DAEKДГ 0
scoreboard players set @s DAEKSГГГ 0
scoreboard players set @s DAEL 0
scoreboard players set @s DAELГ 0
scoreboard players set @s DAEWM 0
scoreboard players set @s DAEWMГ 0
scoreboard players set @s DAEWMГГГ 0
scoreboard players set @s DAEW 0
scoreboard players set @s DAEWГ 0
scoreboard players set @s DAEWЗ 0
scoreboard players set @s DAFW 0
scoreboard players set @s DAFWГ 0
scoreboard players set @s DAGЗ 0
scoreboard players set @s DAG 0
scoreboard players set @s DAJ 0
scoreboard players set @s DAE1 0
scoreboard players set @s DAE1Г 0
scoreboard players set @s DAE2 0
scoreboard players set @s DAE2Г 0
scoreboard players set @s DBFV 0
scoreboard players set @s DBFVГ 0
scoreboard players set @s DBEV 0
scoreboard players set @s DBEVГ 0
scoreboard players set @s DBGЗ 0
scoreboard players set @s DBG 0
scoreboard players set @s DBFQ 0
scoreboard players set @s DBFQЗ 0
scoreboard players set @s DBFQЖ 0
scoreboard players set @s DBFQГ 0
scoreboard players set @s DBFQГЗ 0
scoreboard players set @s DBFQГЖ 0
scoreboard players set @s DBFQГГ 0
scoreboard players set @s DBFQГГГ 0
scoreboard players set @s DBFБ 0
scoreboard players set @s DBFБГ 0
scoreboard players set @s DBFБГГГ 0
scoreboard players set @s DBFБZ 0
scoreboard players set @s DBFБZГ 0
scoreboard players set @s DBFБZГГГ 0
scoreboard players set @s DBJ 0
scoreboard players set @s DCFP 0
scoreboard players set @s DCFPГ 0
scoreboard players set @s DCFPГГ 0
scoreboard players set @s DCFPГГГ 0
scoreboard players set @s DCFPM 0
scoreboard players set @s DCFPMГ 0
scoreboard players set @s DCFPMГГГ 0
scoreboard players set @s DCFPMЗ 0
scoreboard players set @s DCFPMГЗ 0
scoreboard players set @s DCFPMГГГЗ 0
scoreboard players set @s DCFPW 0
scoreboard players set @s DCFPWЗ 0
scoreboard players set @s DCFT 0
scoreboard players set @s DCFTЖ 0
scoreboard players set @s DCFTЗ 0
scoreboard players set @s DCFQ 0
scoreboard players set @s DCFQЖ 0
scoreboard players set @s DCFQЗ 0
scoreboard players set @s DCFQГ 0
scoreboard players set @s DCFQГЗ 0
scoreboard players set @s DCFZ 0
scoreboard players set @s DCFZЖ 0
scoreboard players set @s DCFZЗ 0
scoreboard players set @s DCFO 0
scoreboard players set @s DCFOЗ 0
scoreboard players set @s DCFOЖ 0
scoreboard players set @s DCFOГ 0
scoreboard players set @s DCFOГЗ 0
scoreboard players set @s DCFOГЖ 0
scoreboard players set @s DCFOГГГ 0
scoreboard players set @s DCFOГГГЗ 0
scoreboard players set @s DCFOГГГЖ 0
scoreboard players set @s DCFOQГГГ 0
scoreboard players set @s DCFOQГГГЗ 0
scoreboard players set @s DCFS 0
scoreboard players set @s DCJ 0
scoreboard players set @s DCG 0
scoreboard players set @s DCGЗ 0
scoreboard players set @s DCF2 0
scoreboard players set @s DCIU 0
scoreboard players set @s DCIUГ 0
scoreboard players set @s DCFPU 0
scoreboard players set @s DCFPUЖ 0
scoreboard players set @s DCFPUГГГЖ 0
scoreboard players set @s DDITX 0
scoreboard players set @s DDGZЗ 0
scoreboard players set @s DDFM 0
scoreboard players set @s DDFMP 0
scoreboard players set @s DDFPZЖ 0
scoreboard players set @s DDFY 0
scoreboard players set @s DDFYГ 0
scoreboard players set @s DDFYГГГ 0
scoreboard players set @s DDEY 0
scoreboard players set @s DDEYГ 0
scoreboard players set @s DDEYГГГ 0
scoreboard players set @s DDFБX 0
scoreboard players set @s DDFБXK 0
scoreboard players set @s DDFXY 0
scoreboard players set @s DDFXYГ 0
scoreboard players set @s DDFXYГГГ 0
scoreboard players set @s DDFБ 0
scoreboard players set @s DDFБS 0
scoreboard players set @s DDFБM 0
scoreboard players set @s DDFT 0
scoreboard players set @s DDET 0
scoreboard players set @s DDETГ 0
scoreboard players set @s DDETЗ 0
scoreboard players set @s DDETГЗ 0
scoreboard players set @s DDEZ 0
scoreboard players set @s DDEZГ 0
scoreboard players set @s DDEZГГГ 0
scoreboard players set @s DDEZЗ 0
scoreboard players set @s DDEZГЗ 0
scoreboard players set @s DDEZM 0
scoreboard players set @s DDEZMГ 0
scoreboard players set @s DDEZMГГГ 0
scoreboard players set @s DDEZMЗ 0
scoreboard players set @s DDEZMГЗ 0
scoreboard players set @s DDFZ 0
scoreboard players set @s DDFZГ 0
scoreboard players set @s DDFZГГГ 0
scoreboard players set @s DDFZMГ 0
scoreboard players set @s DDFZЗ 0
scoreboard players set @s DDFZГЗ 0
scoreboard players set @s DDFZГГГЗ 0
scoreboard players set @s DDFZЖ 0
scoreboard players set @s DDEN 0
scoreboard players set @s DDENГ 0
scoreboard players set @s DDENГГГ 0
scoreboard players set @s DDFNГ 0
scoreboard players set @s DDFNГГГ 0
scoreboard players set @s DDHXZTUГЖЗ 0
scoreboard players set @s DDFXMД 0
scoreboard players set @s DDFXMГ 0
scoreboard players set @s DDFXMГГ 0
scoreboard players set @s DDFXMГГГ 0
scoreboard players set @s DDIR 0
scoreboard players set @s DDJM 0
scoreboard players set @s DDJMГ 0
scoreboard players set @s DDJ 0
scoreboard players set @s DDJZ 0
scoreboard players set @s DDGЗ 0
scoreboard players set @s DDG 0
scoreboard players set @s DDGД 0
scoreboard players set @s DDGДЗ 0
scoreboard players set @s DDFXP 0
scoreboard players set @s DDFXPГ 0
scoreboard players set @s DDFXPГГГ 0
scoreboard players set @s DDI2 0
scoreboard players set @s DDI2K 0
scoreboard players set @s DDI2M 0
scoreboard players set @s DDI2MK 0
scoreboard players set @s DDIU 0
scoreboard players set @s DDIUЖ 0
scoreboard players set @s DDIUГГГ 0
scoreboard players set @s DDIUГГГЖ 0
scoreboard players set @s DDHZД 0

scoreboard players set @s EAEK 0
scoreboard players set @s EAEKЗ 0
scoreboard players set @s EAEKЖ 0
scoreboard players set @s EAEKЗЖ 0
scoreboard players set @s EAEKЖЗ 0
scoreboard players set @s EAEKГ 0
scoreboard players set @s EAEKГЗ 0
scoreboard players set @s EAEKГГГ 0
scoreboard players set @s EAEKД 0
scoreboard players set @s EAEKДГ 0
scoreboard players set @s EAEKSГГГ 0
scoreboard players set @s EAEL 0
scoreboard players set @s EAELГ 0
scoreboard players set @s EAEWM 0
scoreboard players set @s EAEWMГ 0
scoreboard players set @s EAEWMГГГ 0
scoreboard players set @s EAEW 0
scoreboard players set @s EAEWГ 0
scoreboard players set @s EAEWЗ 0
scoreboard players set @s EAFW 0
scoreboard players set @s EAFWГ 0
scoreboard players set @s EAGЗ 0
scoreboard players set @s EAG 0
scoreboard players set @s EAJ 0
scoreboard players set @s EAE1 0
scoreboard players set @s EAE1Г 0
scoreboard players set @s EAE2 0
scoreboard players set @s EAE2Г 0
scoreboard players set @s EBFV 0
scoreboard players set @s EBFVГ 0
scoreboard players set @s EBEV 0
scoreboard players set @s EBEVГ 0
scoreboard players set @s EBGЗ 0
scoreboard players set @s EBG 0
scoreboard players set @s EBFQ 0
scoreboard players set @s EBFQЗ 0
scoreboard players set @s EBFQЖ 0
scoreboard players set @s EBFQГ 0
scoreboard players set @s EBFQГЗ 0
scoreboard players set @s EBFQГЖ 0
scoreboard players set @s EBFQГГ 0
scoreboard players set @s EBFQГГГ 0
scoreboard players set @s EBFБ 0
scoreboard players set @s EBFБГ 0
scoreboard players set @s EBFБГГГ 0
scoreboard players set @s EBFБZ 0
scoreboard players set @s EBFБZГ 0
scoreboard players set @s EBFБZГГГ 0
scoreboard players set @s EBJ 0
scoreboard players set @s ECFP 0
scoreboard players set @s ECFPГ 0
scoreboard players set @s ECFPГГ 0
scoreboard players set @s ECFPГГГ 0
scoreboard players set @s ECFPM 0
scoreboard players set @s ECFPMГ 0
scoreboard players set @s ECFPMГГГ 0
scoreboard players set @s ECFPMЗ 0
scoreboard players set @s ECFPMГЗ 0
scoreboard players set @s ECFPMГГГЗ 0
scoreboard players set @s ECFPW 0
scoreboard players set @s ECFPWЗ 0
scoreboard players set @s ECFT 0
scoreboard players set @s ECFTЖ 0
scoreboard players set @s ECFTЗ 0
scoreboard players set @s ECFQ 0
scoreboard players set @s ECFQЖ 0
scoreboard players set @s ECFQЗ 0
scoreboard players set @s ECFQГ 0
scoreboard players set @s ECFQГЗ 0
scoreboard players set @s ECFZ 0
scoreboard players set @s ECFZЖ 0
scoreboard players set @s ECFZЗ 0
scoreboard players set @s ECFO 0
scoreboard players set @s ECFOЗ 0
scoreboard players set @s ECFOЖ 0
scoreboard players set @s ECFOГ 0
scoreboard players set @s ECFOГЗ 0
scoreboard players set @s ECFOГЖ 0
scoreboard players set @s ECFOГГГ 0
scoreboard players set @s ECFOГГГЗ 0
scoreboard players set @s ECFOГГГЖ 0
scoreboard players set @s ECFOQГГГ 0
scoreboard players set @s ECFOQГГГЗ 0
scoreboard players set @s ECFS 0
scoreboard players set @s ECJ 0
scoreboard players set @s ECG 0
scoreboard players set @s ECGЗ 0
scoreboard players set @s ECF2 0
scoreboard players set @s ECIU 0
scoreboard players set @s ECIUГ 0
scoreboard players set @s ECFPU 0
scoreboard players set @s ECFPUЖ 0
scoreboard players set @s ECFPUГГГЖ 0
scoreboard players set @s EDITX 0
scoreboard players set @s EDGZЗ 0
scoreboard players set @s EDFM 0
scoreboard players set @s EDFMP 0
scoreboard players set @s EDFPZЖ 0
scoreboard players set @s EDFY 0
scoreboard players set @s EDFYГ 0
scoreboard players set @s EDFYГГГ 0
scoreboard players set @s EDEY 0
scoreboard players set @s EDEYГ 0
scoreboard players set @s EDEYГГГ 0
scoreboard players set @s EDFБX 0
scoreboard players set @s EDFБXK 0
scoreboard players set @s EDFXY 0
scoreboard players set @s EDFXYГ 0
scoreboard players set @s EDFXYГГГ 0
scoreboard players set @s EDFБ 0
scoreboard players set @s EDFБS 0
scoreboard players set @s EDFБM 0
scoreboard players set @s EDFT 0
scoreboard players set @s EDET 0
scoreboard players set @s EDETГ 0
scoreboard players set @s EDETЗ 0
scoreboard players set @s EDETГЗ 0
scoreboard players set @s EDEZ 0
scoreboard players set @s EDEZГ 0
scoreboard players set @s EDEZГГГ 0
scoreboard players set @s EDEZЗ 0
scoreboard players set @s EDEZГЗ 0
scoreboard players set @s EDEZM 0
scoreboard players set @s EDEZMГ 0
scoreboard players set @s EDEZMГГГ 0
scoreboard players set @s EDEZMЗ 0
scoreboard players set @s EDEZMГЗ 0
scoreboard players set @s EDFZ 0
scoreboard players set @s EDFZГ 0
scoreboard players set @s EDFZГГГ 0
scoreboard players set @s EDFZMГ 0
scoreboard players set @s EDFZЗ 0
scoreboard players set @s EDFZГЗ 0
scoreboard players set @s EDFZГГГЗ 0
scoreboard players set @s EDFZЖ 0
scoreboard players set @s EDEN 0
scoreboard players set @s EDENГ 0
scoreboard players set @s EDENГГГ 0
scoreboard players set @s EDFNГ 0
scoreboard players set @s EDFNГГГ 0
scoreboard players set @s EDHXZTUГЖЗ 0
scoreboard players set @s EDFXMД 0
scoreboard players set @s EDFXMГ 0
scoreboard players set @s EDFXMГГ 0
scoreboard players set @s EDFXMГГГ 0
scoreboard players set @s EDIR 0
scoreboard players set @s EDJM 0
scoreboard players set @s EDJMГ 0
scoreboard players set @s EDJ 0
scoreboard players set @s EDJZ 0
scoreboard players set @s EDGЗ 0
scoreboard players set @s EDG 0
scoreboard players set @s EDGД 0
scoreboard players set @s EDGДЗ 0
scoreboard players set @s EDFXP 0
scoreboard players set @s EDFXPГ 0
scoreboard players set @s EDFXPГГГ 0
scoreboard players set @s EDI2 0
scoreboard players set @s EDI2K 0
scoreboard players set @s EDI2M 0
scoreboard players set @s EDI2MK 0
scoreboard players set @s EDIU 0
scoreboard players set @s EDIUЖ 0
scoreboard players set @s EDIUГГГ 0
scoreboard players set @s EDIUГГГЖ 0
scoreboard players set @s EDHZД 0

scoreboard players set @s FAEK 0
scoreboard players set @s FAEKЗ 0
scoreboard players set @s FAEKЖ 0
scoreboard players set @s FAEKЗЖ 0
scoreboard players set @s FAEKЖЗ 0
scoreboard players set @s FAEKГ 0
scoreboard players set @s FAEKГЗ 0
scoreboard players set @s FAEKГГГ 0
scoreboard players set @s FAEKД 0
scoreboard players set @s FAEKДГ 0
scoreboard players set @s FAEKSГГГ 0
scoreboard players set @s FAEL 0
scoreboard players set @s FAELГ 0
scoreboard players set @s FAEWM 0
scoreboard players set @s FAEWMГ 0
scoreboard players set @s FAEWMГГГ 0
scoreboard players set @s FAEW 0
scoreboard players set @s FAEWГ 0
scoreboard players set @s FAEWЗ 0
scoreboard players set @s FAFW 0
scoreboard players set @s FAFWГ 0
scoreboard players set @s FAGЗ 0
scoreboard players set @s FAG 0
scoreboard players set @s FAJ 0
scoreboard players set @s FAE1 0
scoreboard players set @s FAE1Г 0
scoreboard players set @s FAE2 0
scoreboard players set @s FAE2Г 0
scoreboard players set @s FBFV 0
scoreboard players set @s FBFVГ 0
scoreboard players set @s FBEV 0
scoreboard players set @s FBEVГ 0
scoreboard players set @s FBGЗ 0
scoreboard players set @s FBG 0
scoreboard players set @s FBFQ 0
scoreboard players set @s FBFQЗ 0
scoreboard players set @s FBFQЖ 0
scoreboard players set @s FBFQГ 0
scoreboard players set @s FBFQГЗ 0
scoreboard players set @s FBFQГЖ 0
scoreboard players set @s FBFQГГ 0
scoreboard players set @s FBFQГГГ 0
scoreboard players set @s FBFБ 0
scoreboard players set @s FBFБГ 0
scoreboard players set @s FBFБГГГ 0
scoreboard players set @s FBFБZ 0
scoreboard players set @s FBFБZГ 0
scoreboard players set @s FBFБZГГГ 0
scoreboard players set @s FBJ 0
scoreboard players set @s FCFP 0
scoreboard players set @s FCFPГ 0
scoreboard players set @s FCFPГГ 0
scoreboard players set @s FCFPГГГ 0
scoreboard players set @s FCFPM 0
scoreboard players set @s FCFPMГ 0
scoreboard players set @s FCFPMГГГ 0
scoreboard players set @s FCFPMЗ 0
scoreboard players set @s FCFPMГЗ 0
scoreboard players set @s FCFPMГГГЗ 0
scoreboard players set @s FCFPW 0
scoreboard players set @s FCFPWЗ 0
scoreboard players set @s FCFT 0
scoreboard players set @s FCFTЖ 0
scoreboard players set @s FCFTЗ 0
scoreboard players set @s FCFQ 0
scoreboard players set @s FCFQЖ 0
scoreboard players set @s FCFQЗ 0
scoreboard players set @s FCFQГ 0
scoreboard players set @s FCFQГЗ 0
scoreboard players set @s FCFZ 0
scoreboard players set @s FCFZЖ 0
scoreboard players set @s FCFZЗ 0
scoreboard players set @s FCFO 0
scoreboard players set @s FCFOЗ 0
scoreboard players set @s FCFOЖ 0
scoreboard players set @s FCFOГ 0
scoreboard players set @s FCFOГЗ 0
scoreboard players set @s FCFOГЖ 0
scoreboard players set @s FCFOГГГ 0
scoreboard players set @s FCFOГГГЗ 0
scoreboard players set @s FCFOГГГЖ 0
scoreboard players set @s FCFOQГГГ 0
scoreboard players set @s FCFOQГГГЗ 0
scoreboard players set @s FCFS 0
scoreboard players set @s FCJ 0
scoreboard players set @s FCG 0
scoreboard players set @s FCGЗ 0
scoreboard players set @s FCF2 0
scoreboard players set @s FCIU 0
scoreboard players set @s FCIUГ 0
scoreboard players set @s FCFPU 0
scoreboard players set @s FCFPUЖ 0
scoreboard players set @s FCFPUГГГЖ 0
scoreboard players set @s FDITX 0
scoreboard players set @s FDGZЗ 0
scoreboard players set @s FDFM 0
scoreboard players set @s FDFMP 0
scoreboard players set @s FDFPZЖ 0
scoreboard players set @s FDFY 0
scoreboard players set @s FDFYГ 0
scoreboard players set @s FDFYГГГ 0
scoreboard players set @s FDEY 0
scoreboard players set @s FDEYГ 0
scoreboard players set @s FDEYГГГ 0
scoreboard players set @s FDFБX 0
scoreboard players set @s FDFБXK 0
scoreboard players set @s FDFXY 0
scoreboard players set @s FDFXYГ 0
scoreboard players set @s FDFXYГГГ 0
scoreboard players set @s FDFБ 0
scoreboard players set @s FDFБS 0
scoreboard players set @s FDFБM 0
scoreboard players set @s FDFT 0
scoreboard players set @s FDET 0
scoreboard players set @s FDETГ 0
scoreboard players set @s FDETЗ 0
scoreboard players set @s FDETГЗ 0
scoreboard players set @s FDEZ 0
scoreboard players set @s FDEZГ 0
scoreboard players set @s FDEZГГГ 0
scoreboard players set @s FDEZЗ 0
scoreboard players set @s FDEZГЗ 0
scoreboard players set @s FDEZM 0
scoreboard players set @s FDEZMГ 0
scoreboard players set @s FDEZMГГГ 0
scoreboard players set @s FDEZMЗ 0
scoreboard players set @s FDEZMГЗ 0
scoreboard players set @s FDFZ 0
scoreboard players set @s FDFZГ 0
scoreboard players set @s FDFZГГГ 0
scoreboard players set @s FDFZMГ 0
scoreboard players set @s FDFZЗ 0
scoreboard players set @s FDFZГЗ 0
scoreboard players set @s FDFZГГГЗ 0
scoreboard players set @s FDFZЖ 0
scoreboard players set @s FDEN 0
scoreboard players set @s FDENГ 0
scoreboard players set @s FDENГГГ 0
scoreboard players set @s FDFNГ 0
scoreboard players set @s FDFNГГГ 0
scoreboard players set @s FDHXZTUГЖЗ 0
scoreboard players set @s FDFXMД 0
scoreboard players set @s FDFXMГ 0
scoreboard players set @s FDFXMГГ 0
scoreboard players set @s FDFXMГГГ 0
scoreboard players set @s FDIR 0
scoreboard players set @s FDJM 0
scoreboard players set @s FDJMГ 0
scoreboard players set @s FDJ 0
scoreboard players set @s FDJZ 0
scoreboard players set @s FDGЗ 0
scoreboard players set @s FDG 0
scoreboard players set @s FDGД 0
scoreboard players set @s FDGДЗ 0
scoreboard players set @s FDFXP 0
scoreboard players set @s FDFXPГ 0
scoreboard players set @s FDFXPГГГ 0
scoreboard players set @s FDI2 0
scoreboard players set @s FDI2K 0
scoreboard players set @s FDI2M 0
scoreboard players set @s FDI2MK 0
scoreboard players set @s FDIU 0
scoreboard players set @s FDIUЖ 0
scoreboard players set @s FDIUГГГ 0
scoreboard players set @s FDIUГГГЖ 0
scoreboard players set @s FDHZД 0

