scoreboard players set @s ach_in_space 0
scoreboard players set @s ach_in_hot_mines 0
scoreboard players set @s ach_coldy 0
scoreboard players set @s ach_warm 0
scoreboard players set @s ach_die 0
scoreboard players set @s ach_three_roads 0
scoreboard players set @s ach_1k_blocks_walked 0
scoreboard players set @s ach_10k_blocks_walked 0
scoreboard players set @s ach_100k_blocks_walked 0
scoreboard players set @s ach_1m_blocks_walked 0
scoreboard players set @s ach_10m_blocks_walked 0
scoreboard players set @s ach_has_diamond 0
scoreboard players set @s ach_has_fool_potion 0
scoreboard players set @s ach_has_crafting_table 0
scoreboard players set @s ach_has_evergreen_dream 0
scoreboard players set @s ach_has_royal_sorrel 0
scoreboard players set @s ach_has_ice_iris 0
scoreboard players set @s ach_has_ash_lavaflower 0
scoreboard players set @s ach_has_aluminum_ingot 0
scoreboard players set @s ach_has_tin_ingot 0
scoreboard players set @s ach_has_iron_ingot 0
scoreboard players set @s ach_has_riolik_ingot 0
scoreboard players set @s ach_has_altaite_ingot 0
scoreboard players set @s ach_has_caryite_ingot 0
scoreboard players set @s ach_has_chloronite_ingot 0
scoreboard players set @s ach_has_dorionite_ingot 0
scoreboard players set @s ach_has_draphorite_ingot 0
scoreboard players set @s ach_has_forfactorite_ingot 0
scoreboard players set @s ach_has_lamenite_ingot 0
scoreboard players set @s ach_has_naginitis_ingot 0
scoreboard players set @s ach_has_malafiotironite_ingot 0
scoreboard players set @s ach_has_toliriite_ingot 0
scoreboard players set @s ach_has_wooden_pickaxe 0
scoreboard players set @s ach_has_stone_pickaxe 0
scoreboard players set @s ach_has_iron_pickaxe 0
scoreboard players set @s ach_has_diamond_pickaxe 0
scoreboard players set @s ach_has_netherite_pickaxe 0
scoreboard players set @s ach_kill_sand_elemental 0
scoreboard players set @s ach_kill_rat_monster 0
scoreboard players set @s ach_kill_swamp_monster 0
scoreboard players set @s ach_kill_snow_lady 0
scoreboard players set @s ach_1_kills 0
scoreboard players set @s ach_10_kills 0
scoreboard players set @s ach_100_kills 0
scoreboard players set @s ach_1000_kills 0
scoreboard players set @s ach_10000_kills 0
