scoreboard players set @s sk_a_1 0
scoreboard players set @s sk_a_2 0
scoreboard players set @s sk_a_3 0
scoreboard players set @s sk_a_4 0
scoreboard players set @s sk_a_5 0
scoreboard players set @s sk_a_6 0
scoreboard players set @s sk_a_7 0
scoreboard players set @s sk_a_8 0
scoreboard players set @s sk_a_9 0
scoreboard players set @s sk_a_10 0
scoreboard players set @s sk_a_11 0
scoreboard players set @s sk_a_12 0
scoreboard players set @s sk_a_13 0
scoreboard players set @s sk_a_14 0
scoreboard players set @s sk_a_15 0
scoreboard players set @s sk_a_16 0
scoreboard players set @s sk_a_17 0
scoreboard players set @s sk_a_18 0
scoreboard players set @s sk_a_19 0
scoreboard players set @s sk_a_20 0
scoreboard players set @s sk_a_21 0
scoreboard players set @s sk_a_22 0
scoreboard players set @s sk_a_23 0
scoreboard players set @s sk_a_24 0
scoreboard players set @s sk_a_25 0
scoreboard players set @s sk_a_26 0
scoreboard players set @s sk_a_27 0
scoreboard players set @s sk_a_28 0
scoreboard players set @s sk_a_29 0

scoreboard players set @s sk_b_1 0
scoreboard players set @s sk_b_2 0
scoreboard players set @s sk_b_3 0
scoreboard players set @s sk_b_4 0
scoreboard players set @s sk_b_5 0
scoreboard players set @s sk_b_6 0
scoreboard players set @s sk_b_7 0
scoreboard players set @s sk_b_8 0
scoreboard players set @s sk_b_9 0
scoreboard players set @s sk_b_10 0
scoreboard players set @s sk_b_11 0
scoreboard players set @s sk_b_12 0
scoreboard players set @s sk_b_13 0
scoreboard players set @s sk_b_14 0

scoreboard players set @s sk_c_1 0
scoreboard players set @s sk_c_2 0
scoreboard players set @s sk_c_3 0
scoreboard players set @s sk_c_4 0
scoreboard players set @s sk_c_5 0
scoreboard players set @s sk_c_6 0
scoreboard players set @s sk_c_7 0
scoreboard players set @s sk_c_8 0
scoreboard players set @s sk_c_9 0
scoreboard players set @s sk_c_10 0
scoreboard players set @s sk_c_11 0
scoreboard players set @s sk_c_12 0
scoreboard players set @s sk_c_13 0
scoreboard players set @s sk_c_14 0
scoreboard players set @s sk_c_15 0

scoreboard players set @s sk_d_1 0
scoreboard players set @s sk_d_2 0
scoreboard players set @s sk_d_3 0
scoreboard players set @s sk_d_4 0