scoreboard players add @a AAEK 0
scoreboard players add @a AAEKЗ 0
scoreboard players add @a AAEKЖ 0
scoreboard players add @a AAEKЗЖ 0
scoreboard players add @a AAEKЖЗ 0
scoreboard players add @a AAEKГ 0
scoreboard players add @a AAEKГЗ 0
scoreboard players add @a AAEKГГГ 0
scoreboard players add @a AAEKД 0
scoreboard players add @a AAEKДГ 0
scoreboard players add @a AAEKSГГГ 0
scoreboard players add @a AAEL 0
scoreboard players add @a AAELГ 0
scoreboard players add @a AAEWM 0
scoreboard players add @a AAEWMГ 0
scoreboard players add @a AAEWMГГГ 0
scoreboard players add @a AAEW 0
scoreboard players add @a AAEWГ 0
scoreboard players add @a AAEWЗ 0
scoreboard players add @a AAFW 0
scoreboard players add @a AAFWГ 0
scoreboard players add @a AAGЗ 0
scoreboard players add @a AAG 0
scoreboard players add @a AAJ 0
scoreboard players add @a AAE1 0
scoreboard players add @a AAE1Г 0
scoreboard players add @a AAE2 0
scoreboard players add @a AAE2Г 0
scoreboard players add @a ABFV 0
scoreboard players add @a ABFVГ 0
scoreboard players add @a ABEV 0
scoreboard players add @a ABEVГ 0
scoreboard players add @a ABGЗ 0
scoreboard players add @a ABG 0
scoreboard players add @a ABFQ 0
scoreboard players add @a ABFQЗ 0
scoreboard players add @a ABFQЖ 0
scoreboard players add @a ABFQГ 0
scoreboard players add @a ABFQГЗ 0
scoreboard players add @a ABFQГЖ 0
scoreboard players add @a ABFQГГ 0
scoreboard players add @a ABFQГГГ 0
scoreboard players add @a ABFБ 0
scoreboard players add @a ABFБГ 0
scoreboard players add @a ABFБГГГ 0
scoreboard players add @a ABFБZ 0
scoreboard players add @a ABFБZГ 0
scoreboard players add @a ABFБZГГГ 0
scoreboard players add @a ABJ 0
scoreboard players add @a ACFP 0
scoreboard players add @a ACFPГ 0
scoreboard players add @a ACFPГГ 0
scoreboard players add @a ACFPГГГ 0
scoreboard players add @a ACFPM 0
scoreboard players add @a ACFPMГ 0
scoreboard players add @a ACFPMГГГ 0
scoreboard players add @a ACFPMЗ 0
scoreboard players add @a ACFPMГЗ 0
scoreboard players add @a ACFPMГГГЗ 0
scoreboard players add @a ACFPW 0
scoreboard players add @a ACFPWЗ 0
scoreboard players add @a ACFT 0
scoreboard players add @a ACFTЖ 0
scoreboard players add @a ACFTЗ 0
scoreboard players add @a ACFQ 0
scoreboard players add @a ACFQЖ 0
scoreboard players add @a ACFQЗ 0
scoreboard players add @a ACFQГ 0
scoreboard players add @a ACFQГЗ 0
scoreboard players add @a ACFZ 0
scoreboard players add @a ACFZЖ 0
scoreboard players add @a ACFZЗ 0
scoreboard players add @a ACFO 0
scoreboard players add @a ACFOЗ 0
scoreboard players add @a ACFOЖ 0
scoreboard players add @a ACFOГ 0
scoreboard players add @a ACFOГЗ 0
scoreboard players add @a ACFOГЖ 0
scoreboard players add @a ACFOГГГ 0
scoreboard players add @a ACFOГГГЗ 0
scoreboard players add @a ACFOГГГЖ 0
scoreboard players add @a ACFOQГГГ 0
scoreboard players add @a ACFOQГГГЗ 0
scoreboard players add @a ACFS 0
scoreboard players add @a ACJ 0
scoreboard players add @a ACG 0
scoreboard players add @a ACGЗ 0
scoreboard players add @a ACF2 0
scoreboard players add @a ACIU 0
scoreboard players add @a ACIUГ 0
scoreboard players add @a ACFPU 0
scoreboard players add @a ACFPUЖ 0
scoreboard players add @a ACFPUГГГЖ 0
scoreboard players add @a ADITX 0
scoreboard players add @a ADGZЗ 0
scoreboard players add @a ADFM 0
scoreboard players add @a ADFMP 0
scoreboard players add @a ADFPZЖ 0
scoreboard players add @a ADFY 0
scoreboard players add @a ADFYГ 0
scoreboard players add @a ADFYГГГ 0
scoreboard players add @a ADEY 0
scoreboard players add @a ADEYГ 0
scoreboard players add @a ADEYГГГ 0
scoreboard players add @a ADFБX 0
scoreboard players add @a ADFБXK 0
scoreboard players add @a ADFXY 0
scoreboard players add @a ADFXYГ 0
scoreboard players add @a ADFXYГГГ 0
scoreboard players add @a ADFБ 0
scoreboard players add @a ADFБS 0
scoreboard players add @a ADFБM 0
scoreboard players add @a ADFT 0
scoreboard players add @a ADET 0
scoreboard players add @a ADETГ 0
scoreboard players add @a ADETЗ 0
scoreboard players add @a ADETГЗ 0
scoreboard players add @a ADEZ 0
scoreboard players add @a ADEZГ 0
scoreboard players add @a ADEZГГГ 0
scoreboard players add @a ADEZЗ 0
scoreboard players add @a ADEZГЗ 0
scoreboard players add @a ADEZM 0
scoreboard players add @a ADEZMГ 0
scoreboard players add @a ADEZMГГГ 0
scoreboard players add @a ADEZMЗ 0
scoreboard players add @a ADEZMГЗ 0
scoreboard players add @a ADFZ 0
scoreboard players add @a ADFZГ 0
scoreboard players add @a ADFZГГГ 0
scoreboard players add @a ADFZMГ 0
scoreboard players add @a ADFZЗ 0
scoreboard players add @a ADFZГЗ 0
scoreboard players add @a ADFZГГГЗ 0
scoreboard players add @a ADFZЖ 0
scoreboard players add @a ADEN 0
scoreboard players add @a ADENГ 0
scoreboard players add @a ADENГГГ 0
scoreboard players add @a ADFNГ 0
scoreboard players add @a ADFNГГГ 0
scoreboard players add @a ADHXZTUГЖЗ 0
scoreboard players add @a ADFXMД 0
scoreboard players add @a ADFXMГ 0
scoreboard players add @a ADFXMГГ 0
scoreboard players add @a ADFXMГГГ 0
scoreboard players add @a ADIR 0
scoreboard players add @a ADJM 0
scoreboard players add @a ADJMГ 0
scoreboard players add @a ADJ 0
scoreboard players add @a ADJZ 0
scoreboard players add @a ADGЗ 0
scoreboard players add @a ADG 0
scoreboard players add @a ADGД 0
scoreboard players add @a ADGДЗ 0
scoreboard players add @a ADFXP 0
scoreboard players add @a ADFXPГ 0
scoreboard players add @a ADFXPГГГ 0
scoreboard players add @a ADI2 0
scoreboard players add @a ADI2K 0
scoreboard players add @a ADI2M 0
scoreboard players add @a ADI2MK 0
scoreboard players add @a ADIU 0
scoreboard players add @a ADIUЖ 0
scoreboard players add @a ADIUГГГ 0
scoreboard players add @a ADIUГГГЖ 0

scoreboard players add @a BAEK 0
scoreboard players add @a BAEKЗ 0
scoreboard players add @a BAEKЖ 0
scoreboard players add @a BAEKЗЖ 0
scoreboard players add @a BAEKЖЗ 0
scoreboard players add @a BAEKГ 0
scoreboard players add @a BAEKГЗ 0
scoreboard players add @a BAEKГГГ 0
scoreboard players add @a BAEKД 0
scoreboard players add @a BAEKДГ 0
scoreboard players add @a BAEKSГГГ 0
scoreboard players add @a BAEL 0
scoreboard players add @a BAELГ 0
scoreboard players add @a BAEWM 0
scoreboard players add @a BAEWMГ 0
scoreboard players add @a BAEWMГГГ 0
scoreboard players add @a BAEW 0
scoreboard players add @a BAEWГ 0
scoreboard players add @a BAEWЗ 0
scoreboard players add @a BAFW 0
scoreboard players add @a BAFWГ 0
scoreboard players add @a BAGЗ 0
scoreboard players add @a BAG 0
scoreboard players add @a BAJ 0
scoreboard players add @a BAE1 0
scoreboard players add @a BAE1Г 0
scoreboard players add @a BAE2 0
scoreboard players add @a BAE2Г 0
scoreboard players add @a BBFV 0
scoreboard players add @a BBFVГ 0
scoreboard players add @a BBEV 0
scoreboard players add @a BBEVГ 0
scoreboard players add @a BBGЗ 0
scoreboard players add @a BBG 0
scoreboard players add @a BBFQ 0
scoreboard players add @a BBFQЗ 0
scoreboard players add @a BBFQЖ 0
scoreboard players add @a BBFQГ 0
scoreboard players add @a BBFQГЗ 0
scoreboard players add @a BBFQГЖ 0
scoreboard players add @a BBFQГГ 0
scoreboard players add @a BBFQГГГ 0
scoreboard players add @a BBFБ 0
scoreboard players add @a BBFБГ 0
scoreboard players add @a BBFБГГГ 0
scoreboard players add @a BBFБZ 0
scoreboard players add @a BBFБZГ 0
scoreboard players add @a BBFБZГГГ 0
scoreboard players add @a BBJ 0
scoreboard players add @a BCFP 0
scoreboard players add @a BCFPГ 0
scoreboard players add @a BCFPГГ 0
scoreboard players add @a BCFPГГГ 0
scoreboard players add @a BCFPM 0
scoreboard players add @a BCFPMГ 0
scoreboard players add @a BCFPMГГГ 0
scoreboard players add @a BCFPMЗ 0
scoreboard players add @a BCFPMГЗ 0
scoreboard players add @a BCFPMГГГЗ 0
scoreboard players add @a BCFPW 0
scoreboard players add @a BCFPWЗ 0
scoreboard players add @a BCFT 0
scoreboard players add @a BCFTЖ 0
scoreboard players add @a BCFTЗ 0
scoreboard players add @a BCFQ 0
scoreboard players add @a BCFQЖ 0
scoreboard players add @a BCFQЗ 0
scoreboard players add @a BCFQГ 0
scoreboard players add @a BCFQГЗ 0
scoreboard players add @a BCFZ 0
scoreboard players add @a BCFZЖ 0
scoreboard players add @a BCFZЗ 0
scoreboard players add @a BCFO 0
scoreboard players add @a BCFOЗ 0
scoreboard players add @a BCFOЖ 0
scoreboard players add @a BCFOГ 0
scoreboard players add @a BCFOГЗ 0
scoreboard players add @a BCFOГЖ 0
scoreboard players add @a BCFOГГГ 0
scoreboard players add @a BCFOГГГЗ 0
scoreboard players add @a BCFOГГГЖ 0
scoreboard players add @a BCFOQГГГ 0
scoreboard players add @a BCFOQГГГЗ 0
scoreboard players add @a BCFS 0
scoreboard players add @a BCJ 0
scoreboard players add @a BCG 0
scoreboard players add @a BCGЗ 0
scoreboard players add @a BCF2 0
scoreboard players add @a BCIU 0
scoreboard players add @a BCIUГ 0
scoreboard players add @a BCFPU 0
scoreboard players add @a BCFPUЖ 0
scoreboard players add @a BCFPUГГГЖ 0
scoreboard players add @a BDITX 0
scoreboard players add @a BDGZЗ 0
scoreboard players add @a BDFM 0
scoreboard players add @a BDFMP 0
scoreboard players add @a BDFPZЖ 0
scoreboard players add @a BDFY 0
scoreboard players add @a BDFYГ 0
scoreboard players add @a BDFYГГГ 0
scoreboard players add @a BDEY 0
scoreboard players add @a BDEYГ 0
scoreboard players add @a BDEYГГГ 0
scoreboard players add @a BDFБX 0
scoreboard players add @a BDFБXK 0
scoreboard players add @a BDFXY 0
scoreboard players add @a BDFXYГ 0
scoreboard players add @a BDFXYГГГ 0
scoreboard players add @a BDFБ 0
scoreboard players add @a BDFБS 0
scoreboard players add @a BDFБM 0
scoreboard players add @a BDFT 0
scoreboard players add @a BDET 0
scoreboard players add @a BDETГ 0
scoreboard players add @a BDETЗ 0
scoreboard players add @a BDETГЗ 0
scoreboard players add @a BDEZ 0
scoreboard players add @a BDEZГ 0
scoreboard players add @a BDEZГГГ 0
scoreboard players add @a BDEZЗ 0
scoreboard players add @a BDEZГЗ 0
scoreboard players add @a BDEZM 0
scoreboard players add @a BDEZMГ 0
scoreboard players add @a BDEZMГГГ 0
scoreboard players add @a BDEZMЗ 0
scoreboard players add @a BDEZMГЗ 0
scoreboard players add @a BDFZ 0
scoreboard players add @a BDFZГ 0
scoreboard players add @a BDFZГГГ 0
scoreboard players add @a BDFZMГ 0
scoreboard players add @a BDFZЗ 0
scoreboard players add @a BDFZГЗ 0
scoreboard players add @a BDFZГГГЗ 0
scoreboard players add @a BDFZЖ 0
scoreboard players add @a BDEN 0
scoreboard players add @a BDENГ 0
scoreboard players add @a BDENГГГ 0
scoreboard players add @a BDFNГ 0
scoreboard players add @a BDFNГГГ 0
scoreboard players add @a BDHXZTUГЖЗ 0
scoreboard players add @a BDFXMД 0
scoreboard players add @a BDFXMГ 0
scoreboard players add @a BDFXMГГ 0
scoreboard players add @a BDFXMГГГ 0
scoreboard players add @a BDIR 0
scoreboard players add @a BDJM 0
scoreboard players add @a BDJMГ 0
scoreboard players add @a BDJ 0
scoreboard players add @a BDJZ 0
scoreboard players add @a BDGЗ 0
scoreboard players add @a BDG 0
scoreboard players add @a BDGД 0
scoreboard players add @a BDGДЗ 0
scoreboard players add @a BDFXP 0
scoreboard players add @a BDFXPГ 0
scoreboard players add @a BDFXPГГГ 0
scoreboard players add @a BDI2 0
scoreboard players add @a BDI2K 0
scoreboard players add @a BDI2M 0
scoreboard players add @a BDI2MK 0
scoreboard players add @a BDIU 0
scoreboard players add @a BDIUЖ 0
scoreboard players add @a BDIUГГГ 0
scoreboard players add @a BDIUГГГЖ 0

scoreboard players add @a CAEK 0
scoreboard players add @a CAEKЗ 0
scoreboard players add @a CAEKЖ 0
scoreboard players add @a CAEKЗЖ 0
scoreboard players add @a CAEKЖЗ 0
scoreboard players add @a CAEKГ 0
scoreboard players add @a CAEKГЗ 0
scoreboard players add @a CAEKГГГ 0
scoreboard players add @a CAEKД 0
scoreboard players add @a CAEKДГ 0
scoreboard players add @a CAEKSГГГ 0
scoreboard players add @a CAEL 0
scoreboard players add @a CAELГ 0
scoreboard players add @a CAEWM 0
scoreboard players add @a CAEWMГ 0
scoreboard players add @a CAEWMГГГ 0
scoreboard players add @a CAEW 0
scoreboard players add @a CAEWГ 0
scoreboard players add @a CAEWЗ 0
scoreboard players add @a CAFW 0
scoreboard players add @a CAFWГ 0
scoreboard players add @a CAGЗ 0
scoreboard players add @a CAG 0
scoreboard players add @a CAJ 0
scoreboard players add @a CAE1 0
scoreboard players add @a CAE1Г 0
scoreboard players add @a CAE2 0
scoreboard players add @a CAE2Г 0
scoreboard players add @a CBFV 0
scoreboard players add @a CBFVГ 0
scoreboard players add @a CBEV 0
scoreboard players add @a CBEVГ 0
scoreboard players add @a CBGЗ 0
scoreboard players add @a CBG 0
scoreboard players add @a CBFQ 0
scoreboard players add @a CBFQЗ 0
scoreboard players add @a CBFQЖ 0
scoreboard players add @a CBFQГ 0
scoreboard players add @a CBFQГЗ 0
scoreboard players add @a CBFQГЖ 0
scoreboard players add @a CBFQГГ 0
scoreboard players add @a CBFQГГГ 0
scoreboard players add @a CBFБ 0
scoreboard players add @a CBFБГ 0
scoreboard players add @a CBFБГГГ 0
scoreboard players add @a CBFБZ 0
scoreboard players add @a CBFБZГ 0
scoreboard players add @a CBFБZГГГ 0
scoreboard players add @a CBJ 0
scoreboard players add @a CCFP 0
scoreboard players add @a CCFPГ 0
scoreboard players add @a CCFPГГ 0
scoreboard players add @a CCFPГГГ 0
scoreboard players add @a CCFPM 0
scoreboard players add @a CCFPMГ 0
scoreboard players add @a CCFPMГГГ 0
scoreboard players add @a CCFPMЗ 0
scoreboard players add @a CCFPMГЗ 0
scoreboard players add @a CCFPMГГГЗ 0
scoreboard players add @a CCFPW 0
scoreboard players add @a CCFPWЗ 0
scoreboard players add @a CCFT 0
scoreboard players add @a CCFTЖ 0
scoreboard players add @a CCFTЗ 0
scoreboard players add @a CCFQ 0
scoreboard players add @a CCFQЖ 0
scoreboard players add @a CCFQЗ 0
scoreboard players add @a CCFQГ 0
scoreboard players add @a CCFQГЗ 0
scoreboard players add @a CCFZ 0
scoreboard players add @a CCFZЖ 0
scoreboard players add @a CCFZЗ 0
scoreboard players add @a CCFO 0
scoreboard players add @a CCFOЗ 0
scoreboard players add @a CCFOЖ 0
scoreboard players add @a CCFOГ 0
scoreboard players add @a CCFOГЗ 0
scoreboard players add @a CCFOГЖ 0
scoreboard players add @a CCFOГГГ 0
scoreboard players add @a CCFOГГГЗ 0
scoreboard players add @a CCFOГГГЖ 0
scoreboard players add @a CCFOQГГГ 0
scoreboard players add @a CCFOQГГГЗ 0
scoreboard players add @a CCFS 0
scoreboard players add @a CCJ 0
scoreboard players add @a CCG 0
scoreboard players add @a CCGЗ 0
scoreboard players add @a CCF2 0
scoreboard players add @a CCIU 0
scoreboard players add @a CCIUГ 0
scoreboard players add @a CCFPU 0
scoreboard players add @a CCFPUЖ 0
scoreboard players add @a CCFPUГГГЖ 0
scoreboard players add @a CDITX 0
scoreboard players add @a CDGZЗ 0
scoreboard players add @a CDFM 0
scoreboard players add @a CDFMP 0
scoreboard players add @a CDFPZЖ 0
scoreboard players add @a CDFY 0
scoreboard players add @a CDFYГ 0
scoreboard players add @a CDFYГГГ 0
scoreboard players add @a CDEY 0
scoreboard players add @a CDEYГ 0
scoreboard players add @a CDEYГГГ 0
scoreboard players add @a CDFБX 0
scoreboard players add @a CDFБXK 0
scoreboard players add @a CDFXY 0
scoreboard players add @a CDFXYГ 0
scoreboard players add @a CDFXYГГГ 0
scoreboard players add @a CDFБ 0
scoreboard players add @a CDFБS 0
scoreboard players add @a CDFБM 0
scoreboard players add @a CDFT 0
scoreboard players add @a CDET 0
scoreboard players add @a CDETГ 0
scoreboard players add @a CDETЗ 0
scoreboard players add @a CDETГЗ 0
scoreboard players add @a CDEZ 0
scoreboard players add @a CDEZГ 0
scoreboard players add @a CDEZГГГ 0
scoreboard players add @a CDEZЗ 0
scoreboard players add @a CDEZГЗ 0
scoreboard players add @a CDEZM 0
scoreboard players add @a CDEZMГ 0
scoreboard players add @a CDEZMГГГ 0
scoreboard players add @a CDEZMЗ 0
scoreboard players add @a CDEZMГЗ 0
scoreboard players add @a CDFZ 0
scoreboard players add @a CDFZГ 0
scoreboard players add @a CDFZГГГ 0
scoreboard players add @a CDFZMГ 0
scoreboard players add @a CDFZЗ 0
scoreboard players add @a CDFZГЗ 0
scoreboard players add @a CDFZГГГЗ 0
scoreboard players add @a CDFZЖ 0
scoreboard players add @a CDEN 0
scoreboard players add @a CDENГ 0
scoreboard players add @a CDENГГГ 0
scoreboard players add @a CDFNГ 0
scoreboard players add @a CDFNГГГ 0
scoreboard players add @a CDHXZTUГЖЗ 0
scoreboard players add @a CDFXMД 0
scoreboard players add @a CDFXMГ 0
scoreboard players add @a CDFXMГГ 0
scoreboard players add @a CDFXMГГГ 0
scoreboard players add @a CDIR 0
scoreboard players add @a CDJM 0
scoreboard players add @a CDJMГ 0
scoreboard players add @a CDJ 0
scoreboard players add @a CDJZ 0
scoreboard players add @a CDGЗ 0
scoreboard players add @a CDG 0
scoreboard players add @a CDGД 0
scoreboard players add @a CDGДЗ 0
scoreboard players add @a CDFXP 0
scoreboard players add @a CDFXPГ 0
scoreboard players add @a CDFXPГГГ 0
scoreboard players add @a CDI2 0
scoreboard players add @a CDI2K 0
scoreboard players add @a CDI2M 0
scoreboard players add @a CDI2MK 0
scoreboard players add @a CDIU 0
scoreboard players add @a CDIUЖ 0
scoreboard players add @a CDIUГГГ 0
scoreboard players add @a CDIUГГГЖ 0

scoreboard players add @a DAEK 0
scoreboard players add @a DAEKЗ 0
scoreboard players add @a DAEKЖ 0
scoreboard players add @a DAEKЗЖ 0
scoreboard players add @a DAEKЖЗ 0
scoreboard players add @a DAEKГ 0
scoreboard players add @a DAEKГЗ 0
scoreboard players add @a DAEKГГГ 0
scoreboard players add @a DAEKД 0
scoreboard players add @a DAEKДГ 0
scoreboard players add @a DAEKSГГГ 0
scoreboard players add @a DAEL 0
scoreboard players add @a DAELГ 0
scoreboard players add @a DAEWM 0
scoreboard players add @a DAEWMГ 0
scoreboard players add @a DAEWMГГГ 0
scoreboard players add @a DAEW 0
scoreboard players add @a DAEWГ 0
scoreboard players add @a DAEWЗ 0
scoreboard players add @a DAFW 0
scoreboard players add @a DAFWГ 0
scoreboard players add @a DAGЗ 0
scoreboard players add @a DAG 0
scoreboard players add @a DAJ 0
scoreboard players add @a DAE1 0
scoreboard players add @a DAE1Г 0
scoreboard players add @a DAE2 0
scoreboard players add @a DAE2Г 0
scoreboard players add @a DBFV 0
scoreboard players add @a DBFVГ 0
scoreboard players add @a DBEV 0
scoreboard players add @a DBEVГ 0
scoreboard players add @a DBGЗ 0
scoreboard players add @a DBG 0
scoreboard players add @a DBFQ 0
scoreboard players add @a DBFQЗ 0
scoreboard players add @a DBFQЖ 0
scoreboard players add @a DBFQГ 0
scoreboard players add @a DBFQГЗ 0
scoreboard players add @a DBFQГЖ 0
scoreboard players add @a DBFQГГ 0
scoreboard players add @a DBFQГГГ 0
scoreboard players add @a DBFБ 0
scoreboard players add @a DBFБГ 0
scoreboard players add @a DBFБГГГ 0
scoreboard players add @a DBFБZ 0
scoreboard players add @a DBFБZГ 0
scoreboard players add @a DBFБZГГГ 0
scoreboard players add @a DBJ 0
scoreboard players add @a DCFP 0
scoreboard players add @a DCFPГ 0
scoreboard players add @a DCFPГГ 0
scoreboard players add @a DCFPГГГ 0
scoreboard players add @a DCFPM 0
scoreboard players add @a DCFPMГ 0
scoreboard players add @a DCFPMГГГ 0
scoreboard players add @a DCFPMЗ 0
scoreboard players add @a DCFPMГЗ 0
scoreboard players add @a DCFPMГГГЗ 0
scoreboard players add @a DCFPW 0
scoreboard players add @a DCFPWЗ 0
scoreboard players add @a DCFT 0
scoreboard players add @a DCFTЖ 0
scoreboard players add @a DCFTЗ 0
scoreboard players add @a DCFQ 0
scoreboard players add @a DCFQЖ 0
scoreboard players add @a DCFQЗ 0
scoreboard players add @a DCFQГ 0
scoreboard players add @a DCFQГЗ 0
scoreboard players add @a DCFZ 0
scoreboard players add @a DCFZЖ 0
scoreboard players add @a DCFZЗ 0
scoreboard players add @a DCFO 0
scoreboard players add @a DCFOЗ 0
scoreboard players add @a DCFOЖ 0
scoreboard players add @a DCFOГ 0
scoreboard players add @a DCFOГЗ 0
scoreboard players add @a DCFOГЖ 0
scoreboard players add @a DCFOГГГ 0
scoreboard players add @a DCFOГГГЗ 0
scoreboard players add @a DCFOГГГЖ 0
scoreboard players add @a DCFOQГГГ 0
scoreboard players add @a DCFOQГГГЗ 0
scoreboard players add @a DCFS 0
scoreboard players add @a DCJ 0
scoreboard players add @a DCG 0
scoreboard players add @a DCGЗ 0
scoreboard players add @a DCF2 0
scoreboard players add @a DCIU 0
scoreboard players add @a DCIUГ 0
scoreboard players add @a DCFPU 0
scoreboard players add @a DCFPUЖ 0
scoreboard players add @a DCFPUГГГЖ 0
scoreboard players add @a DDITX 0
scoreboard players add @a DDGZЗ 0
scoreboard players add @a DDFM 0
scoreboard players add @a DDFMP 0
scoreboard players add @a DDFPZЖ 0
scoreboard players add @a DDFY 0
scoreboard players add @a DDFYГ 0
scoreboard players add @a DDFYГГГ 0
scoreboard players add @a DDEY 0
scoreboard players add @a DDEYГ 0
scoreboard players add @a DDEYГГГ 0
scoreboard players add @a DDFБX 0
scoreboard players add @a DDFБXK 0
scoreboard players add @a DDFXY 0
scoreboard players add @a DDFXYГ 0
scoreboard players add @a DDFXYГГГ 0
scoreboard players add @a DDFБ 0
scoreboard players add @a DDFБS 0
scoreboard players add @a DDFБM 0
scoreboard players add @a DDFT 0
scoreboard players add @a DDET 0
scoreboard players add @a DDETГ 0
scoreboard players add @a DDETЗ 0
scoreboard players add @a DDETГЗ 0
scoreboard players add @a DDEZ 0
scoreboard players add @a DDEZГ 0
scoreboard players add @a DDEZГГГ 0
scoreboard players add @a DDEZЗ 0
scoreboard players add @a DDEZГЗ 0
scoreboard players add @a DDEZM 0
scoreboard players add @a DDEZMГ 0
scoreboard players add @a DDEZMГГГ 0
scoreboard players add @a DDEZMЗ 0
scoreboard players add @a DDEZMГЗ 0
scoreboard players add @a DDFZ 0
scoreboard players add @a DDFZГ 0
scoreboard players add @a DDFZГГГ 0
scoreboard players add @a DDFZMГ 0
scoreboard players add @a DDFZЗ 0
scoreboard players add @a DDFZГЗ 0
scoreboard players add @a DDFZГГГЗ 0
scoreboard players add @a DDFZЖ 0
scoreboard players add @a DDEN 0
scoreboard players add @a DDENГ 0
scoreboard players add @a DDENГГГ 0
scoreboard players add @a DDFNГ 0
scoreboard players add @a DDFNГГГ 0
scoreboard players add @a DDHXZTUГЖЗ 0
scoreboard players add @a DDFXMД 0
scoreboard players add @a DDFXMГ 0
scoreboard players add @a DDFXMГГ 0
scoreboard players add @a DDFXMГГГ 0
scoreboard players add @a DDIR 0
scoreboard players add @a DDJM 0
scoreboard players add @a DDJMГ 0
scoreboard players add @a DDJ 0
scoreboard players add @a DDJZ 0
scoreboard players add @a DDGЗ 0
scoreboard players add @a DDG 0
scoreboard players add @a DDGД 0
scoreboard players add @a DDGДЗ 0
scoreboard players add @a DDFXP 0
scoreboard players add @a DDFXPГ 0
scoreboard players add @a DDFXPГГГ 0
scoreboard players add @a DDI2 0
scoreboard players add @a DDI2K 0
scoreboard players add @a DDI2M 0
scoreboard players add @a DDI2MK 0
scoreboard players add @a DDIU 0
scoreboard players add @a DDIUЖ 0
scoreboard players add @a DDIUГГГ 0
scoreboard players add @a DDIUГГГЖ 0

scoreboard players add @a EAEK 0
scoreboard players add @a EAEKЗ 0
scoreboard players add @a EAEKЖ 0
scoreboard players add @a EAEKЗЖ 0
scoreboard players add @a EAEKЖЗ 0
scoreboard players add @a EAEKГ 0
scoreboard players add @a EAEKГЗ 0
scoreboard players add @a EAEKГГГ 0
scoreboard players add @a EAEKД 0
scoreboard players add @a EAEKДГ 0
scoreboard players add @a EAEKSГГГ 0
scoreboard players add @a EAEL 0
scoreboard players add @a EAELГ 0
scoreboard players add @a EAEWM 0
scoreboard players add @a EAEWMГ 0
scoreboard players add @a EAEWMГГГ 0
scoreboard players add @a EAEW 0
scoreboard players add @a EAEWГ 0
scoreboard players add @a EAEWЗ 0
scoreboard players add @a EAFW 0
scoreboard players add @a EAFWГ 0
scoreboard players add @a EAGЗ 0
scoreboard players add @a EAG 0
scoreboard players add @a EAJ 0
scoreboard players add @a EAE1 0
scoreboard players add @a EAE1Г 0
scoreboard players add @a EAE2 0
scoreboard players add @a EAE2Г 0
scoreboard players add @a EBFV 0
scoreboard players add @a EBFVГ 0
scoreboard players add @a EBEV 0
scoreboard players add @a EBEVГ 0
scoreboard players add @a EBGЗ 0
scoreboard players add @a EBG 0
scoreboard players add @a EBFQ 0
scoreboard players add @a EBFQЗ 0
scoreboard players add @a EBFQЖ 0
scoreboard players add @a EBFQГ 0
scoreboard players add @a EBFQГЗ 0
scoreboard players add @a EBFQГЖ 0
scoreboard players add @a EBFQГГ 0
scoreboard players add @a EBFQГГГ 0
scoreboard players add @a EBFБ 0
scoreboard players add @a EBFБГ 0
scoreboard players add @a EBFБГГГ 0
scoreboard players add @a EBFБZ 0
scoreboard players add @a EBFБZГ 0
scoreboard players add @a EBFБZГГГ 0
scoreboard players add @a EBJ 0
scoreboard players add @a ECFP 0
scoreboard players add @a ECFPГ 0
scoreboard players add @a ECFPГГ 0
scoreboard players add @a ECFPГГГ 0
scoreboard players add @a ECFPM 0
scoreboard players add @a ECFPMГ 0
scoreboard players add @a ECFPMГГГ 0
scoreboard players add @a ECFPMЗ 0
scoreboard players add @a ECFPMГЗ 0
scoreboard players add @a ECFPMГГГЗ 0
scoreboard players add @a ECFPW 0
scoreboard players add @a ECFPWЗ 0
scoreboard players add @a ECFT 0
scoreboard players add @a ECFTЖ 0
scoreboard players add @a ECFTЗ 0
scoreboard players add @a ECFQ 0
scoreboard players add @a ECFQЖ 0
scoreboard players add @a ECFQЗ 0
scoreboard players add @a ECFQГ 0
scoreboard players add @a ECFQГЗ 0
scoreboard players add @a ECFZ 0
scoreboard players add @a ECFZЖ 0
scoreboard players add @a ECFZЗ 0
scoreboard players add @a ECFO 0
scoreboard players add @a ECFOЗ 0
scoreboard players add @a ECFOЖ 0
scoreboard players add @a ECFOГ 0
scoreboard players add @a ECFOГЗ 0
scoreboard players add @a ECFOГЖ 0
scoreboard players add @a ECFOГГГ 0
scoreboard players add @a ECFOГГГЗ 0
scoreboard players add @a ECFOГГГЖ 0
scoreboard players add @a ECFOQГГГ 0
scoreboard players add @a ECFOQГГГЗ 0
scoreboard players add @a ECFS 0
scoreboard players add @a ECJ 0
scoreboard players add @a ECG 0
scoreboard players add @a ECGЗ 0
scoreboard players add @a ECF2 0
scoreboard players add @a ECIU 0
scoreboard players add @a ECIUГ 0
scoreboard players add @a ECFPU 0
scoreboard players add @a ECFPUЖ 0
scoreboard players add @a ECFPUГГГЖ 0
scoreboard players add @a EDITX 0
scoreboard players add @a EDGZЗ 0
scoreboard players add @a EDFM 0
scoreboard players add @a EDFMP 0
scoreboard players add @a EDFPZЖ 0
scoreboard players add @a EDFY 0
scoreboard players add @a EDFYГ 0
scoreboard players add @a EDFYГГГ 0
scoreboard players add @a EDEY 0
scoreboard players add @a EDEYГ 0
scoreboard players add @a EDEYГГГ 0
scoreboard players add @a EDFБX 0
scoreboard players add @a EDFБXK 0
scoreboard players add @a EDFXY 0
scoreboard players add @a EDFXYГ 0
scoreboard players add @a EDFXYГГГ 0
scoreboard players add @a EDFБ 0
scoreboard players add @a EDFБS 0
scoreboard players add @a EDFБM 0
scoreboard players add @a EDFT 0
scoreboard players add @a EDET 0
scoreboard players add @a EDETГ 0
scoreboard players add @a EDETЗ 0
scoreboard players add @a EDETГЗ 0
scoreboard players add @a EDEZ 0
scoreboard players add @a EDEZГ 0
scoreboard players add @a EDEZГГГ 0
scoreboard players add @a EDEZЗ 0
scoreboard players add @a EDEZГЗ 0
scoreboard players add @a EDEZM 0
scoreboard players add @a EDEZMГ 0
scoreboard players add @a EDEZMГГГ 0
scoreboard players add @a EDEZMЗ 0
scoreboard players add @a EDEZMГЗ 0
scoreboard players add @a EDFZ 0
scoreboard players add @a EDFZГ 0
scoreboard players add @a EDFZГГГ 0
scoreboard players add @a EDFZMГ 0
scoreboard players add @a EDFZЗ 0
scoreboard players add @a EDFZГЗ 0
scoreboard players add @a EDFZГГГЗ 0
scoreboard players add @a EDFZЖ 0
scoreboard players add @a EDEN 0
scoreboard players add @a EDENГ 0
scoreboard players add @a EDENГГГ 0
scoreboard players add @a EDFNГ 0
scoreboard players add @a EDFNГГГ 0
scoreboard players add @a EDHXZTUГЖЗ 0
scoreboard players add @a EDFXMД 0
scoreboard players add @a EDFXMГ 0
scoreboard players add @a EDFXMГГ 0
scoreboard players add @a EDFXMГГГ 0
scoreboard players add @a EDIR 0
scoreboard players add @a EDJM 0
scoreboard players add @a EDJMГ 0
scoreboard players add @a EDJ 0
scoreboard players add @a EDJZ 0
scoreboard players add @a EDGЗ 0
scoreboard players add @a EDG 0
scoreboard players add @a EDGД 0
scoreboard players add @a EDGДЗ 0
scoreboard players add @a EDFXP 0
scoreboard players add @a EDFXPГ 0
scoreboard players add @a EDFXPГГГ 0
scoreboard players add @a EDI2 0
scoreboard players add @a EDI2K 0
scoreboard players add @a EDI2M 0
scoreboard players add @a EDI2MK 0
scoreboard players add @a EDIU 0
scoreboard players add @a EDIUЖ 0
scoreboard players add @a EDIUГГГ 0
scoreboard players add @a EDIUГГГЖ 0

scoreboard players add @a FAEK 0
scoreboard players add @a FAEKЗ 0
scoreboard players add @a FAEKЖ 0
scoreboard players add @a FAEKЗЖ 0
scoreboard players add @a FAEKЖЗ 0
scoreboard players add @a FAEKГ 0
scoreboard players add @a FAEKГЗ 0
scoreboard players add @a FAEKГГГ 0
scoreboard players add @a FAEKД 0
scoreboard players add @a FAEKДГ 0
scoreboard players add @a FAEKSГГГ 0
scoreboard players add @a FAEL 0
scoreboard players add @a FAELГ 0
scoreboard players add @a FAEWM 0
scoreboard players add @a FAEWMГ 0
scoreboard players add @a FAEWMГГГ 0
scoreboard players add @a FAEW 0
scoreboard players add @a FAEWГ 0
scoreboard players add @a FAEWЗ 0
scoreboard players add @a FAFW 0
scoreboard players add @a FAFWГ 0
scoreboard players add @a FAGЗ 0
scoreboard players add @a FAG 0
scoreboard players add @a FAJ 0
scoreboard players add @a FAE1 0
scoreboard players add @a FAE1Г 0
scoreboard players add @a FAE2 0
scoreboard players add @a FAE2Г 0
scoreboard players add @a FBFV 0
scoreboard players add @a FBFVГ 0
scoreboard players add @a FBEV 0
scoreboard players add @a FBEVГ 0
scoreboard players add @a FBGЗ 0
scoreboard players add @a FBG 0
scoreboard players add @a FBFQ 0
scoreboard players add @a FBFQЗ 0
scoreboard players add @a FBFQЖ 0
scoreboard players add @a FBFQГ 0
scoreboard players add @a FBFQГЗ 0
scoreboard players add @a FBFQГЖ 0
scoreboard players add @a FBFQГГ 0
scoreboard players add @a FBFQГГГ 0
scoreboard players add @a FBFБ 0
scoreboard players add @a FBFБГ 0
scoreboard players add @a FBFБГГГ 0
scoreboard players add @a FBFБZ 0
scoreboard players add @a FBFБZГ 0
scoreboard players add @a FBFБZГГГ 0
scoreboard players add @a FBJ 0
scoreboard players add @a FCFP 0
scoreboard players add @a FCFPГ 0
scoreboard players add @a FCFPГГ 0
scoreboard players add @a FCFPГГГ 0
scoreboard players add @a FCFPM 0
scoreboard players add @a FCFPMГ 0
scoreboard players add @a FCFPMГГГ 0
scoreboard players add @a FCFPMЗ 0
scoreboard players add @a FCFPMГЗ 0
scoreboard players add @a FCFPMГГГЗ 0
scoreboard players add @a FCFPW 0
scoreboard players add @a FCFPWЗ 0
scoreboard players add @a FCFT 0
scoreboard players add @a FCFTЖ 0
scoreboard players add @a FCFTЗ 0
scoreboard players add @a FCFQ 0
scoreboard players add @a FCFQЖ 0
scoreboard players add @a FCFQЗ 0
scoreboard players add @a FCFQГ 0
scoreboard players add @a FCFQГЗ 0
scoreboard players add @a FCFZ 0
scoreboard players add @a FCFZЖ 0
scoreboard players add @a FCFZЗ 0
scoreboard players add @a FCFO 0
scoreboard players add @a FCFOЗ 0
scoreboard players add @a FCFOЖ 0
scoreboard players add @a FCFOГ 0
scoreboard players add @a FCFOГЗ 0
scoreboard players add @a FCFOГЖ 0
scoreboard players add @a FCFOГГГ 0
scoreboard players add @a FCFOГГГЗ 0
scoreboard players add @a FCFOГГГЖ 0
scoreboard players add @a FCFOQГГГ 0
scoreboard players add @a FCFOQГГГЗ 0
scoreboard players add @a FCFS 0
scoreboard players add @a FCJ 0
scoreboard players add @a FCG 0
scoreboard players add @a FCGЗ 0
scoreboard players add @a FCF2 0
scoreboard players add @a FCIU 0
scoreboard players add @a FCIUГ 0
scoreboard players add @a FCFPU 0
scoreboard players add @a FCFPUЖ 0
scoreboard players add @a FCFPUГГГЖ 0
scoreboard players add @a FDITX 0
scoreboard players add @a FDGZЗ 0
scoreboard players add @a FDFM 0
scoreboard players add @a FDFMP 0
scoreboard players add @a FDFPZЖ 0
scoreboard players add @a FDFY 0
scoreboard players add @a FDFYГ 0
scoreboard players add @a FDFYГГГ 0
scoreboard players add @a FDEY 0
scoreboard players add @a FDEYГ 0
scoreboard players add @a FDEYГГГ 0
scoreboard players add @a FDFБX 0
scoreboard players add @a FDFБXK 0
scoreboard players add @a FDFXY 0
scoreboard players add @a FDFXYГ 0
scoreboard players add @a FDFXYГГГ 0
scoreboard players add @a FDFБ 0
scoreboard players add @a FDFБS 0
scoreboard players add @a FDFБM 0
scoreboard players add @a FDFT 0
scoreboard players add @a FDET 0
scoreboard players add @a FDETГ 0
scoreboard players add @a FDETЗ 0
scoreboard players add @a FDETГЗ 0
scoreboard players add @a FDEZ 0
scoreboard players add @a FDEZГ 0
scoreboard players add @a FDEZГГГ 0
scoreboard players add @a FDEZЗ 0
scoreboard players add @a FDEZГЗ 0
scoreboard players add @a FDEZM 0
scoreboard players add @a FDEZMГ 0
scoreboard players add @a FDEZMГГГ 0
scoreboard players add @a FDEZMЗ 0
scoreboard players add @a FDEZMГЗ 0
scoreboard players add @a FDFZ 0
scoreboard players add @a FDFZГ 0
scoreboard players add @a FDFZГГГ 0
scoreboard players add @a FDFZMГ 0
scoreboard players add @a FDFZЗ 0
scoreboard players add @a FDFZГЗ 0
scoreboard players add @a FDFZГГГЗ 0
scoreboard players add @a FDFZЖ 0
scoreboard players add @a FDEN 0
scoreboard players add @a FDENГ 0
scoreboard players add @a FDENГГГ 0
scoreboard players add @a FDFNГ 0
scoreboard players add @a FDFNГГГ 0
scoreboard players add @a FDHXZTUГЖЗ 0
scoreboard players add @a FDFXMД 0
scoreboard players add @a FDFXMГ 0
scoreboard players add @a FDFXMГГ 0
scoreboard players add @a FDFXMГГГ 0
scoreboard players add @a FDIR 0
scoreboard players add @a FDJM 0
scoreboard players add @a FDJMГ 0
scoreboard players add @a FDJ 0
scoreboard players add @a FDJZ 0
scoreboard players add @a FDGЗ 0
scoreboard players add @a FDG 0
scoreboard players add @a FDGД 0
scoreboard players add @a FDGДЗ 0
scoreboard players add @a FDFXP 0
scoreboard players add @a FDFXPГ 0
scoreboard players add @a FDFXPГГГ 0
scoreboard players add @a FDI2 0
scoreboard players add @a FDI2K 0
scoreboard players add @a FDI2M 0
scoreboard players add @a FDI2MK 0
scoreboard players add @a FDIU 0
scoreboard players add @a FDIUЖ 0
scoreboard players add @a FDIUГГГ 0
scoreboard players add @a FDIUГГГЖ 0

