clear @p arx:skill_book_a_kit 0 1
give @p arx:skill_book_a_1
give @p arx:skill_book_a_2
give @p arx:skill_book_a_3
give @p arx:skill_book_a_4
give @p arx:skill_book_a_5
give @p arx:skill_book_a_6
give @p arx:skill_book_a_7
give @p arx:skill_book_a_8
give @p arx:skill_book_a_9
give @p arx:skill_book_a_10
give @p arx:skill_book_a_11
give @p arx:skill_book_a_12
give @p arx:skill_book_a_13
give @p arx:skill_book_a_14
give @p arx:skill_book_a_15
give @p arx:skill_book_a_16
give @p arx:skill_book_a_17
give @p arx:skill_book_a_18
give @p arx:skill_book_a_19
give @p arx:skill_book_a_20
give @p arx:skill_book_a_21
give @p arx:skill_book_a_22
give @p arx:skill_book_a_23
give @p arx:skill_book_a_24
give @p arx:skill_book_a_25
give @p arx:skill_book_a_26
give @p arx:skill_book_a_27
give @p arx:skill_book_a_28
give @p arx:skill_book_a_29