xp 5000 @s
clear @s arx:big_xp_book 0 1
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb
summon xp_orb