execute @a[scores={c_schizophrenic=1.., custom_random=1}] ~ ~ ~ playsound mob.chicken.say @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=2}] ~ ~ ~ playsound random.explode @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=3}] ~ ~ ~ playsound random.orb @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=4}] ~ ~ ~ playsound random.eat @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=5}] ~ ~ ~ playsound random.chestopen @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=6}] ~ ~ ~ playsound random.break @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=7}] ~ ~ ~ playsound random.door_close @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=8}] ~ ~ ~ playsound random.click @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=9}] ~ ~ ~ playsound fire.fire @p ~ ~ ~
execute @a[scores={c_schizophrenic=1.., custom_random=10}] ~ ~ ~ playsound ambient.weather.lightning.impact @p ~ ~ ~