scoreboard players add @p stability_core 0
scoreboard players add @p stability_const 0
scoreboard players add @p karma_pallas 0
scoreboard players add @p karma_pires 0
scoreboard players add @p attack_anim_rand 0
scoreboard players add @p case_counter_pl 0
scoreboard players add @p case_counter_pr 0
scoreboard players add @p case_random 0 
scoreboard players add @p custom_random 0 
scoreboard players add @p custom_random_b 0 
scoreboard players add @p drugs_delay 0
scoreboard players add @p gender 0
scoreboard players add @p respawn_delay 0
scoreboard players add @p time_h 0
scoreboard players add @p time_m 0
scoreboard players add @p water_delay 0
scoreboard players add @p water_block 0
scoreboard players add @p class 0
scoreboard players add @p religion 0
scoreboard players add @p no_religion 0
scoreboard players add @p target 0
scoreboard players add @p verify 0
scoreboard players add @p mp 0
scoreboard players add @p mp_max 0
scoreboard players add @p mp_delta 0
scoreboard players add @p mp_delay 0
scoreboard players add @p mp_tray 0
scoreboard players add @p poisoning 0
scoreboard players add @p pois_cond_delta 0
scoreboard players add @p pois_cond 0
scoreboard players add @p pois_cond_log 0
scoreboard players add @p pois_dec 0
scoreboard players add @p pois_block 0
scoreboard players add @p freezing_hold 0
scoreboard players add @p hot_hold 0
scoreboard players add @p mark 0
scoreboard players add @p regen_hp 0
scoreboard players add @p regen_mp 0
scoreboard players add @p heavy 0
scoreboard players add @p heavy_la 0
scoreboard players add @p heavy_ha 0
scoreboard players add @p heavy_delta 0
scoreboard players add @p heavy_log 0
scoreboard players add @p heavy_compens 0
scoreboard players add @p heavy_result 0
scoreboard players add @p final_mining 0
scoreboard players add @p sneese_prob 0
scoreboard players add @p cough_prob 0
scoreboard players add @p no_hard_ill 0
scoreboard players add @p no_dark_fog 0
scoreboard players add @p poit_mp_reg 0
scoreboard players add @p blocking 0
scoreboard players add @p poit_speed_a 0
scoreboard players add @p poit_speed_b 0
scoreboard players add @p poit_jump_a 0
scoreboard players add @p poit_jump_b 0
scoreboard players add @p poit_heigth_a 0
scoreboard players add @p poit_heigth_b 0
scoreboard players add @p poit_mining_u 0
scoreboard players add @p poit_mining_d 0
scoreboard players add @p poit_pois_dec_a 0
scoreboard players add @p poit_pois_dec_b 0
scoreboard players add @p poit_pois_dec_c 0
scoreboard players add @p poit_pois_dec_d 0
scoreboard players add @p mp_const 0
scoreboard players add @p speed_skill 0
scoreboard players add @p magic_skill 0
scoreboard players add @p strength_skill 0
scoreboard players add @p bow_result 0
scoreboard players add @p bow_spell_a 0
scoreboard players add @p bow_spell_b 0
scoreboard players add @p bow_spell_c 0
scoreboard players add @p bow_spell_d 0
scoreboard players add @p bow_tick 0
scoreboard players add @p jump_speed_up_a 0
scoreboard players add @p jump_speed_up_b 0
scoreboard players add @p jump_speed_up_c 0
scoreboard players add @p jump_speed_up_d 0
scoreboard players add @p jump_speed_up_e 0
scoreboard players add @p jump_speed_up_f 0
scoreboard players add @p resist_up_a 0
scoreboard players add @p resist_up_b 0
scoreboard players add @p resist_up_c 0
scoreboard players add @p resist_up_d 0
scoreboard players add @p final_speed 0
scoreboard players add @p final_jump 0
scoreboard players add @p final_strength 0
scoreboard players add @p final_weak 0
scoreboard players add @p final_resist 0
scoreboard players add @p final_slow 0
scoreboard players add @p regen_speed 0
scoreboard players add @p regen_effect 0
scoreboard players add @p regen_delay 0
scoreboard players add @p move_delay 0
scoreboard players add @p freezing 0
scoreboard players add @p stress 0
scoreboard players add @p stress_cond 0
scoreboard players add @p stress_co_delta 0
scoreboard players add @p stress_co_hist 0
scoreboard players add @p on_hurt_delay 0
scoreboard players add @p water_block_saki 0
scoreboard players add @p sin_host_block 0
scoreboard players add @p sin_host_saki 0
scoreboard players add @p blind_block 0
scoreboard players add @p blind_block_saki 0
scoreboard players add @p check_one_point 0
scoreboard players add @p demon_power 0
scoreboard players add @p weather 0
scoreboard players add @p weather_cond 0
scoreboard players add @p is_day 0 
scoreboard players add @p day_history 0
scoreboard players add @p day_delta 0
scoreboard players add @p in_battle 0
scoreboard players add @p regen_saki_a 0
scoreboard players add @p regen_saki_b 0
scoreboard players add @p regen_saki_c 0
scoreboard players add @p invisible 0
scoreboard players add @p invis_saki 0
scoreboard players add @p teleport_def 0
scoreboard players add @p teleport_dmg 0
scoreboard players add @p in_portal 0
scoreboard players add @p tp_backpoint 0
scoreboard players add @p no_fog 0
scoreboard players add @p nightvis_saki 0
scoreboard players add @p item_control 0
scoreboard players add @p online 0
scoreboard players add @p online_log 0
scoreboard players add @p xp_tray 0
scoreboard players set @p const_10 10
scoreboard players set @p const_-1 -1
scoreboard players set @p const_1000 1000
scoreboard players set @p const_100 100
scoreboard players set @p const_1500 1500
scoreboard players set @p const_1050 1050
scoreboard players add @p xp 0
scoreboard players add @p xp_lim_delta 0
scoreboard players add @p xp_stage 0
scoreboard players add @p xp_lim 0
scoreboard players add @p skill_point 0
scoreboard players add @p xp_х1_5 0
scoreboard players add @p ill_cancer 0
scoreboard players add @p ill_mild_cold 0
scoreboard players add @p ill_severe_cold 0
scoreboard players add @p ill_pneumonia 0
scoreboard players add @p ill_broken_leg 0
scoreboard players add @p ill_broken_arm 0
scoreboard players add @p ill_flu 0
scoreboard players add @p ill_helminth 0
scoreboard players add @p ill_appendicitis 0
scoreboard players add @p ill_anal_fissure 0
scoreboard players add @p ill_r_head 0
scoreboard players add @p ill_r_stomach 0
scoreboard players add @p AAEK 0
scoreboard players add @p AAEKЗ 0
scoreboard players add @p AAEKЖ 0
scoreboard players add @p AAEKЖЗ 0
scoreboard players add @p AAEKЗЖ 0
scoreboard players add @p AAEKГ 0
scoreboard players add @p AAEKГЗ 0
scoreboard players add @p AAEKГГГ 0
scoreboard players add @p AAEKД 0
scoreboard players add @p AAEKДГ 0
scoreboard players add @p AAEKSГГГ 0
scoreboard players add @p AAEL 0
scoreboard players add @p AAELГ 0
scoreboard players add @p AAEWM 0
scoreboard players add @p AAEWMГ 0
scoreboard players add @p AAEWMГГГ 0
scoreboard players add @p AAEW 0
scoreboard players add @p AAEWГ 0
scoreboard players add @p AAEWЗ 0
scoreboard players add @p AAFW 0
scoreboard players add @p AAFWГ 0
scoreboard players add @p AAGЗ 0
scoreboard players add @p AAG 0
scoreboard players add @p AAJ 0
scoreboard players add @p ABFV 0
scoreboard players add @p ABFVГ 0
scoreboard players add @p ABEV 0
scoreboard players add @p ABEVГ 0
scoreboard players add @p ABGЗ 0
scoreboard players add @p ABG 0
scoreboard players add @p ABFQ 0
scoreboard players add @p ABFQЗ 0
scoreboard players add @p ABFQЖ 0
scoreboard players add @p ABFQГ 0
scoreboard players add @p ABFQГЗ 0
scoreboard players add @p ABFQГЖ 0
scoreboard players add @p ABFQГГ 0
scoreboard players add @p ABFQГГГ 0
scoreboard players add @p ABJ 0
scoreboard players add @p ACFP 0
scoreboard players add @p ACFPГ 0
scoreboard players add @p ACFPГГ 0
scoreboard players add @p ACFPГГГ 0
scoreboard players add @p ACFPM 0
scoreboard players add @p ACFPMГ 0
scoreboard players add @p ACFPMГГГ 0
scoreboard players add @p ACFPMЗ 0
scoreboard players add @p ACFPMГЗ 0
scoreboard players add @p ACFPMГГГЗ 0
scoreboard players add @p ACFPW 0
scoreboard players add @p ACFPWЗ 0
scoreboard players add @p ACFT 0
scoreboard players add @p ACFTЖ 0
scoreboard players add @p ACFTЗ 0
scoreboard players add @p ACFQ 0
scoreboard players add @p ACFQЖ 0
scoreboard players add @p ACFQЗ 0
scoreboard players add @p ACFQГ 0
scoreboard players add @p ACFQГЗ 0
scoreboard players add @p ACFZ 0
scoreboard players add @p ACFZЖ 0
scoreboard players add @p ACFZЗ 0
scoreboard players add @p ACFO 0
scoreboard players add @p ACFOЗ 0
scoreboard players add @p ACFOЖ 0
scoreboard players add @p ACFOГ 0
scoreboard players add @p ACFOГЗ 0
scoreboard players add @p ACFOГЖ 0
scoreboard players add @p ACFOГГГ 0
scoreboard players add @p ACFOГГГЗ 0
scoreboard players add @p ACFOГГГЖ 0
scoreboard players add @p ACFOQГГГ 0
scoreboard players add @p ACFOQГГГЗ 0
scoreboard players add @p ACFS 0
scoreboard players add @p ACJ 0
scoreboard players add @p ACG 0
scoreboard players add @p ACGЗ 0
scoreboard players add @p ADITX 0
scoreboard players add @p ADGZЗ 0
scoreboard players add @p ADFM 0
scoreboard players add @p ADFMP 0
scoreboard players add @p ADFPZЖ 0
scoreboard players add @p ADFY 0
scoreboard players add @p ADFYГ 0
scoreboard players add @p ADFYГГГ 0
scoreboard players add @p ADEY 0
scoreboard players add @p ADEYГ 0
scoreboard players add @p ADEYГГГ 0
scoreboard players add @p ADFБX 0
scoreboard players add @p ADFБXK 0
scoreboard players add @p ADFXY 0
scoreboard players add @p ADFXYГ 0
scoreboard players add @p ADFXYГГГ 0
scoreboard players add @p ADFБ 0
scoreboard players add @p ADFБS 0
scoreboard players add @p ADFБM 0
scoreboard players add @p ADFT 0
scoreboard players add @p ADET 0
scoreboard players add @p ADETГ 0
scoreboard players add @p ADETЗ 0
scoreboard players add @p ADETГЗ 0
scoreboard players add @p ADEZ 0
scoreboard players add @p ADEZГ 0
scoreboard players add @p ADEZГГГ 0
scoreboard players add @p ADEZЗ 0
scoreboard players add @p ADEZГЗ 0
scoreboard players add @p ADEZM 0
scoreboard players add @p ADEZMГ 0
scoreboard players add @p ADEZMГГГ 0
scoreboard players add @p ADEZMЗ 0
scoreboard players add @p ADEZMГЗ 0
scoreboard players add @p ADFZ 0
scoreboard players add @p ADFZГ 0
scoreboard players add @p ADFZГГГ 0
scoreboard players add @p ADFZMГ 0
scoreboard players add @p ADFZЗ 0
scoreboard players add @p ADFZГЗ 0
scoreboard players add @p ADFZГГГЗ 0
scoreboard players add @p ADFZЖ 0
scoreboard players add @p ADEN 0
scoreboard players add @p ADENГ 0
scoreboard players add @p ADENГГГ 0
scoreboard players add @p ADFNГ 0
scoreboard players add @p ADFNГГГ 0
scoreboard players add @p ADHXZTUГЖЗ 0
scoreboard players add @p ADFXMГГГ 0
scoreboard players add @p ADIR 0
scoreboard players add @p ADJM 0
scoreboard players add @p ADJMГ 0
scoreboard players add @p ADJ 0
scoreboard players add @p ADJZ 0
scoreboard players add @p ADGЗ 0
scoreboard players add @p ADG 0
scoreboard players add @p ADGД 0
scoreboard players add @p ADGДЗ 0
scoreboard players add @p ADFXP 0
scoreboard players add @p ADFXPГ 0
scoreboard players add @p ADFXPГГГ 0
scoreboard players add @p BAEK 0
scoreboard players add @p BAEKЗ 0
scoreboard players add @p BAEKЖ 0
scoreboard players add @p BAEKЖЗ 0
scoreboard players add @p BAEKЗЖ 0
scoreboard players add @p BAEKГ 0
scoreboard players add @p BAEKГЗ 0
scoreboard players add @p BAEKГГГ 0
scoreboard players add @p BAEKД 0
scoreboard players add @p BAEKДГ 0
scoreboard players add @p BAEKSГГГ 0
scoreboard players add @p BAEL 0
scoreboard players add @p BAELГ 0
scoreboard players add @p BAEWM 0
scoreboard players add @p BAEWMГ 0
scoreboard players add @p BAEWMГГГ 0
scoreboard players add @p BAEW 0
scoreboard players add @p BAEWГ 0
scoreboard players add @p BAEWЗ 0
scoreboard players add @p BAFW 0
scoreboard players add @p BAFWГ 0
scoreboard players add @p BAGЗ 0
scoreboard players add @p BAG 0
scoreboard players add @p BAJ 0
scoreboard players add @p BBFV 0
scoreboard players add @p BBFVГ 0
scoreboard players add @p BBEV 0
scoreboard players add @p BBEVГ 0
scoreboard players add @p BBGЗ 0
scoreboard players add @p BBG 0
scoreboard players add @p BBFQ 0
scoreboard players add @p BBFQЗ 0
scoreboard players add @p BBFQЖ 0
scoreboard players add @p BBFQГ 0
scoreboard players add @p BBFQГЗ 0
scoreboard players add @p BBFQГЖ 0
scoreboard players add @p BBFQГГ 0
scoreboard players add @p BBFQГГГ 0
scoreboard players add @p BBJ 0
scoreboard players add @p BCFP 0
scoreboard players add @p BCFPГ 0
scoreboard players add @p BCFPГГ 0
scoreboard players add @p BCFPГГГ 0
scoreboard players add @p BCFPM 0
scoreboard players add @p BCFPMГ 0
scoreboard players add @p BCFPMГГГ 0
scoreboard players add @p BCFPMЗ 0
scoreboard players add @p BCFPMГЗ 0
scoreboard players add @p BCFPMГГГЗ 0
scoreboard players add @p BCFPW 0
scoreboard players add @p BCFPWЗ 0
scoreboard players add @p BCFT 0
scoreboard players add @p BCFTЖ 0
scoreboard players add @p BCFTЗ 0
scoreboard players add @p BCFQ 0
scoreboard players add @p BCFQЖ 0
scoreboard players add @p BCFQЗ 0
scoreboard players add @p BCFQГ 0
scoreboard players add @p BCFQГЗ 0
scoreboard players add @p BCFZ 0
scoreboard players add @p BCFZЖ 0
scoreboard players add @p BCFZЗ 0
scoreboard players add @p BCFO 0
scoreboard players add @p BCFOЗ 0
scoreboard players add @p BCFOЖ 0
scoreboard players add @p BCFOГ 0
scoreboard players add @p BCFOГЗ 0
scoreboard players add @p BCFOГЖ 0
scoreboard players add @p BCFOГГГ 0
scoreboard players add @p BCFOГГГЗ 0
scoreboard players add @p BCFOГГГЖ 0
scoreboard players add @p BCFOQГГГ 0
scoreboard players add @p BCFOQГГГЗ 0
scoreboard players add @p BCFS 0
scoreboard players add @p BCJ 0
scoreboard players add @p BCG 0
scoreboard players add @p BCGЗ 0
scoreboard players add @p BDITX 0
scoreboard players add @p BDGZЗ 0
scoreboard players add @p BDFM 0
scoreboard players add @p BDFMP 0
scoreboard players add @p BDFPZЖ 0
scoreboard players add @p BDFY 0
scoreboard players add @p BDFYГ 0
scoreboard players add @p BDFYГГГ 0
scoreboard players add @p BDEY 0
scoreboard players add @p BDEYГ 0
scoreboard players add @p BDEYГГГ 0
scoreboard players add @p BDFБX 0
scoreboard players add @p BDFБXK 0
scoreboard players add @p BDFXY 0
scoreboard players add @p BDFXYГ 0
scoreboard players add @p BDFXYГГГ 0
scoreboard players add @p BDFБ 0
scoreboard players add @p BDFБS 0
scoreboard players add @p BDFБM 0
scoreboard players add @p BDFT 0
scoreboard players add @p BDET 0
scoreboard players add @p BDETГ 0
scoreboard players add @p BDETЗ 0
scoreboard players add @p BDETГЗ 0
scoreboard players add @p BDEZ 0
scoreboard players add @p BDEZГ 0
scoreboard players add @p BDEZГГГ 0
scoreboard players add @p BDEZЗ 0
scoreboard players add @p BDEZГЗ 0
scoreboard players add @p BDEZM 0
scoreboard players add @p BDEZMГ 0
scoreboard players add @p BDEZMГГГ 0
scoreboard players add @p BDEZMЗ 0
scoreboard players add @p BDEZMГЗ 0
scoreboard players add @p BDFZ 0
scoreboard players add @p BDFZГ 0
scoreboard players add @p BDFZГГГ 0
scoreboard players add @p BDFZMГ 0
scoreboard players add @p BDFZЗ 0
scoreboard players add @p BDFZГЗ 0
scoreboard players add @p BDFZГГГЗ 0
scoreboard players add @p BDFZЖ 0
scoreboard players add @p BDEN 0
scoreboard players add @p BDENГ 0
scoreboard players add @p BDENГГГ 0
scoreboard players add @p BDFNГ 0
scoreboard players add @p BDFNГГГ 0
scoreboard players add @p BDHXZTUГЖЗ 0
scoreboard players add @p BDFXMГГГ 0
scoreboard players add @p BDIR 0
scoreboard players add @p BDJM 0
scoreboard players add @p BDJMГ 0
scoreboard players add @p BDJ 0
scoreboard players add @p BDJZ 0
scoreboard players add @p BDGЗ 0
scoreboard players add @p BDG 0
scoreboard players add @p BDGД 0
scoreboard players add @p BDGДЗ 0
scoreboard players add @p BDFXP 0
scoreboard players add @p BDFXPГ 0
scoreboard players add @p BDFXPГГГ 0
scoreboard players add @p CAEK 0
scoreboard players add @p CAEKЗ 0
scoreboard players add @p CAEKЖ 0
scoreboard players add @p CAEKЖЗ 0
scoreboard players add @p CAEKЗЖ 0
scoreboard players add @p CAEKГ 0
scoreboard players add @p CAEKГЗ 0
scoreboard players add @p CAEKГГГ 0
scoreboard players add @p CAEKД 0
scoreboard players add @p CAEKДГ 0
scoreboard players add @p CAEKSГГГ 0
scoreboard players add @p CAEL 0
scoreboard players add @p CAELГ 0
scoreboard players add @p CAEWM 0
scoreboard players add @p CAEWMГ 0
scoreboard players add @p CAEWMГГГ 0
scoreboard players add @p CAEW 0
scoreboard players add @p CAEWГ 0
scoreboard players add @p CAEWЗ 0
scoreboard players add @p CAFW 0
scoreboard players add @p CAFWГ 0
scoreboard players add @p CAGЗ 0
scoreboard players add @p CAG 0
scoreboard players add @p CAJ 0
scoreboard players add @p CBFV 0
scoreboard players add @p CBFVГ 0
scoreboard players add @p CBEV 0
scoreboard players add @p CBEVГ 0
scoreboard players add @p CBGЗ 0
scoreboard players add @p CBG 0
scoreboard players add @p CBFQ 0
scoreboard players add @p CBFQЗ 0
scoreboard players add @p CBFQЖ 0
scoreboard players add @p CBFQГ 0
scoreboard players add @p CBFQГЗ 0
scoreboard players add @p CBFQГЖ 0
scoreboard players add @p CBFQГГ 0
scoreboard players add @p CBFQГГГ 0
scoreboard players add @p CBJ 0
scoreboard players add @p CCFP 0
scoreboard players add @p CCFPГ 0
scoreboard players add @p CCFPГГ 0
scoreboard players add @p CCFPГГГ 0
scoreboard players add @p CCFPM 0
scoreboard players add @p CCFPMГ 0
scoreboard players add @p CCFPMГГГ 0
scoreboard players add @p CCFPMЗ 0
scoreboard players add @p CCFPMГЗ 0
scoreboard players add @p CCFPMГГГЗ 0
scoreboard players add @p CCFPW 0
scoreboard players add @p CCFPWЗ 0
scoreboard players add @p CCFT 0
scoreboard players add @p CCFTЖ 0
scoreboard players add @p CCFTЗ 0
scoreboard players add @p CCFQ 0
scoreboard players add @p CCFQЖ 0
scoreboard players add @p CCFQЗ 0
scoreboard players add @p CCFQГ 0
scoreboard players add @p CCFQГЗ 0
scoreboard players add @p CCFZ 0
scoreboard players add @p CCFZЖ 0
scoreboard players add @p CCFZЗ 0
scoreboard players add @p CCFO 0
scoreboard players add @p CCFOЗ 0
scoreboard players add @p CCFOЖ 0
scoreboard players add @p CCFOГ 0
scoreboard players add @p CCFOГЗ 0
scoreboard players add @p CCFOГЖ 0
scoreboard players add @p CCFOГГГ 0
scoreboard players add @p CCFOГГГЗ 0
scoreboard players add @p CCFOГГГЖ 0
scoreboard players add @p CCFOQГГГ 0
scoreboard players add @p CCFOQГГГЗ 0
scoreboard players add @p CCFS 0
scoreboard players add @p CCJ 0
scoreboard players add @p CCG 0
scoreboard players add @p CCGЗ 0
scoreboard players add @p CDITX 0
scoreboard players add @p CDGZЗ 0
scoreboard players add @p CDFM 0
scoreboard players add @p CDFMP 0
scoreboard players add @p CDFPZЖ 0
scoreboard players add @p CDFY 0
scoreboard players add @p CDFYГ 0
scoreboard players add @p CDFYГГГ 0
scoreboard players add @p CDEY 0
scoreboard players add @p CDEYГ 0
scoreboard players add @p CDEYГГГ 0
scoreboard players add @p CDFБX 0
scoreboard players add @p CDFБXK 0
scoreboard players add @p CDFXY 0
scoreboard players add @p CDFXYГ 0
scoreboard players add @p CDFXYГГГ 0
scoreboard players add @p CDFБ 0
scoreboard players add @p CDFБS 0
scoreboard players add @p CDFБM 0
scoreboard players add @p CDFT 0
scoreboard players add @p CDET 0
scoreboard players add @p CDETГ 0
scoreboard players add @p CDETЗ 0
scoreboard players add @p CDETГЗ 0
scoreboard players add @p CDEZ 0
scoreboard players add @p CDEZГ 0
scoreboard players add @p CDEZГГГ 0
scoreboard players add @p CDEZЗ 0
scoreboard players add @p CDEZГЗ 0
scoreboard players add @p CDEZM 0
scoreboard players add @p CDEZMГ 0
scoreboard players add @p CDEZMГГГ 0
scoreboard players add @p CDEZMЗ 0
scoreboard players add @p CDEZMГЗ 0
scoreboard players add @p CDFZ 0
scoreboard players add @p CDFZГ 0
scoreboard players add @p CDFZГГГ 0
scoreboard players add @p CDFZMГ 0
scoreboard players add @p CDFZЗ 0
scoreboard players add @p CDFZГЗ 0
scoreboard players add @p CDFZГГГЗ 0
scoreboard players add @p CDFZЖ 0
scoreboard players add @p CDEN 0
scoreboard players add @p CDENГ 0
scoreboard players add @p CDENГГГ 0
scoreboard players add @p CDFNГ 0
scoreboard players add @p CDFNГГГ 0
scoreboard players add @p CDHXZTUГЖЗ 0
scoreboard players add @p CDFXMГГГ 0
scoreboard players add @p CDIR 0
scoreboard players add @p CDJM 0
scoreboard players add @p CDJMГ 0
scoreboard players add @p CDJ 0
scoreboard players add @p CDJZ 0
scoreboard players add @p CDGЗ 0
scoreboard players add @p CDG 0
scoreboard players add @p CDGД 0
scoreboard players add @p CDGДЗ 0
scoreboard players add @p CDFXP 0
scoreboard players add @p CDFXPГ 0
scoreboard players add @p CDFXPГГГ 0
scoreboard players add @p tick_nosempra_a 0
scoreboard players add @p tick_nosempra_b 0
scoreboard players add @p tick_nosempra_c 0
scoreboard players add @p tick_sempra_dps 0
scoreboard players add @p tick 0
scoreboard players add @p sec 0
scoreboard players add @p attack_weakness 0
scoreboard players add @p trait_random 0
scoreboard players add @p c_cowardly 0
scoreboard players add @p c_schizophrenic 0
scoreboard players add @p c_stupid 0
scoreboard players add @p c_paranoid 0
scoreboard players add @p c_nospider 0
scoreboard players add @p c_nonecro 0
scoreboard players add @p c_nosocio 0
scoreboard players add @p c_notecno 0
scoreboard players add @p c_nodarkness 0
scoreboard players add @p c_nomines 0
scoreboard players add @p c_religious 0
scoreboard players add @p c_nolight 0
scoreboard players add @p c_nocold 0
scoreboard players add @p c_nowarm 0
scoreboard players add @p c_indifference 0
scoreboard players add @p c_angry 0
scoreboard players add @p c_loner 0
scoreboard players add @p c_rude 0
scoreboard players add @p c_warmy 0
scoreboard players add @p c_coldy 0
scoreboard players add @p c_inflexible 0
scoreboard players add @p c_powerful 0
scoreboard players add @p c_indeclinable 0
scoreboard players add @p c_enlightened 0
scoreboard players add @p c_bright_look 0
scoreboard players add @p c_wise 0
scoreboard players add @p c_persistent 0
scoreboard players add @p c_seen_death 0
scoreboard players add @p c_demon 0
scoreboard players add @p t_f_spicy 0
scoreboard players add @p t_f_salty 0
scoreboard players add @p t_f_sweet 0
scoreboard players add @p t_f_sour 0
scoreboard players add @p t_f_exotic 0
scoreboard players add @p t_f_deliciousness 0
scoreboard players add @p t_f_poisoning 0
scoreboard players add @p t_spicy 0 
scoreboard players add @p t_salty 0
scoreboard players add @p t_sweet 0
scoreboard players add @p t_sour 0
scoreboard players add @p t_exotic 0
scoreboard players add @p t_herbal 0
scoreboard players add @p t_meat 0
scoreboard players add @p t_fish 0
scoreboard players add @p t_bread 0
scoreboard players add @p t_lactic 0
scoreboard players add @p food_tray_stress 0
scoreboard players add @p food_tray_prime 0
scoreboard players add @p book_asar_i 0
scoreboard players add @p book_asar_ii 0
scoreboard players add @p book_asar_iii 0
scoreboard players add @p book_asar_iv 0
scoreboard players add @p book_th_ab_gods 0
scoreboard players add @p book_golfari 0
scoreboard players add @p book_namel_pal 0
scoreboard players add @p book_holy_sakura 0
scoreboard players add @p book_wand_puppet 0
scoreboard players add @p book_dragon_arti 0
scoreboard players add @p book_dext 0
scoreboard players add @p book_philosophy 0
scoreboard players add @p armor_assas_dmg 0
scoreboard players add @p armor_conq_dmg 0
scoreboard players add @p armor_ranger_dmg 0